### ISSUE TITLE
Add g++ version to SystemRequirements field in DESCRIPTION

### ISSUE THREAD

**Issue by dashaub** [RcppCore/RcppArmadillo#107]
Related to #97 , adding information about the required g++ version in the DESCRIPTION would make selecting an appropriate release easier. I realize that the `SystemRequirements` field doesn't really enforce anything, but the user information would nonetheless be helpful.

**Comment by eddelbuettel** [comment]
Yes, could do though it won't help you going backwards.  :-/   

But you have a point that DESCRIPTION is a little bare right now.  Too bad I just shipped a release (currently pending checks at CRAN...)

**Comment by dashaub** [comment]
Right, your suggested heuristic to look at Armadillo major versions or a manual binary search across versions works ok for now--either checking the configure file or just trying the install until some version works. `SystemRequirements` might make things a little easier next time there is a bumped version dependency. More documentation (almost) never hurts.

**Comment by eddelbuettel** [comment]
I can definitely add a free-format sentence to Description: a la "RcppArmadillo works best with g++ versions 4.6 or newer, and now reports an error for older version."
