### ISSUE TITLE
update sample.h for sort and sort_index interface change

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#111]

**Comment by coatless** [comment]
I have this

**Comment by eddelbuettel** [comment]
Too late, bud.

**Comment by coatless** [comment]
Blah.

**Comment by eddelbuettel** [comment]
Sorry 'bout that but as they tell you in primary school, don't work in isolation in the dark -- file an issue!

In all seriousness I think I added `Contributing.md` files in one or two repos strongly suggesting issue tickets _before_ pull requests.

**Comment by coatless** [comment]
Normally claiming on SO was sufficient before:

http://stackoverflow.com/a/40241213/1345455

**Comment by eddelbuettel** [comment]
That fell into the gap of "getting up at home to get to work" and "sitting down at work".  In the meantime, I fixed it on the laptop.

**Comment by coatless** [comment]
Oh well, moving on to other things. I'll stash the changes. FYI, `RcppExports.R` and `RcppExports.cpp` need to be updated.

**Comment by eddelbuettel** [comment]
That too is in my commit.

**Comment by coatless** [comment]
And if you could, please a `&` to the `arma::vec &prob_`

```cpp
        T sample(const T &x, const int size, const bool replace, arma::vec &prob_)
```

**Comment by eddelbuettel** [comment]
If only you and I had something like a slack channel ...  :grinning:

Again, too bad about the wasted energy but _c'est la vie_

**Comment by eddelbuettel** [comment]
Line 59, correct?

**Comment by coatless** [comment]
My editor has it on line 62:

This is the function:

```cpp
        template <class T> 
        T sample(const T &x, const int size, const bool replace, arma::vec &prob_){
          return sample_main(x, size, replace, prob_);
        }
```

**Comment by eddelbuettel** [comment]
Yes, sorry, me too.  Magit diff unstages shows the diff output and 59 is the line of the diff segment. My operator error.  Your error was throwing a random line out.   GH is good at links with lines ...

I guess the only real fail here is that you should have opened an upstream ticket (here) when you filed the client ticket you filed for gmwm :disappointed:

**Comment by coatless** [comment]
@eddelbuettel: Cost of a speedy response to raise flag / highlight a change and ensure it made it into the commit. 

And, aye, not filing a ticket here was an oversight on my part since the code base has a local copy of the sampling class vs. calling it within the RcppArmadillo namespace.
