### ISSUE TITLE
RcppArmadillo sp_mat doesn't interpret Sparse Symmetric Matrix correctly

### ISSUE THREAD

**Issue by jeffwong-nflx** [RcppCore/RcppArmadillo#114]
This code produces a sparse symmetric matrix, a special case when crossprod(x) is known to be symmetric.

```
require(Matrix)
x = rsparsematrix(10000, 50, .05)
x2 = crossprod(x)
```
Note that the nonzero values stored in x2 only reflect the upper triangle

```
x2@x #only upper triangle part!
```

When this is sent to RcppArmadillo as a sp_mat, only the upper triangle is sent, and it thinks that the lower triangle is all 0

```
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
sp_mat foo(sp_mat X) {
  return X;
}
foo(crossprod(rsparsematrix(10000, 5, .01)))
```

**Comment by eddelbuettel** [comment]
Thanks for the bug report, and for bringing it here.  I will try to take a look.

I think the overarching issue may be that we have a larger number of possibly representations in the Matrix package than are currently handled by the converters.  So it will require someone to sit down and write those.

**Comment by thirdwing** [comment]
This seems very similar to #17 .

I will take a look in the weekend.

**Comment by thirdwing** [comment]
I was thinking using `symmatu() / symmatl()` to handle the symmetric matrix. However, it only works on `arma::mat` not `arma::sp_mat`.

More complicated than I thought.

**Comment by coatless** [comment]
FYI: 

Sparse support was just added today for...

- `symmatu()` / `symmatl()` in https://github.com/conradsnicta/armadillo-code/commit/d99b8241e299e61058038294001e71acb77e7f74
- `trimatu()`/`trimatl()` in  https://github.com/conradsnicta/armadillo-code/commit/f294d3bca5508cc44ce2a744f6b908854372794b

**Comment by thirdwing** [comment]
WOW~!

Let's complete GSOC project idea!

**Comment by eddelbuettel** [comment]
@conradsnicta being Conrad, I am of course prohibited from following the repo.  #facepalm

**Comment by coatless** [comment]
You can prohibit someone from following a repo?

**Comment by eddelbuettel** [comment]
Apparently.  Looks like you snug in before he changes that setting.

**Comment by jeffwong-nflx** [comment]
Great, it looks like it exists in the upstream Armadillo project, but if I understand correctly there is no wrapping in Rcpp?

**Comment by coatless** [comment]
Should be coming over the summer according to the GSOC project:

https://github.com/rstats-gsoc/gsoc2017/wiki/Sparse-matrix-automatic-conversion-in-RcppArmadillo

**Comment by eddelbuettel** [comment]
Slowly, young man. Having file a GSoC _proposal_ is not the same as _getting it accepted_ after which it may still not get _done_ right ...

**Comment by binxiangni** [comment]
The support for symmetric numeric sparse matrices inherited from CsparseMatrix, TsparseMatrix & RsparseMatrix has been added. You are welcomed to use it and report possible bugs when the newest package is released. @jeffwong-nflx If you have need to use logical numeric sparse matrices, could please give me some examples of their applications?

**Comment by eddelbuettel** [comment]
@binxiangni Given your PRs in master, can we close this?

**Comment by binxiangni** [comment]
I believe so.
