### ISSUE TITLE
Clarify documentation (in Rd files) on RNG use

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#117]
Tickled by [this SO question](http://stackoverflow.com/questions/41250974/what-is-the-random-number-generator-that-armadillo-uses).

**Comment by coatless** [comment]
Two areas in the code need to be updated. Perhaps a `/man-roxygen` with a `@template` could be created instead of the copy + paste.

[File](https://github.com/RcppCore/RcppArmadillo/blob/9e344e60d57c7b025a2193bafeb991ac5a161a5f/src/RcppArmadillo.cpp#L58)

Original:

> Depending on whether RcppArmadillo was compiled for the C++98 standard 
(currently the default) or for C++11 (optional), two different RNGs may be used. 
This function resets either. For C++98, the system library RNG is used. It may
have poor performance, particularly on older versions of Windows. For C++11, the
RNG included in its library is used.

New:

> Depending on whether RcppArmadillo was compiled for the C++98 standard 
(currently the default) or for C++11 (optional), two different RNGs may be used. 
This function resets either. For C++98, **the R programming language's RNG is used.**
It may have poor performance, particularly on older versions of Windows. 
For C++11, the RNG included in **the \code{<random>}** library is used. **To enable
at compile-time the C++11 RNG option, add \code{#define ARMA_USE_CXX11_RNG}
before the \code{#include <RcppArmadillo.h>}.**

**Comment by lesshaste** [comment]
In what way does the R programming language's RNG have poor performance on older versions of Windows?  Is there a reference that can be included that explains this in more detail? (E.g. which versions of Windows.)

**Comment by eddelbuettel** [comment]
> In what way does the R programming language's RNG have poor performance on older versions of Windows? 

You misread. That is from the _Armadillo_ documentation.  R always ships its own RNGs (plural) which are (as you would expect from a statistical tool) good.

**Comment by lesshaste** [comment]
OK thanks. 

I was reading the proposed "New:" version in the comment by coatless just above. There it says

> 
> For C++98, the R programming language's RNG is used.
> It may have poor performance, particularly on older versions of Windows.

**Comment by eddelbuettel** [comment]
Yes, thanks, that was proposed wording and it is not yet final.  The whole issue is murky and in need of cleanup.  Hence the ticket here.

**Comment by eddelbuettel** [comment]
Could do -- I know nothing about roxygen templating but I do now use [R macros](https://github.com/eddelbuettel/nanotime/blob/master/man/nanotime-package.Rd) to minimize duplication.

**Comment by coatless** [comment]
@lesshaste: to echo @eddelbuettel, above is just proposed verbiage. I've tightened it up. Apologies.

**Comment by coatless** [comment]
@eddelbuettel: Good with verbiage change? I'll PR it with roxygen change.

**Comment by eddelbuettel** [comment]
Sorry, but where is the supposed new text to look at?  Up there from 12 days ago?

**Comment by coatless** [comment]
Well, it's a few months ago now... But, let's cut our losses so this can be closed out.

This is the proposed documentation change:

Original:

> Depending on whether RcppArmadillo was compiled for the C++98 standard 
(currently the default) or for C++11 (optional), two different RNGs may be used. 
This function resets either. For C++98, the system library RNG is used. It may
have poor performance, particularly on older versions of Windows. For C++11, the
RNG included in its library is used.

New:

> Depending on whether RcppArmadillo was compiled for the C++98 standard 
(currently the default) or for C++11 (optional), two different RNGs may be used. 
This function resets either. For C++98, **the R programming language's RNG is used.**
~~It may have poor performance, particularly on older versions of Windows.~~
For C++11, the RNG included in **the \code{\<random>}** library is used **only when \code{#define ARMA_USE_CXX11_RNG} is placed before \code{#include <RcppArmadillo.h>}.**

[File](https://github.com/RcppCore/RcppArmadillo/blob/9e344e60d57c7b025a2193bafeb991ac5a161a5f/src/RcppArmadillo.cpp#L58)

**Comment by conradsnicta** [comment]
@coatless I don't think the proposed changes are right. Armadillo uses the C++11 RNG only when 2 conditions are true: (1) a C++11 compiler is detected, and (2) ARMA_USE_WRAPPER is defined.  As far as I can tell, the latter is never true under RcppArmadillo.

**Comment by eddelbuettel** [comment]
2) Does not apply as we never builld a libarmdaillo.{so,dylib,dll}.  When to set the value in 3) is what we may need to update.

**Comment by conradsnicta** [comment]
If there is no libarmadillo.so, then using ARMA_USE_WRAPPER will not work.  ARMA_USE_WRAPPER enables the use of libarmadillo.so.
More info: http://arma.sourceforge.net/faq.html#linking

**Comment by eddelbuettel** [comment]
@conradsnicta It is different.  We create a mechanism to fall back to R's RNG by default:

```c++
// using this define makes the R RNG have precedent over both the
// C++11-based RNG provided by Armadillo, as well as the C++98-based
// fallback.
//
// One can use the C++11-based on by commenting out the following
// #define and also selecting C++11 (eg via src/Makevars* or the
// DESCRIPTION file) and/or defining #define-ing ARMA_USE_CXX11_RNG
#define ARMA_RNG_ALT         RcppArmadillo/Alt_R_RNG.h
```

That has been in effect for year but we could/should document it better as well as the existing alternatives.

**Comment by conradsnicta** [comment]
This bit is not right:
`// DESCRIPTION file) and/or defining #define-ing ARMA_USE_CXX11_RNG`

There is no `ARMA_USE_CXX11_RNG` anywhere in the Armadillo codebase

**Comment by eddelbuettel** [comment]
You are unfamiliar with the R build process. This is an R package. They all have a DESCRIPTION file.  It is one of two places where C++11 can be turned on.

But you are correct about the `#define` being void and null.  That needs updating, I think it was effective when I wrote it 2 1/2 years ago.  I am sort-of off for a few days traveling, but I can look into this some more as I get time.

We need to rethink the 'with R and Rcpp, use RcppArmadillo in C++98 mode this way, and in C++11 mode (the suggested default) this way,  and in C++14 mode this way'.  R allows all three, we could just impose C++11 (easiest) but it cuts off all those poor souls with their RHEL versions from 1998. Or 2008. Or whatever -- with g++ 4.4 and other crap.  We currently draw the line at 4.6.

**Comment by coatless** [comment]
@conradsnicta Thanks for pointing that out. I'll correct the correction by emphasizing that RcppArmadillo uses the `# define ARMA_RNG_ALT` statement to hook into R's API regardless of C++ standard.

**Comment by coatless** [comment]
I've had a moment to sit down and look at what is happening. In particular, the following needs to occur:

1. Remove the above documentation and replace it with something along the lines of:

> RcppArmadillo takes advantage of the armadillo matrix library's ability to specify an alternative
> RNG scheme for the random number generators (RNGs). The alternative RNG used is written to
> take advantage of the R programming language's backend RNG. This is regardless of what 
> compilation standard was used, e.g. C++98/11/14. Thus, any routines using armadillo's random 
> sampling routine must be free of an OpenMP call.

2. Write in [`inst/include/RcppArmadillo/Alt_R_RNG.`](https://github.com/RcppCore/RcppArmadillo/blob/1d501ffed3fd9c8f390555a7a48f3ffb6d440135/inst/include/RcppArmadillo/Alt_R_RNG.h) a replacement for the [`arma::arma_rng::set_seed_random()`](https://github.com/RcppCore/RcppArmadillo/blob/1d501ffed3fd9c8f390555a7a48f3ffb6d440135/src/RcppArmadillo.cpp#L73)

3. Either deprecate both [`armadillo_set_seed_random()`](https://github.com/RcppCore/RcppArmadillo/blob/1d501ffed3fd9c8f390555a7a48f3ffb6d440135/src/RcppArmadillo.cpp#L72) and [`armadillo_set_seed()`](https://github.com/RcppCore/RcppArmadillo/blob/1d501ffed3fd9c8f390555a7a48f3ffb6d440135/src/RcppArmadillo.cpp#L93), which presently do _nothing_, or convert them over to using a call to _R_'s `set.seed` function from Rcpp ([SO respone](http://stackoverflow.com/questions/43221681/how-to-return-the-same-random-draws-as-long-as-the-parameter-value-does-not-chan/43222950#43222950))

**Comment by eddelbuettel** [comment]
1. is ok, the writing needs help, and the scope narrowed.  let's focus on a) we use R's RNG so that R's `set.seed()` works.
1.b) the OpenMP point is good and important, maybe we need treat this differently.

2. I have no idea what you are trying to say here.  Seeds get set from R, and one normally does via Rcpp.

3. Not sure. Better documentation helps. I'd rather not monkey-patch around Conrad's code.  If you see the default, then these functions are null-ops.  So what.  Need to document it.  Now, _if_ you turn the Alt.RNG scheme off, they works as usual.   Sounds fine to me.

We had RcppArmadillo on CRAN for maybe 7 years.  Almost 350 packages use it.  Nobody has ever asked for its RNG (or the C++ RNG).

**Comment by coatless** [comment]
1. How about:

> RcppArmadillo takes advantage of the R programming language's random number
> generators (RNGs). This allows for users to specify a seed with R's \code{set.seed()}
> function to achieve reproducible results. Presently, there is no option to specify the
> use of the C++ \code{random} library.

> With armadillo 7.900.0, the armadillo library has begun to support parallelization
> through OpenMP. However, due to the use of R's RNG routines within armadillo,
> it is not possible to use parallelization with armdillo's RNG functions. Principally, 
> R's RNG routines are not thread safe and must operate on a single-thread paradigm.
> Thus, any attempt to use OpenMP or embed RNG within an OpenMP scheme will
> result in a crash. For more details, please see:
> \url{https://cran.r-project.org/doc/manuals/r-patched/R-exts.html#OpenMP-support}

2. The point being made here was a behavior inconsistency with the alt RNG definition. In particular,  `set_seed_random()` is not specified whereas `set_seed(val)`  is (and provides a warning about where to set the RNG state). So, to ensure parity, there should be a definition for `set_seed_random()` that mimics `set_seed(val)`.

3.  When I said _nothing_, I meant to say that they do not modify the seed w.r.t R's RNG scheme. However, if the alt rng is turned off, then -- of course -- it works as it hooks into the *random* library.

**Comment by conradsnicta** [comment]
> With armadillo 7.900.0, the armadillo library has begun to support parallelization
> through OpenMP. However, due to the use of R's RNG routines within armadillo,
> it is not possible to use parallelization with armdillo's RNG functions.

I'm not sure this is applicable.  It's actually misleading.

Armadillo doesn't use OpenMP for anything related to random numbers. Instead, Armadillo uses OpenMP for element-wise functions such as exp(), log, exp().

**Comment by coatless** [comment]
@conradsnicta I realize it may seem misleading now; however, when conradsnicta/armadillo-code#22 goes through -- which allows `.for_each()`, `.transform()`, and `.imbue()` to be parallelized -- this can of worms will be opened.

**Comment by conradsnicta** [comment]
That's more of a bug in R though?

Even if there is a potential for threading conflicts with random numbers in the future, it's not like things will blow up. The numbers will still be random, but not in a guaranteed order.

R should really provide a thread safe RNG, though I'm not sure it's safe to assume that the R folks know that it's 2017 and computers have multiple cores these days?  Last I checked they had issues with using highly advanced concepts such as 64 bit integers.

**Comment by eddelbuettel** [comment]
Still, it would require each of these "transformations" to be done in a way that relies on RNG draws.

Let's not get carried away.  We have RNGs.  For consistency with R, we fall back to its generator (just uniforms;   for Normals, it is still Conrad's Box/Muller based on these uniforms so not identical to what R gives but still reproducible).

"All we have to do here" is remind people that 'parallel' and 'R RNG' do not go together.  So as with other OpenMP examples, we just gave to show an example of doing it without R data structures.

There are possibly lots of other worms too:  our proxy object mapping to Armadillo objects when that even in OpenMP blocks with "just Arma types" we could get an garbage collection event.  Uggh.

**Comment by eddelbuettel** [comment]
> That's more of a bug in R though?

It is a well-known design limitation at the center of R that is around 40 years old when all things where single-threaded.  Think GIL for Python.  

On the other hand people have been using parallel RNGs for 15+ years with R.   You need to know how.  No more, no less.  It is still a system extensible with packages.

**Comment by coatless** [comment]
How about this?

> With armadillo 7.900.0, the armadillo library has begun to provide support
> for parallelization through OpenMP. Over time, the parallelization options
> provided within armadillo will increase. However, due to the configuration
> used by RcppArmadillo to associate R's RNG routines with armadillo's, it
> is not possible to use a parallelization approach with armdillo's RNG functions.

**Comment by conradsnicta** [comment]
@coatless @eddelbuettel - I don't like the way it associates broken R functionality with Armadillo. Many people simply don't look at the underlying issues, so there is a potential of having people incorrectly think that Armadillo always has misbehaving rng functions. It's also wrong to say "not possible to use a parallelization approach". It's certainly possible; it will just lead to non-deterministic / non-reproducable random numbers.

How about the following wording, which is succinctly clear and provides an explicit caveat:

> Armadillo version 7.900 provides support for automatic parallelization (through OpenMP)
> of computationally expensive element-wise functions such as exp(), log(), cos(), etc.
> Later versions of Armadillo may expand parallelization to more functions, such as .for_each().
> Caveat: RcppArmadillo configures Armadillo to use RNG routines from the host R environment.
> The R environment currently doesn't have thread-safe RNG routines.
> This may lead to non-reproducable random numbers if the RNG routines are used within .for_each().

**Comment by coatless** [comment]
@conradsnicta: Beautiful.

**Comment by eddelbuettel** [comment]
We are getting nowhere with this issue and I am closing it.
