### ISSUE TITLE
SUPERLU support

### ISSUE THREAD

**Issue by ivan-krukov** [RcppCore/RcppArmadillo#120]
How would one go about enabling SUPERLU support with RcppArmadillo?

Specifically, I would like to be able to use `spsolve` with SUPERLU under the hood.

Should this amount to enabling `ARMA_USE_SUPERLU` in [`inst/include/armadillo_bits/config.hpp`](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/armadillo_bits/config.hpp#L41) and installing package from source?

Or is this a [deeper issue](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/README#L5)? 

Thank you.

**Comment by eddelbuettel** [comment]
Good question. I am not sure.   

Context, as you may know:  RcppArmadillo takes a plain copy, no cmake, no options. Works great with basic BLAS and LAPACK which we get from R.

Extensions are harder.  We are learning that now with MLPACK (over [here](https://github.com/rcppmlpack/rcppmlpack2))  which uses linking against external Boost (as it needs serialization) and Armadillo (as that is how it is build).

You could try something narrower and half way.  Ie define the required tokens in your source file (or `src/Makevars`), then load RcppArmadillo to have them take effect.  Then you "only" need to make sure you supply SUPERLU itself. 

There are a few people interested in better sparse support, maybe time to discuss on rcpp-devel, or here.

**Comment by eddelbuettel** [comment]
Just checked, and Conrad's documentation leans the same way:

> `ARMA_USE_SUPERLU`	 	Enable use of SuperLU, which is used by `spsolve()` for finding the solutions of sparse systems; you will need to link with the superlu library, for example `-lsuperlu` 
Caveat: Armadillo 6.x requires SuperLU 4.3, while Armadillo 7.x requires SuperLU 5.2

**Comment by thirdwing** [comment]
@ivan-krukov After enabling `ARMA_USE_SUPERLU`, you also need to pass the `-lsuperlu`  option to R.

```cpp
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp ;
using namespace arma;

// [[Rcpp::export]]
void test () {
  sp_mat A = sprandu<sp_mat>(1000, 1000, 0.1);

  vec b = randu<vec>(1000);
  mat B = randu<mat>(1000, 5);

  vec x = spsolve(A, b);  // solve one system
  mat X = spsolve(A, B);  // solve several systems

  bool status = spsolve(x, A, b);  // use default solver
  if(status == false)  { cout << "no solution" << endl; }

  spsolve(x, A, b, "lapack");   // use LAPACK  solver
  spsolve(x, A, b, "superlu");  // use SuperLU solver

}
```

In R:

```
> Sys.setenv("PKG_LIBS"="-lsuperlu")
> Rcpp::sourceCpp("test.cpp")
```

If you didn't pass `-lsuperlu`, you might get some errors like `undefined symbol: set_default_options`.

**Comment by eddelbuettel** [comment]
Perfect, was just thinking I should write an Rcpp Gallery post along those line.  

The default libsuperlu-dev on Ubuntu is currenty behind, the one in Debian is good enough so easy enough to test in a Docker container, or a locally rebuilt packager for superlu.

**Comment by ivan-krukov** [comment]
@thirdwing Did you have to recompile any of `RcppArmadillo` components? Or is this all in the headers?

**Comment by eddelbuettel** [comment]
It should all be headers ... until the call to superlu is made at which point object code is needed. 

Not any different from when LAPACK is called, which get for free from R which is why it seems so seamless.

**Comment by ivan-krukov** [comment]
Just checked everything works, no need to recompile `RcppArmadillo`.

This is excellent. Thank you!

**Comment by eddelbuettel** [comment]
I wrote this up as a [new piece on the Rcpp Gallery](http://gallery.rcpp.org/articles/armadillo-with-superlu/).
