### ISSUE TITLE
Single-row matrix passed on from R is "not compatible with requested type" arma::mat

### ISSUE THREAD

**Issue by twolodzko** [RcppCore/RcppArmadillo#123]
This might be either bug or a feature, but RcppArmadillo seems to incorrectly handle single row matrix objects. Consider the following function:

```
arma::mat foo(const arma::mat& x) {
  return x;
}
```

pass single-row matrix through it:

```
foo(matrix(1:5, nrow = 1))
## Error in foo(matrix(mtcars[1, ], nrow = 1)) :
##  not compatible with requested type
```

Imagine some function that passes matrix to `foo()`, since this behavior, additional exception handling
is needed so that different functions are called for single-row matrix as input vs multi-row
matrix. On another hand, one should rather not expect of users to treat differently single-row vs multi-row matrices and matrix should be passed as matrix (especially a matrix that was explicitly passed as matrix, I'm not talking about converting vectors to matrices).

As far as I know Armadillo alone does not have any problems with handling single-row matrices.

**Comment by nathan-russell** [comment]
The problem is that you passed a `list` to your function: 

```c++
// [[Rcpp::export]]
int sexp_type(SEXP x)
{ return TYPEOF(x); }

/*** R

sexp_type(matrix(1:5, nrow = 1))
# [1] 13  # integer

sexp_type(matrix(mtcars[1, ], nrow = 1))
# [1] 19  # list

*/
```

------

```c++
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>

// [[Rcpp::export]]
arma::mat foo(const arma::mat& x)
{ return x; }

/*** R

str(matrix(1:5, nrow = 1))
# int [1, 1:5] 1 2 3 4 5

str(matrix(mtcars[1, ], nrow = 1))
# List of 11
#  $ : num 21
#  $ : num 6
#  $ : num 160
#  $ : num 110
#  $ : num 3.9
#  $ : num 2.62
#  $ : num 16.5
#  $ : num 0
#  $ : num 1
#  $ : num 4
#  $ : num 4
#  - attr(*, "dim")= int [1:2] 1 11

foo(matrix(1:5, nrow = 1))
#      [,1] [,2] [,3] [,4] [,5]
# [1,]    1    2    3    4    5

foo(matrix(mtcars[1, ], nrow = 1))
# Error in foo(matrix(mtcars[1, ], nrow = 1)) :
#   not compatible with requested type

*/
```
