### ISSUE TITLE
GCC 7 support

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppArmadillo#126]
Allow for GCC 7 in [`configure.ac`](https://github.com/RcppCore/RcppArmadillo/blob/268adf3644c139d77f7fce7b3e2a52b2f8000b5f/configure.ac#L42) by adding `7.*` in gcc check. e.g.

	4.6.*|4.7.*|4.8.*|4.9.*|5.*|6.*|7.*)

**Comment by eddelbuettel** [comment]
Now merged.
