### ISSUE TITLE
OpenMP Support for Standalone Scripts in 7.900.0

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppArmadillo#127]
Add ` $(SHLIB_OPENMP_CFLAGS)` to [`inlineCxxPlugin <- Rcpp:::Rcpp.plugin.maker` in `inline.R`](https://github.com/RcppCore/RcppArmadillo/blob/268adf3644c139d77f7fce7b3e2a52b2f8000b5f/R/inline.R#L18-L22) to support OpenMP support added in Armadillo 7.900.0

```r
inlineCxxPlugin <- Rcpp:::Rcpp.plugin.maker(
	include.before = "#include <RcppArmadillo.h>", 
	libs           = "$(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CFLAGS)", 
	package        = "RcppArmadillo"
)
```

Per [comment](https://github.com/RcppCore/RcppArmadillo/commit/b567a47a48ac22cc51f870b2d5d9ee3c385f9de0#commitcomment-22031448), I don't think `$(SHLIB_OPENMP_CXXFLAGS)` is applicable for `Rcpp.plugin.maker` as it doesn't have a slot for them.

**Comment by eddelbuettel** [comment]
But ... as I recall this gist of getting OpenMP was to *both* compile and link with `-fopenmp` so we would need to get it into `CXXFLAGS`, or `PKG_CXXFLAGS`, or ...   And make sure we cover the various C++ dialect options we now have.

**Comment by eddelbuettel** [comment]
Ie here is what Rcpp does in its plugin for openmp:

```
## built-in OpenMP++11 plugin
.plugins[["openmp"]] <- function() {
    list(env = list(PKG_CXXFLAGS="-fopenmp",
                    PKG_LIBS="-fopenmp"))
}
```

(I suppose OpenMP++11 is a cut-and-pasto.  Should be OpenMP.)

**Comment by coatless** [comment]
@eddelbuettel You are correct. The functionality of `Rcpp.plugin.maker` needs to be extended...

**Comment by coatless** [comment]
Or, what can happen is an injection into the `Makevars` slot in a similar way as the `libs` line is defined. See [`R/inline.R#L44-L54`](https://github.com/RcppCore/Rcpp/blob/6f81b4684481dbd9bb554dd95e66725fc3b63a8c/R/inline.R#L44-L54)

```r
Rcpp:::Rcpp.plugin.maker(
	include.before = "#include <RcppArmadillo.h>", 
	libs           = "$(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CFLAGS)", 
        Makevars       = list( PKG_CXXFLAGS = "$(SHLIB_OPENMP_CXXFLAGS)" ) ,
        Makevars.win   = list( PKG_CXXFLAGS = "$(SHLIB_OPENMP_CXXFLAGS)" ),
	package        = "RcppArmadillo")
```

**Comment by eddelbuettel** [comment]
Or ... we just punt and tell folks to rely on the _existing_ plugin for OpenMP which reliably turns on OpenMP?

Ie recommend to turn on RcppArmadillo (via `Rcpp::depends()`) and OpenMP (via `Rcpp::plugins()`) ?

**Comment by coatless** [comment]
I think it would be better to be contained within armadillo. I noodled around with the `Makevars` approach I outlined above. It didn't work out well since I do not believe `Makevars` is even used by [`R/Attributes.R`](https://github.com/RcppCore/Rcpp/blob/092d947e35e3d19e6a20910b35f4f245bff3a1a6/R/Attributes.R) after browsing the file.

So, I would propose an approach similar to [`RQuantlib`](https://github.com/cran/RQuantLib/blob/ddd59d605aeeafcfbfaba67d53b62abc3e8565c7/R/inline.R#L65-L74) for setting the flag.

```r
inlineCxxPlugin <- function(...) {
  plugin <- Rcpp:::Rcpp.plugin.maker(include.before = "#include <RcppArmadillo.h>", 
                                     libs           = "$(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CFLAGS)", 
                                     package        = "RcppArmadillo")
  settings <- plugin()
  settings$env$PKG_CPPFLAGS <- paste0("$(SHLIB_OPENMP_CXXFLAGS)")
  settings
}
```

**Comment by eddelbuettel** [comment]
RcppGSL does something similar.  The crux, as you say, is that this once aimed the inline package, and Rcpp sort of just picked it up.

We have to figure put the different use case and try to make sure we hit most of them home...

**Comment by coatless** [comment]
Per 70a27b7405fa3ea546816c5cf2a6e9127669b040 and 150899fbdb2d4ed4668065d3873f2ff9dcb852de this can be closed out.

However, note that `Makevars` uses `PKG_CXXFLAGS` while `Makevars.win` uses `PKG_CPPFLAGS`. 
Though, setting the flags through either appears to matriculate the correct flags for the compile.

**Comment by eddelbuettel** [comment]
Yes, testing this on Metra this am.  Seems to work.  Users may still have to supply the C++11 or C++14 (Rcpp) plugin in addition to the the depends getting them this from the pluginMaker.

Thanks for the reminder on the Makevars. I'll clean this up.  Writing R Extension is a little rambling there but I PKG_CXXFLAGS may be better.

One thought I had was to ... maybe adding comments that all this is optional may help?   Then again adding -fopenmp without actual OpenMP directive is just a null-op so no harm done.

**Comment by eddelbuettel** [comment]
I think this one can be closed now.
