### ISSUE TITLE
Armadillo 7.900.0 and C++11 transition

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#131]
Opening an issue to tick off a few things we (hi, @coatless) could look into:

- [ ] support C++11 and OpenMP in package build 
    - easy for RcppArmadillo itself and essentially done 
   -  but less relevant as eg `fastLm()` does not "need" it)
- [ ] adjust `RcppArmadillo.package.skeleton()` to set these two options as well
    - maybe with a fallback option?
- [ ] maybe beef up `configure` to test compilers and simply fall back C++98 for g++ older than 4.9 ?

All this is predicated on Armadillo actually still falling back sanely to a non-C++11 world, and Conrad is increasingly unlikely to support this 'forever' (and has given ample warning)

That would mean more proactively setting some of the config variables.  More work, but we would not exclude the poor souls

**Comment by coatless** [comment]
1. This was primarily done in [`src/Makevars`](https://github.com/RcppCore/RcppArmadillo/blob/b567a47a48ac22cc51f870b2d5d9ee3c385f9de0/src/Makevars) with the 7.899.0 branch. However, the [`Rcpp.plugin.maker()`](https://github.com/RcppCore/RcppArmadillo/blob/b567a47a48ac22cc51f870b2d5d9ee3c385f9de0/R/inline.R#L18-L22) option needs to be updated per #127. 
2. Probably should have `CXX_STD = "CXX11"` option in `Rcpp.package.skeleton()`?
3. Use autoconf [`AX_CXX_COMPILE_STDCXX_11`](https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx_11.html) macro, then set `CXX_STD` to either `CXX98` or `CXX11`.

**Comment by eddelbuettel** [comment]
Instead of 3, which R already does, just ask R?

**Comment by eddelbuettel** [comment]
Let's discuss later. I think I have most of these licked by outsourcing to what R already has -- see Writing R Extensions on OpenMP.

I also want users to opt-into C++11 and not enforce it.  

And I just commented in #127 too.

**Comment by eddelbuettel** [comment]
I think we have this under control now:  C++11 is an option for package users of RcppArmadillo.
