### ISSUE TITLE
clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by binxiangni** [RcppCore/RcppArmadillo#143]
When I test codes in MacOS, the error message above showed up. I tried some methods on stackoverflow but they didn't work. Any idea?

**Comment by coatless** [comment]
Read: http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/

**Comment by binxiangni** [comment]
The initial error disappeared, but a new one comes out:
```
checking whether we are cross compiling... configure: error: in `/private/var/folders/xn/46r52scd6_v17k8qb28tpflh0000gn/T/RtmpPQupxB/Rbuild282a768a148a/RcppArmadillo':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

**Comment by coatless** [comment]
1. [ ] Installed Xcode CLI
2. [ ] Installed clang4 (once) with the installer?
3. [ ] Installed gfortran 6.1
4. [ ] Restarted R?

**Comment by binxiangni** [comment]
Now I reinstall Xcode, then the error is away. Thanks! 👍

**Comment by gurol** [comment]
Use [https://github.com/coatless/r-macos-rtools](https://github.com/coatless/r-macos-rtools)

**Comment by eddelbuettel** [comment]
@gurol ?  We have made half a dozen releases since that report, rewrote the architecture detection and have just seen R Core give us new macOS tools.  The comment may be a little out of sync, as well-intended as it may be.

**Comment by dpastoor** [comment]
@eddelbuettel not completely out of of sync - from @vjd after fresh R OSX install + new macOS tools getting this exact error

![image](https://user-images.githubusercontent.com/3196313/39632008-e0d085f4-4f81-11e8-9adc-70c41b67eae9.png)

**Comment by vjd** [comment]
@dpastoor thanks. 
@eddelbuettel My MakeVars looks like this.

```
CC=/usr/local/clang6/bin/clang
CXX=/usr/local/clang6/bin/clang++
LDFLAGS=-L/usr/local/clang6/lib
```

**Comment by eddelbuettel** [comment]
@coatless Can you chime in? Which `clang` version should people use? What documentation should we point to? I was under the impression this was now ironed out?

**Comment by kylebmetrum** [comment]
No issues here:

```r
F77 = /usr/local/bin/gfortran
FC = $F77
CXX = ccache /usr/local/clang6/bin/clang++  -Wall
LDFLAGS=-L/usr/local/clang6/lib
CC= ccache /usr/local/clang6/bin/clang
SHLIB_CXXLD=ccache /usr/local/clang6/bin/clang++
CXX11 = ccache /usr/local/clang6/bin/clang++
CXX98 = ccache /usr/local/clang6/bin/clang++
CXX14 = ccache /usr/local/clang6/bin/clang++
```

**Comment by coatless** [comment]
@eddelbuettel in short, I gotta spend time updating documentation for the R 3.5.* line as it uses `clang6` instead of `clang4`...

**Comment by vjd** [comment]
@kylebmetrum My makevars reflects what you have mostly, so I don't see an issue. I updated to reflect your config. Now, I get the following error below. Is this a permissions thing?

```
configure: error: in `/private/var/folders/c1/ydghd7v17g16f0_nw47gvqmm0000gn/T/RtmpVeAriM/R.INSTALLab22eb1a962/RcppArmadillo':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘RcppArmadillo’
* removing ‘/Users/vijay/Dropbox (Personal)/rlibs/RcppArmadillo’
Warning in install.packages :
  installation of package ‘RcppArmadillo’ had non-zero exit status
```

**Comment by coatless** [comment]
@vjd post the `config.log` and your `~/.R/Makevars`

**Comment by coatless** [comment]
The issue we are running into here is the binary from _R_ is configured for usage on CRAN. Local machines still need a _lot_ of options set.

**Comment by vjd** [comment]
@coatless I used the same `~/.R/Makevars` as @kylebmetrum 

where can I find the `config.log`?

**Comment by coatless** [comment]
Should be in `/private/var/folders/c1/ydghd7v17g16f0_nw47gvqmm0000gn/T/RtmpVeAriM/R.INSTALLab22eb1a962/RcppArmadillo`

**Comment by vjd** [comment]
That's where I tired initially.. but is this temp folder blown away after failed install?

![image](https://user-images.githubusercontent.com/1425562/39634641-56461ec8-4f89-11e8-9064-494b491e80c7.png)

**Comment by eddelbuettel** [comment]
Maybe do it the other way around: create a temp directory,  change into it, copy the RcppArmadillo tarball, unpack it and run `./configure`.  The log file will be there.   R does the same for you but cleans up temp dirs which you do not want now.

**Comment by kylebmetrum** [comment]
@vjd `ccache` is a program to speed up installation by caching; highly recommended

See: http://dirk.eddelbuettel.com/blog/2017/11/27/

And: https://ccache.samba.org/

**Comment by eddelbuettel** [comment]
Highly recommended especially when you compile the same (C/C++/...) sources multiple times -- eg when building / testing an R packages.

Also, as you just relearned the hard way, do not just copy a setup blindly.  You clearly could copy `ccache` when you did not have it installed.  Sorry for the bother, it leaks out of my examples too -- but there is a wee amount of 'buyer beware' here.
