### ISSUE TITLE
Cube Exporter bug with DARMA_64BIT_WORD

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppArmadillo#146]
With DARMA_64BIT_WORD to work with large cubes (2^30 elements), there appears to be a cast issue in [`include/RcppArmadilloAs.h`](https://github.com/RcppCore/RcppArmadillo/blob/7a50d12dc5835725235ca6b287e549f86f788c01/inst/include/RcppArmadilloAs.h#L622-L624)

```
invalid cast from type 'Rcpp::Vector<19>::iterator
 {aka Rcpp::internal::Proxy_Iterator<Rcpp::internal::generic_proxy<19> >}'
 to type 'log long int*'
```

Reprex inc.

**Comment by coatless** [comment]
Didn't push the right configuration file... Failed because C++11 wasn't detect... It's going to be one of those mornings. Sorry.

**Comment by eddelbuettel** [comment]
Ahh. Usual fix of C++11 to get hold of `long long` as a way around CRAN insisting C++ == C++98.
