### ISSUE TITLE
Documentation for Sparse Matrix in RcppArmadillo

### ISSUE THREAD

**Issue by binxiangni** [RcppCore/RcppArmadillo#148]
I'm sorting out a [documentation](https://github.com/binxiangni/Sparse_Matrix_in_RcppArmadillo/blob/master/Sparse_Matrix_in_RcppArmadillo.Rmd) for sparse matrix in RcppArmadillo. Now it's preliminary. Some more details and examples will be added and completed soon. Suggestions and corrections would also be welcomed. @eddelbuettel @thirdwing @coatless

**Comment by thirdwing** [comment]
I have gone through the document quickly. Great work and I believe this will help many R users in the community.

Just some very minor suggestions I want to make:

(1) Currently, all vignettes in RcppArmadillo are using Rnw format(https://github.com/RcppCore/RcppArmadillo/tree/master/vignettes). Maybe it is better to keep consistent. We might switch to Rmd later.

(2) It seems you don't mention the return type from RcppArmadillo. Personally, I think we still need to mention this.

(3) Personally, I think we can make the introduction part a little shorter. Because the conversion is the part we want users pay attention to.

**Comment by binxiangni** [comment]
While completing the documentation I wrote before, I think I might go in the wrong way. My initial intention to write this documentation is to let users know how to use sparse matrix in RcppArmadillo, including:  

1. how to create a sparse matrix in R(in package "Matrix");  
2. how to use member functions in Armadillo.  

But the 1st one seems kind of far off the topic "sparse matrix conversion in RcppArmadillo" as KK mentioned before. And the `member functions` part is almost similar to `Armadillo`, but I might not write as well as the original one.   

So I was trapped into the topic of documentation. What should I include in the documentation? Description in the conversion algorithms? Sound like a silly question, but really confuse me. 😞   

By the way, when writing examples of RcppArmadillo, I found error occurred that "p of dgCMatrix should be non-decreasing" when using `speye()` to create a unit diagonal sparse matrix in `Armadillo`. I test the as<>() and it seems fine. I guess that the problem might be caused by the fact that the col_ptrs in `Armadillo` is not sorted when creating a unit diagonal sparse matrix. Any thoughts? If so, I might need to rewrite wrap(). Or I might just remind users not to use this function in RcppArmadillo, since if I add `sort` in wrap(), it will increase the running time when converting to dgCMatrix while no problems occurred in other examples.

**Comment by eddelbuettel** [comment]
There are probably several possible usage patterns, and coming from package Matrix may well be one.

Another may be to look at examples elsewhere: spam, SparseM, ... may have examples that are useful.

Shall we open an separate issue for the conversion question?  With a reproducible example?

**Comment by binxiangni** [comment]
I've shorten the [documentation](https://github.com/binxiangni/Sparse_Matrix_in_RcppArmadillo/blob/master/Sparse_Matrix_in_RcppArmadillo_shorten.Rmd). Could you please check whether it's all right? Then I'll learn how to write it in Rnw.

**Comment by eddelbuettel** [comment]
Not sure we must rewrite as Rnw now that it exists.  Up for discussion, I suppose. We could keep it.  But if you want, Rnw would make it consistent with what we have now.  Keeping it as Rmd may be easier.  (There may also be a way from the Rmd we have now into Rnw/pdf. Not set up yet.)

As for content, it reads fine to me. Maybe @dmbates who was very recently around in another thread could give it a quick read?    (In the first line, you want `user's` instead, and the third paragraph isn't quite polished but we can clean that later.)

**Comment by binxiangni** [comment]
Just travel back to China and it seems that the progress is kind of left behind. Now I've added a [Rnw](https://github.com/binxiangni/Sparse_Matrix_in_RcppArmadillo/blob/master/RcppArmadillo-sparseMatrix.Rnw) documentation. A [pdf](https://github.com/binxiangni/Sparse_Matrix_in_RcppArmadillo/blob/master/RcppArmadillo-sparseMatrix.pdf) version is also generated for your convenience to take a look. I am a newbie to Rnw, and if there is something inappropriate, please correct me. If everything is fine, I'll close this issue, put the Rnw file into `vignettes` folder and open a pull request.

**Comment by eddelbuettel** [comment]
Oh, nice. PR away.   (We use highlight more for code than lstlisting which I also used in the past, but those are minor details we can clean up later or leave as is.)
