### ISSUE TITLE
Build failure on NixOS because there is no /bin/bash

### ISSUE THREAD

**Issue by peti** [RcppCore/RcppArmadillo#15]
The `configure` script assumes that the path `/bin/bash` exists, but that is not true on many system, including the NixOS Linux distribution. As a result, we get the following build error: http://hydra.cryp.to/build/66463/nixlog/1/raw

Could you please change that shebang path to use `/usr/bin/env bash` instead? Or maybe even `/bin/sh`, if your script works with any POSIX-compliant Bourne shell?

**Comment by ORESoftware** [comment]
on nixos anyone know how to add bash so that env can find it?

I have this error:

```bash
env: can't execute 'bash': No such file or directory
```

which results from using a hashbang like:

```bash
#!/usr/bin/env bash

```

**Comment by eddelbuettel** [comment]
You are commenting on a five year old bug report for an issue we no longer have -- these days `configure` is `autoconf` generated rather than a shell script with the a shebang line calling `bash` via `env`.

**Comment by ORESoftware** [comment]
@eddelbuettel  I am taking about the more general context - a shell script with that hasbang does not seem to work on nixos at all

**Comment by eddelbuettel** [comment]
Would you consider having that debate elsewhere?  It is now 2019, not 2014 when this ticket was openend, and we have no use of `/usr/bin/env` here.  And have not for years.  Cool?
