### ISSUE TITLE
Next release 0.7.960.0.0 ready ?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#157]
Unusual step of probing via issue ticket as we have so much concurrent activity which is super exciting.

Status:
- [x] all old issue tickets closed 
- [x] one new ticket on SciPy sparse matrix conversion by [reticulate](https://github.com/rstudio/reticulate) which may not be release critical
- [x] most recent release (7.960.0) by @conradsnicta plus one upstream fix for non-square `speye()`
- [x] ChangeLog and NEWS are now current for all the fine Google Summer of Code work by @binxiangni 
- [x] Ran two complete reverse-depends check last Wed and Fri, no new issues
- [x] Windows test issue ... which turns out to have been a missing test for SciPy in the unit tests
- [x] Anything I am forgetting for a shiny new 0.7.960.0.0 release?

Poking @thirdwing @binxiangni @sgsokol for comments/suggestions/omissions/...

**Comment by binxiangni** [comment]
Everything looks fine. I'll follow up the conversion of SciPy sparse matrix ASAP. Working on sorting out a final report of GSOC. BTW, there is a minor [typo](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/NEWS.Rd#L30), which should be 2017. You can just leave it as is, or just fix it when you modify NEWS.Rd next time.

**Comment by eddelbuettel** [comment]
Thanks for catching the typo.  Will fix in sources so that the released version will have it.

If you think you may have something for the SciPy import within the next few days, we can wait.  Else we can also just have it committed in master and ready for the next release...

**Comment by binxiangni** [comment]
Well, I'll try to finish that tomorrow.

**Comment by thirdwing** [comment]
I am fine with a new release.

**Comment by sgsokol** [comment]
When I run unit tests, few of them fail (sparse matrices are poking some errors). But I suppose you are aware of all these cases and here, it is not a problem to have failed tests in a public release, right?
A part from that, the rest looks fine.

**Comment by eddelbuettel** [comment]
Hm, can you detail the errors, please? I ran
- locally with r-release
- locally with r-devel
- on win-builder for [r-release](https://win-builder.r-project.org/E9FJc6bBy3Yd) and [r-devel](https://win-builder.r-project.org/h8PRM1657E8X)
- on r-hub using its `check_on_cran()`

and only that last one had an 'error' under the ASAN/UBSAN build which upon closer inspection looks spurious.  

Are you sure that you didn't just fall for quirky output (where "expected" errors are in fact caught) ?

**Comment by sgsokol** [comment]
For example, is such mesage an expected error?
```
Executing test function test.as.dgt2dgc  ... Timing stopped at: 0.05 0 0.047
Error in checkEquals(dgc, asSpMat(dgt), msg = "dgT2dgC_15") : 
  Attributes: < Component “i”: Numeric: lengths (3, 4) differ >
Attributes: < Component “p”: Mean relative difference: 0.3333333 >
Attributes: < Component “x”: Numeric: lengths (3, 4) differ >
dgT2dgC_15
 done successfully.
```
My R.version is:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.1                         
year           2017                        
month          06                          
day            30                          
svn rev        72865                       
language       R                           
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle

**Comment by eddelbuettel** [comment]
For that one I get

```bash
Executing test function test.as.dgt2dgc  ... Note: method with signature ‘sparseMatrix#ANY’ chosen for fu
nction ‘kronecker’,
 target signature ‘dtTMatrix#dgeMatrix’.
 "ANY#Matrix" would also be valid
Note: method with signature ‘dsparseMatrix#dsparseMatrix’ chosen for function ‘kronecker’,
 target signature ‘dgRMatrix#dgTMatrix’.
 "sparseMatrix#TsparseMatrix" would also be valid
 done successfully.
```

I use the script below to run individual Unit test files.  That can help.

```r
#!/bin/sh

set -u 
set -e

progname=`basename $0`
options='p:ah?'
 
usage_and_exit()
{
    echo ""
    echo "Usage: $progname [-p package[,package2,..]] [-?|-h]"
    echo "  Run unit test script for R package"
    echo ""
    echo "Options:"
    echo "  -p package[,package2,..]]  load additional package(s)"
    echo "  -h                         show this help"
    echo "  -a                         run with 'export RunAllRcppTests=yes'"
    echo ""
    echo "The RUnit and inline packages are automatically loaded."
    echo ""
    exit 0
}

while getopts "$options" i 
do 
    case "$i" in
	p)
	    pkg=",$OPTARG"
	    shift 
	    shift
	    ;;
	a)
	    export RunAllRcppTests="yes"
	    shift
	    ;;
	h|?)
	    usage_and_exit
	    ;;
    esac
done

if [ ! -f $1 ]; then
    echo "Error: No file '$1' found"
    exit 1
fi

file=`pwd`/$1

#r -i -t -linline,RUnit${pkg} -e"cppfunction <- function(...) cxxfunction(..., plugin=\"Rcpp\"); runTestFile(\"$file\")"
r -i -t -lRUnit${pkg} -e"runTestFile(\"$file\")"
```

I can then do `runit.sh -p RcppArmadillo inst/unitTests/runit.sparseConversion.R`.  You may need to adapt to `Rscript` if you don't have littler and its `/usr/bin/r`.

**Comment by binxiangni** [comment]
The failed unit test is:
```
x <- matrix(c(1, 0, 0, 2, 1, NA), nrow = 3)
dgt <- as(x, "dgTMatrix")
dgc <- as(x, "dgCMatrix")
checkEquals(dgc, asSpMat(dgt), msg="dgT2dgC_15")
```
I guess the problem might be `NA`.  But in MacOs and R 3.4.1, it passes the test.

**Comment by eddelbuettel** [comment]
I just looked at that on the train and it also worked for me there (Linux, R 3.4.1, everything current).

I am a little annoyed by the "noise" coming from `kronecker()` earlier in that same block, and will try to see if I can help improve that.

**Comment by eddelbuettel** [comment]
@sgsokol Can you print the two matrices?  

```r
R> library(RUnit)
R> library(Matrix)
R> library(RcppArmadillo)
R> library(Rcpp)
R> sourceCpp("~/git/rcpparmadillo/inst/unitTests/cpp/sparse.cpp")  ## needed
R> x <- matrix(c(1, 0, 0, 2, 1, NA), nrow = 3)
R> dgt <- as(x, "dgTMatrix")
R> dgc <- as(x, "dgCMatrix")
R> checkEquals(dgc, asSpMat(dgt), msg="dgT2dgC_15")
[1] TRUE
R> 
```

**Comment by sgsokol** [comment]
Looks strange what I had:
``` dgt <- as(x, "dgTMatrix")
> dgt
3 x 2 sparse Matrix of class "dgTMatrix"
         
[1,] 1  2
[2,] .  1
[3,] . NA
> dgc <- as(x, "dgCMatrix")
> dgc
3 x 2 sparse Matrix of class "dgCMatrix"
        
[1,] 1 2
[2,] . 1
[3,] . .
> checkEquals(dgc, asSpMat(dgt), msg="dgT2dgC_15")
Error in asSpMat(dgt) : No such slot: p.
> str(dgt)
Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:4] 0 0 1 2
  ..@ j       : int [1:4] 0 1 1 1
  ..@ Dim     : int [1:2] 3 2
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ x       : num [1:4] 1 2 1 NA
  ..@ factors : list()
```
Indeed, there is no such slot "p".

**Comment by eddelbuettel** [comment]
Well so far that does not affect Binxiang, myself, Travis CI, ... but only you.   Any chance your build env might be contaminated with another version or something?

**Comment by sgsokol** [comment]
Could be. I'll check.

**Comment by sgsokol** [comment]
Yep, there was a contamination but it was not its fault in the error message. The fault was in "-ffast-math" option that I used for R (and hence Matrix) compilation. It optimized out NA during dgc conversion. Now, without this option, dgc prints as it should:
```
> dgc
3 x 2 sparse Matrix of class "dgCMatrix"
         
[1,] 1  2
[2,] .  1
[3,] . NA
```
and logically I have now
```
> checkEquals(dgc, asSpMat(dgt), msg="dgT2dgC_15")
[1] TRUE
```

**Comment by eddelbuettel** [comment]
Just finished another reverse depends run.  Still no issues besides two known failures (both internal, seemingly, to their packages). 

So I think I will roll this up for release to CRAN for tomorrow or Thursday.

**Comment by eddelbuettel** [comment]
One more thing I need to sort out: reticulate does not need to be in Imports: making it a hard depends.
I will soften that to a Suggests: and make sure the helper converter and unit tests are conditional on it being present.

**Comment by eddelbuettel** [comment]
Crap. And now I am getting Windows test issues.  Will look into that later.

**Comment by eddelbuettel** [comment]
And on all (!!) other systems.  Probably just a lack of NumPy / SciPy so I will condition that test further.

**Comment by binxiangni** [comment]
If any help is needed, please let me know. Not familiar with system setup and tests, but I'd love to learn that.

**Comment by eddelbuettel** [comment]
Oh, just follow the few recent commits.  I just made some code more conditional -- neither win-builder nor rhub have scipy so we can't just load it unconditionally.  Let me know (here or off-line) if anything is unclear.

**Comment by eddelbuettel** [comment]
And uploaded to CRAN.

**Comment by eddelbuettel** [comment]
And still waiting.  No feedback either.

**Comment by eddelbuettel** [comment]
I just got word of power issues on the campus where the relevant machines are hosted.
