### ISSUE TITLE
Vendoring of Armadillo headers

### ISSUE THREAD

**Issue by SylvainCorlay** [RcppCore/RcppArmadillo#160]
Is it possible to not vendor armadillo headers when dealing with other cases than the cran package, such as linux distributions, other package managers, that may have their own package for armadillo.

**Comment by eddelbuettel** [comment]
We like the degree of freedom offered by having a copy.  We use that in RcppEigen with a carried-over modification of Eigen.  For Armadillo we _could_ do so in Debian but that would be a Debian packaging issue (which has come up for both packages, and I was allowed to "argue it away" as maintainer) though it strictly speaking _is_ a Policy violation.

In any event, downstream packaging has nothing to do the with package _per se_ so closing this.

**Comment by eddelbuettel** [comment]
And don't get me wrong: I agree with your engineering desire _in principle_ particularly in a narrow and controllable stack like Debian.

But I feel I need to balance that with providing an identical experience _for the R package_ across all deployments and architectures.  And there it is sadly much easier to bundle.  So I don't expect that change any time soon.
