### ISSUE TITLE
implement for as<arma::sp_mat> for Matrix classes other than dgCMatrix

### ISSUE THREAD

**Issue by fabian-s** [RcppCore/RcppArmadillo#17]
It would nice if RcppArmadillo knew how to deal with all Matrix-objects inheriting from `CsparseMatrix` (i.e. all Matrix classes in sorted compressed column-oriented form), not just `dgCMatrix`.  The `ngCMatrix`-class doesn't have an x-slot, for example, because the entries are all TRUE/FALSE, so the current implementation of `as<arma::sp_mat>` fails. 
Of course it's usually possible  to do a conversion to `dgCMatrix` on the R-side, but that's messy -- right now, in R you have to do something like 

`as(as(X, "CsparseMatrix"), "dMatrix")`

to every Matrix-object you're handing over to RcppArmadillo to be sort-of-safe that it ends up having the correct class -- but the above will still fail to create a `dgC`-matrix if X inherits from `symmetricMatrix`, for example. You have to do the conversion in this roundabout way because, as Martin Maechler explicitly writes in the Matrix docs,  `as(X, <MatrixClass>)` should only be used to convert `X`  to "virtual Matrix super classes" like `CsparseMatrix` and not actual classes  like `dgCMatrix`, and there aren't any direct `as`-methods to make a `dgCMatrix` from, say, an `ngTMatrix` or a `ddiMatrix`.

These conversions in R can be costly as the matrix gets copied around, it would be more efficient to create the `sp_mat` directly. If that is too difficult, the RcppArmadillo-converter could at least check the class of its input to give more informative/correct error messages. 

Thanks for all your great work on these packages!

**Comment by thirdwing** [comment]
Believe it or not, I am a little surprised about how many matrix classes defined in the `Matrix` package (https://github.com/cran/Matrix/blob/master/src/Mutils.h#L349).

Personally I think at least we need to provide some warning message if it is not `dgCMatrix`.

**Comment by eddelbuettel** [comment]
Agreed on the idea for a warning matrix.  

Sparse support simple is better in (Rcpp)Eigen due to the needs by Doug Bates at the time. Until someone _really_ cranks sparse data with (Rcpp)Armadillo this will remain limited.  A related problem is, of course, the lack of actual sparse matrix transformations as you discovered yesterday in #114.

**Comment by eddelbuettel** [comment]
I guess that is the second time today that I am thinking "hm, maybe for next year's Google Summer of Code".  Someone remind me when the time is closer :)

**Comment by thirdwing** [comment]
Sorry that I pushed to the master by accident. Adding warning is quite easy.

I think this is enough for a GSOC project. Let's make it happen.

```cpp
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
sp_mat foo(sp_mat X) {
  return X;
}
/*
> Rcpp::sourceCpp("test.cpp")
> library(Matrix)
> m <- foo(crossprod(rsparsematrix(10000, 5, .01)))
Warning: dsCMatrix not supported.
*/
```

**Comment by eddelbuettel** [comment]
> pushed to the master by accident.

What? Where? When? I didn't see anything.

GSoC is a good idea. Between you, me and @yixuan we would have it covered.  Going to his [RSpectra](https://cran.r-project.org/package=RSpectra) may be an idea (unless that one is too closely tied to Eigen).

**Comment by thirdwing** [comment]
Let's add a project with details when having time.

https://github.com/rstats-gsoc/gsoc2017/wiki

**Comment by binxiangni** [comment]
For now, the conversion for all numeric sparse matrices inherited from Csparse, Tsparse & Rsparse has been added to the package. You can feel free to use it when the newest package is released. @fabian-s For the nsparseMatrix & lsparseMatrix, could you please give me some examples of their applications? Then I can reflect on the need to convert them through RcppArmadillo. Since I am not frequently working on sparse matrix in my schoolwork, I cannot figure out the applications of the two kinds of sparse matrices.

**Comment by binxiangni** [comment]
I have a silly question: how can I add warning messages in C++?

**Comment by yixuan** [comment]
@binxiangni For R warning messages, simply call `Rcpp::warning()`.

**Comment by eddelbuettel** [comment]
IIRC we wrapped that in Rcpp: 

```
R> library(Rcpp)
R> cppFunction("void demoWarning() { Rcpp::warning(\"Some text here\"); }")
R> demoWarning()
Warning message:
In demoWarning() : Some text here
R>
```

**Comment by eddelbuettel** [comment]
@binxiangni Given your PRs in master, can we close this?

**Comment by binxiangni** [comment]
Sure.
