### ISSUE TITLE
problem with nested calls to RcppArmadillo on Mac with clang4

### ISSUE THREAD

**Issue by rdrr1990** [RcppCore/RcppArmadillo#172]
Hi,

`bigKRLS`, my R package with @rbshaffer, uses `RcppArmadillo`, which has been super useful. However, since `RcppArmadillo` has required `clang4`, `crossvalidate.bigKRLS()` crashes R on my Mac (but not Unix, which isn't having any issues). Some details:

`bigKRLS` (available on [CRAN](https://cran.r-project.org/web/packages/bigKRLS/index.html) and [GitHub](https://github.com/rdrr1990/bigKRLS)) uses `RcppArmadillo` in conjunction with `bigmemory` (by @kaneplusplus). The main regression function is `bigKRLS()`. That function still works on Mac with the newest RcppArmadillo, ‘0.7.960.1.2’. `crossvalidate.bigKRLS()` is really just a wrapper function that splits testing from training data and computes various statistics after calling `bigKRLS()` and the `predict` method; it is only available on Github. 

Optionally, `bigKRLS()` uses `library(parallel)`. Because the new `RcppArmadillo` is meant to make `OMP` usable on Mac (which is awesome), I thought this might be the source of the issue. However, as the test code below shows, it's not a simple matter of disabling `library(parallel)` (by setting `bigKRLS(..., Ncores = 1)`). @rbshaffer and I have run `crossvalidate.bigKRLS` extensively in parallel on both Mac and Unix with older versions of RcppArmadillo without issue; he's run on `crossvalidate.bigKRLS` on ‘0.7.960.1.2’ on Ubuntu without trouble either. 

Everything described here is on `R 3.4.0` or `R 3.4.1`; no differences were noticed between the two. I did not notice any difference with `R 3.4.1 Patched (2017-08-27 r73149)` either. Nor does this seem to be a difference of running `RStudio` vs. `Terminal`.

In terms of configuring my Mac, I followed the instructions of the Coatless Professor (@coatless) found [here](http://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/). Since installing `clang4`, `bigKRLS` won't build on the Mac with the `Makevars` file found on CRAN. However, it will with the `Makevars` he recommends:

```
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX11=$CXX
CXX14=$CXX
CXX17=$CXX
CXX1X=$CXX
LDFLAGS=-L/usr/local/clang4/lib
```

Here is R code that shows the problem:

```
library(bigKRLS)

y = matrix(runif(100))
X = matrix(runif(200), ncol = 2)

works_fine = bigKRLS(y, X)
crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, ptesting = 20, Ncores = 1)
crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, ptesting = 20)
crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, Kfolds = 3)
crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, Kfolds = 3, Ncores = 1)

``` 

On a Unix machine, all of this will run in under a minute with minimal output (some dots for progress bar after each function call and a few instructions). On Mac, the first regression runs and it hangs usually (but oddly enough not always) in the first call to `crossvalidate.bigKRLS` (but always hangs by the second call). Any advice on how to resolve this issue and/or identify the source of the problem would be greatly appreciated!

**Comment by eddelbuettel** [comment]
Hm -- one idea: are you using OpenMP on your mac or not?

**Comment by eddelbuettel** [comment]
Also try [RhpcBLASctl](https://cran.r-project.org/package=RhpcBLASctl) to set the number of cores to 1. 

Otherwise: it would be really helpful to a minimally reproducible example so that those with access to macOS (paging @coatless @kevinushey @thirdwing @binxiangni) can give it a try in order to reproduce.

**Comment by coatless** [comment]
Hi @rdrr1990, 

I can't reproduce the crashes on R 3.4.1 and RStudio 1.1 Preview with the GitHub version of bigKRSL:

<img width="842" alt="screen shot 2017-09-09 at 9 13 36 am" src="https://user-images.githubusercontent.com/833642/30240927-561ba062-953f-11e7-886e-8fc860401b48.png">

I think the main reason why you might be running into an issue with `clang4` is the `Makevars` listed on that website page is out of date.   The instructions found here <https://github.com/coatless/r-macos-clang> are accurate.

I'm working on transitioning the website to a new platform this weekend. When that happens, I can roll out a new update to that post.

In particular, the `Makevars` file must have the following for `clang4`:

```bash
# The following statements are required to use the clang4 binary
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
CXX98=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib
# End clang4 inclusion statements
```

Using the `Makevars` file with `$CXX` references will likely give:

```bash
/bin/sh: XX: command not found
make: *** [file91e37f2852ce.o] Error 127
XX -std=gnu++11
```

You will then need the appropriate gfortran binary as well (6.1.0 or you need to supply a `FLIBS` statement).

**Comment by binxiangni** [comment]
@coatless did you run the above example multiple times? Actually sometimes the code works, but sometimes not. Like this:
```
> crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, ptesting = 20, Ncores = 1)
..........
> crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, ptesting = 20)
........
> crashes_mac_R_session = crossvalidate.bigKRLS(y, X, seed = 123, Kfolds = 3)
1
2
3
4
1
2
3
4
1
2
3
4
.........
.........
.........
```
The third call to `crossvalidate.bigKRLS` didn't stop running. My working environment is R.3.4.1. and RStudio 1.0.153.

**Comment by coatless** [comment]
Ran all three 3x times... Session didn't crash.

https://gfycat.com/gifs/detail/GlossyPowerlessArmadillo

**Comment by eddelbuettel** [comment]
Will guess: interaction with RStudion 1.0.* vs 1.1.* ?  Crashes with release, surives with newer daylies?

**Comment by coatless** [comment]
I wasn't able to create an interaction. Also, see the video showing 3x the execution of the "problematic" code.

**Comment by rdrr1990** [comment]
Many thanks to all for looking into this issue! I just looped the above R code 50 times without a problem (and ran the final, k folds CV in parallel, arguably the most problematic) an additional 100 times without a hitch. Some details:

I am running `R 3.4.1 Patched (2017-08-27 r73149)` on stable `RStudio 1.0.153` for Mac with `gfortran 6.3.0` and `clang4`, which had been installed with bash commands. 

I started (without luck) by switching to the `Makevars` file @coatless describes above for both `~\.R\Makevars` and the `bigKRLS` (github version):

```
# The following statements are required to use the clang4 binary
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
CXX98=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib
# End clang4 inclusion statements
```
When re-building like that still crashed `crossvalidate.bigKRLS`, I used @coatless's [pkg installer](https://github.com/coatless/r-macos-clang). Along with a restart, that did the trick.
