### ISSUE TITLE
Using arma::sp_mat with new RcppArmadillo

### ISSUE THREAD

**Issue by privefl** [RcppCore/RcppArmadillo#178]
Concerning the problems for packages **biglasso** and **bigstatsr** with the new version of **RcppArmadillo** (0.8.100.1.0), I investigated more.

Please see this small reproducible example
```
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>

// [[Rcpp::export]]
arma::sp_mat testSpArma() {
  
  arma::sp_mat beta = arma::sp_mat(2, 3);
  
  beta(0, 0) = 1;
  
  return beta;
}

/*** R
packageVersion("RcppArmadillo")
library(Matrix)
test <- testSpArma()
test[]
*/
```

This is basically a minimal example of how we use `arma::sp_mat` in our two packages. With the previous CRAN version (0.7.960.1.2), it returns a `dgCMatrix` (from package **Matrix**) with one `1` at the first position. With the latest version of RcppArmadillo, it returns a `dgCMatrix` with only 0s.

So my question is how can we change this code in order to work with the new version of **RcppArmadillo**?

**Comment by conradsnicta** [comment]
@eddelbuettel @binxiangni - I suspect that in RcppArmadillo the corresponding SpMat to R sparse matrix conversion is missing a call to `.sync()`. It seems that PR https://github.com/RcppCore/RcppArmadillo/pull/171 was incomplete.

To be specific, in Armadillo 8.x it's absolutely essential to call `.sync()` before reading any of the following internal arrays in any SpMat instance: `values`, `row_indices`, `col_ptrs`.  I suggest to double check any code in RcppArmadillo that access any of the internal SpMat arrays.

Simple example:

    sp_mat X(2,3);
    X(0,0) = 1;
    X.sync();
    // can now read SpMat::values, SpMat::row_indices, SpMat::col_ptrs

Note the call to `.sync()` should be incorporated into the internal SpMat -> dgCMatrix converter inside RcppArmadillo. User packages (such as _biglasso_ and _bigstatsr)_ do not need to be changed.

**Comment by eddelbuettel** [comment]
@privefl Good minimal example, thank you!
@coatless We'll take a look.

**Comment by eddelbuettel** [comment]
Looks like it was missing a single `sm.sync()` in *Wrap on the way out, see fb31a787699a3e66a898dacc117307ec41bdd85b

Now we get

```sh
edd@brad:~/git$ r -e 'Rcpp::sourceCpp("/tmp/rcpparma178.cpp")'

> packageVersion("RcppArmadillo")
[1] ‘0.8.100.1.0’

> suppressMessages(library(Matrix))

> test <- testSpArma()

> test[]
2 x 3 sparse Matrix of class "dgCMatrix"

[1,] 1 . .
[2,] . . .
edd@brad:~/git$
```

@privefl It's early morning here and I won't get to it for a bit but could re-run the tests for `biglasso` and `bigstatr` to see how things work now?

**Comment by privefl** [comment]
Seems OK for both packages.

Thanks @conradsnicta and @eddelbuettel

**Comment by eddelbuettel** [comment]
Awesome.  This was simply one assignment we missed "on the way out" from (Rcpp)Armadillo back to R.  But as it is critically important, it is no wonder the tests failed.  That's why we run them.

My bad for submitting to CRAN with a bad set if tests (using previous RcppArmadillo).  I'll re-run the battery of all of them here.

**Comment by binxiangni** [comment]
Sorry to mess it up. My bad for not checking the `wrap()`. 😭

**Comment by eddelbuettel** [comment]
No worries, it happens. I also messed the last reverse depends check up and should have seen thos. 
In a a way it is more on all of us to not have thought of a unit test for that case either.   

I confirmed here that `biglasso` and `bigstatr` are now fine and launched a new reverse-depends check against all (and by now 405) packages.

**Comment by coatless** [comment]
@binxiangni Heh, if only you knew how often it happens ;-)

**Comment by binxiangni** [comment]
@coatless Hah, I’ll continue to mess it up and prove how often ;-)

**Comment by eddelbuettel** [comment]
See, Google of Summer Code _really works_ but you now *really* know how we operate :)

**Comment by gvegayon** [comment]
fb31a787699a3e66a898dacc117307ec41bdd85b works for me know with https://github.com/USCCANA/netdiffuseR
