### ISSUE TITLE
mandatory Matrix package

### ISSUE THREAD

**Issue by sgsokol** [RcppCore/RcppArmadillo#194]
Currently, it is mandatory to load package Matrix if someone get sparse matrix in parameter or turn it back to R environment. I proposed a patch (pr #192) that was supposed to circumvent an obligation to do so but Matrix is still needed. I would like to propose another one that will finally allow to avoid an obligation to load Matrix.
With this new path, a user function can take a simple_triplet_matrix type as argument and (to go in opposite direction) use a function 
```
List simple_triplet_matrix(const arma::SpMat<T> &)
```
to be able to return a sparse matrix without requiring S4 classes defined in Matrix package.

The motivation behind all of this is that a user needing only lightweight operations on sparse matrices should have an opportunity to pass by lightweight packages. Unfortunately, Matrix can require more than 1&nbsp;s to load which can be prohibitive for programs intended to run in very short time.

**Comment by eddelbuettel** [comment]
Well but there are other conversion besides the one you added, and they all need Matrix as it is creates the dgCMatrix.  Plus, Matrix is almost base R so I am not sure I _really_ care about the extra installation footprint.

**Comment by sgsokol** [comment]
I have made tests unloading Matrix and it passes.
Even being almost base R, Matrix is not loaded every time (fortunately!)

**Comment by eddelbuettel** [comment]
Ok, lighter depends is a good goal.  Do the tests requiring Matrix then become optional?  I am still not quite sure what exactly you want to do (but _Big Thank You_ for starting with an issue ticket !).

**Comment by sgsokol** [comment]
Well, they can become optional (it will require some rewriting) but for now I did not touch to them. As for tests we don't look for getting 1 s less, do we?

**Comment by eddelbuettel** [comment]
No, run time is not a constraint.  Fewer depends is good, ideally at unchanged test coverage.

**Comment by eddelbuettel** [comment]
Addressed in #196
