### ISSUE TITLE
sgemm compile fails on Windows 7

### ISSUE THREAD

**Issue by cdeterman** [RcppCore/RcppArmadillo#197]
I have create a very simple package from Rstudio using RcppArmadillo.  The only function I have included is the following which uses 'sgemm'.  It works without a problem if I use 'dgemm'.

```r
#include <RcppArmadillo.h>

using namespace Rcpp;

// [[Rcpp::export]]
SEXP arma_sgemm(
    const arma::fmat A,
    const arma::fmat B)
{
    arma::fmat C = A * B;
    return wrap(C);
}
```

This fails to compile though with the following errors

>** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.3/library/RcppArmadillo/include"     -fopenmp    -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.3/library/RcppArmadillo/include"     -fopenmp    -O2 -Wall  -mtune=generic -c rcpparma_hello_world.cpp -o rcpparma_hello_world.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/Program Files/R/R-3.4.3/library/Rcpp/include" -I"C:/Program Files/R/R-3.4.3/library/RcppArmadillo/include"     -fopenmp    -O2 -Wall  -mtune=generic -c test.cpp -o test.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o test.dll tmp.def RcppExports.o rcpparma_hello_world.o test.o -fopenmp -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lR
test.o:test.cpp:(.text+0x357): undefined reference to `sgemm_'
test.o:test.cpp:(.text+0x5bf): undefined reference to `sgemv_'
test.o:test.cpp:(.text+0x6cc): undefined reference to `sgemv_'
collect2.exe: error: ld returned 1 exit status
no DLL was created

**Comment by eddelbuettel** [comment]
R does not support floating point.

**Comment by cdeterman** [comment]
I see, thanks for the explanation.

**Comment by eddelbuettel** [comment]
It's stupid, but it is what it is.  And on the platforms with limited BLAS it is *really* hard to code around. Witness Baptiste's issues with complex solve functions (cf recent list traffic).

**Comment by dselivanov** [comment]
FYI https://github.com/wrathematics/float/issues/4
