### ISSUE TITLE
Trouble installing RcppArmadillo on an external Linux server 

### ISSUE THREAD

**Issue by bobems1215** [RcppCore/RcppArmadillo#198]
Hello, 
I have been trying to install a new pipeline on the external server that our lab uses and this pipeline includes a DESeq2 analysis which requires RcppArmadillo. This should have been a fairly easy install but the gcc version on the server is outdated and needed to be updated. The problem there is that I do not have admin privileges so I had to install to local directories. After updating gcc in my local environment I keep getting errors about va_list not being declared when I tray to install RcppArmadillo through R. I am sure this has some thing to do with the way I updated gcc but I don't know where to start troubleshooting this.

currently my gcc is version 5.2.0, and the server is running R 3.2.1 any thoughts on how to fix this?

Thanks,
Bob

**Comment by eddelbuettel** [comment]
There are documented minimal requirements.  Either make your system match them or, and that may be easier, just install an older RcppArmadillo version.   They are [all available](https://cloud.r-project.org/src/contrib/Archive/RcppArmadillo/).

I'll close this as there is actually no defect here.  Feel free to come to the rcpp-devel to discuss best practices and whatnot.
