### ISSUE TITLE
please implement index_min() and index_max() for cube

### ISSUE THREAD

**Issue by githubtomtom** [RcppCore/RcppArmadillo#199]
the index_min() and index_max() for cube would be called like:
index_min(Q, dim)
where Q is a cube, and dim is in the set {0, 1, 2}

Thanks!

**Comment by coatless** [comment]
Not the appropriate form for this... See https://github.com/conradsnicta/armadillo-code

With this being said, `dim` is already allocated in the non-member form, [`index_min()` and `index_max()`](http://arma.sourceforge.net/docs.html#index_min_and_index_max_standalone), to specify the output vector (e.g. `vec` or `rowvec`).

You might want to post this kind of question (e.g. "How do I specify a range of slices to find a minimum or max value across?") on https://stackoverflow.com

**Comment by eddelbuettel** [comment]
I think we can close this.
