### ISSUE TITLE
During install reports omp.h missing, but seems to be present

### ISSUE THREAD

**Issue by vforget** [RcppCore/RcppArmadillo#200]
Hi I am attempting to install package but get the following error:

```
# sudo Rscript -e 'install.packages(c("RcppArmadillo"), repos="http://cran.us.r-project.org")'
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.us.r-project.org/src/contrib/RcppArmadillo_0.8.300.1.0.tar.gz'
Content type 'application/x-gzip' length 1318517 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -m64 accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 7.2.1
checking LAPACK_LIBS... fallback LAPACK from R 3.3.0 or later used
checking for macOS... not found as on Linux
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
g++ -m64 -std=gnu++11 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include  -I../inst/include -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppArmadillo.cpp -o RcppArmadillo.o
In file included from ../inst/include/RcppArmadilloForward.h:46:0,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo:91:12: fatal error: omp.h: No such file or directory
   #include <omp.h>
            ^~~~~~~
compilation terminated.
make: *** [RcppArmadillo.o] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/usr/lib64/R/library/RcppArmadillo’

The downloaded source packages are in
        ‘/tmp/Rtmp6Tx96D/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(c("RcppArmadillo"), repos = "http://cran.us.r-project.org") :
  installation of package ‘RcppArmadillo’ had non-zero exit status
``` 

OS:
```
# uname -a
Linux ip-172-31-10-138 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
R version:
```
# R --version
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

```

GOMP:
```
# /sbin/ldconfig -p | grep gomp
        libgomp.so.1 (libc6,x86-64) => /usr/lib64/libgomp.so.1
        libgomp.so.1 (libc6) => /usr/lib/libgomp.so.1
```

Clearly, some other library may be missing. On AWS, this worked without issue previously,  but I needed to replace that instance due to AWS contacting me that the instances was being de-commissioned. I created a new instance and now I have this issue. The AWS instance I used is:

https://aws.amazon.com/marketplace/pp/B00CIYTQTC

Thanks in advance for your help.

Vince

**Comment by eddelbuettel** [comment]
I fear we will need to rely on _you_ for finding why/where/how this goes pear-shaped.  See the [CRAN check results page for RcppArmadillo](https://cloud.r-project.org/web/checks/check_results_RcppArmadillo.html)  indicating that _e.g._ Fedora is fine too (modulo our error of not testing if package `slam` is present).

**Comment by eddelbuettel** [comment]
And just for the obvious one: you show `libgomp` runtime files, you may also need the -dev package supplying the header.

**Comment by vforget** [comment]
As usual, found the answer shortly after. Version of g++ was too recent, 7.2.1. Also had g++-4.8 installed, so simple fix was to remove 7.2.1, which made it fall back to v4.8:

`sudo yum remove gcc72-c++.x86_64 libgcc72.x86_64`

Then RcppArmadillo install process failed due to missing Fortran lib, which I fixed:

`sudo yum install gcc-gfortran.noarch`

Compiles fine now. I assume the AWS instance added a newer g++ version, hence why it worked previously.

V

**Comment by Misterresearch** [comment]
I would just add that once  sudo yum remove gcc72-c++.x86_64 libgcc72.x86_64 executed, it will remove three dependencies, two of them will empty the R_INCLUDE_DIR of its header files, which are needed to install packages. You will then need to re-install them with the following:

sudo yum install R-core-devel.x86_64 0:3.4.1-1.52.amzn1    R-devel.x86_64 0:3.4.1-1.52.amzn1 

After this, installing data.table will work on Amazon Linux AMI

**Comment by benmwhite** [comment]
Our team was having the same problem and managed to resolve this issue by installing an older version of the C++ compiler (6.4) and creating a new symlink. This was on Amazon AMI version 4.14.77-70.82.amzn1.x86_64 x86_64.

```
sudo yum install gcc64.x86_64
sudo rm /etc/alternatives/g++
sudo ln -s /usr/bin/g++64 /etc/alternatives/g++
```

The RcppArmadillo installation worked after this.

**Comment by eddelbuettel** [comment]
Looks like `yum` is a commonality here so maybe one of you affected could follow-up with RedHat?
