### ISSUE TITLE
armadillo 8.400 RC1

### ISSUE THREAD

**Issue by conradsnicta** [RcppCore/RcppArmadillo#201]
@eddelbuettel @coatless @kthohr - I've released Armadillo 8.400 RC1 (Release Candidate 1):
http://sourceforge.net/projects/arma/files/armadillo-8.400-RC1.tar.xz

Could you test it and let me know if you encounter any issues?

Changes:
- added [wishrnd()](http://arma.sourceforge.net/docs.html#wishrnd) and [iwishrnd()](http://arma.sourceforge.net/docs.html#iwishrnd) for generation of random Wishart matrices
- added [chi2rnd()](http://arma.sourceforge.net/docs.html#chi2rnd) for generation of chi-squared random numbers
- added [normcdf()](http://arma.sourceforge.net/docs.html#normcdf)
- added [submatrix & subcube iterators](http://arma.sourceforge.net/docs.html#iterators_submat)
- faster handling of sparse matrices by [repmat()](http://arma.sourceforge.net/docs.html#repmat)
- faster [loading](http://arma.sourceforge.net/docs.html#save_load_mat) of CSV files
- expanded [kron()](http://arma.sourceforge.net/docs.html#kron) to handle sparse matrices
- expanded [index_min()](http://arma.sourceforge.net/docs.html#index_min_and_index_max_standalone) and [index_max()](http://arma.sourceforge.net/docs.html#index_min_and_index_max_standalone) to handle cubes
- expanded [randi()](http://arma.sourceforge.net/docs.html#randi), [randu()](http://arma.sourceforge.net/docs.html#randu_randn_standalone), [randn()](http://arma.sourceforge.net/docs.html#randu_randn_standalone), [randg()](http://arma.sourceforge.net/docs.html#randg) to output single scalars

**Comment by coatless** [comment]
@conradsnicta a thousand thanks for the work on the random number generation, e.g. scalars + wishart! (You've also just blown up the use one of my packages... But, I'll take it!)

**Comment by conradsnicta** [comment]
@coatless - sorry for blowing up your stuff :-)  Could you test the Wishart stuff?  I'm currently not 100% certain on it.

**Comment by coatless** [comment]
@conradsnicta few quick remarks:

- Implementation wise, it matches with what I was running: 

https://github.com/coatless/r-to-armadillo/blob/3ebbc49b219c3d49724c110709f4d545108f7f7f/src/distributions.cpp#L28-L55

https://github.com/conradsnicta/armadillo-code/blob/d5c0f728a0bf392ea93be10a4d34a793230b7d8c/include/armadillo_bits/op_wishrnd_meat.hpp#L134-L155

- `df` should always be an integer.
- Could we switch it from `wishrnd(S, df)` to `wishrnd(df, S)`? The latter is the preferred notation. 
- I tested the wishart generation using my [branch of RcppArmadillo](https://github.com/coatless/rcpparmadillo/tree/feature/armadillo-8.400-rc1) and it was within the error tolerances:

```r
# Build the C++ function
Rcpp::cppFunction("arma::mat test_rwishart(arma::mat S, int df) {
  return arma::wishrnd(S, df);
}", plugins = "cpp11", depends = "RcppArmadillo")

# Run through tests:

## Artificial
S = toeplitz((10:1)/10)

set.seed(11)
R = replicate(1000, test_rwishart(S, 20))

dim(R) 
#  10 10  1000

mR = apply(R, 1:2, mean)  
# ~= E[ Wish(S, 20) ] = 20 * S

stopifnot(all.equal(mR, 20*S, tolerance = .009))

## See Details, the variance is
Va = 20*(S^2 + tcrossprod(diag(S)))
vR = apply(R, 1:2, var)

stopifnot(all.equal(vR, Va, tolerance = 1/16))
```

**Comment by conradsnicta** [comment]
@coatless - thanks for testing this

> df should always be an integer.

There seem to be uses for non-integer df (eg. in MCMC).  I'm following the algorithm by Ku & Bloomfield (2010) which allows fractional df:  http://www.gwu.edu/~forcpgm/YuChengKu-030510final-WishartYu-ChengKu.pdf

However, the code in Armadillo does check for an integer `df` and uses a simpler algorithm for that case, which skips the generation of chi2 random values.

> Could we switch it from wishrnd(S, df) to wishrnd(df, S)? The latter is the preferred notation.

Since Armadillo generally has Matlab-like syntax, I've followed the form for `wishrnd()` as used in Matlab:
https://mathworks.com/help/stats/wishrnd.html

Could you also test `iwishrnd()`?  It uses a bunch of reasonable assumptions to enhance efficiency. It would be good to ensure these assumptions don't blow up.

**Comment by kthohr** [comment]
Hi @conradsnicta 

I checked
* wishrnd and iwishrnd
* randg
* normcdf
* kron (for sp_mat)

and everything came out as expected.

One suggestion, however. Based on my experience, the df_simple case here

https://github.com/conradsnicta/armadillo-code/blob/unstable/include/armadillo_bits/op_wishrnd_meat.hpp#L124

is very inefficient when df is large (as tmp'tmp is costly to calculate). Example: when df = 1E05 and S = eye(3,3), the second implementation---similar to what I use in my library, but for integer df---runs ~ 100 times faster than df_simple, even with multi-threaded BLAS.

Perhaps remove the df_simple case entirely, or include a `(df < some_bound)` switch?

**Comment by eddelbuettel** [comment]
I ran a complete reverse depends check and just going over the results -- we may have one regression in one package that I need to look at more closely.

**Comment by eddelbuettel** [comment]
Looked at that package--it fails with the CRAN version of RcppArmadillo too so no regression here.

**Comment by conradsnicta** [comment]
@kthohr - thanks for doing the tests. You're right about the df_simple case. I've refactored the code to use the simple generator only if df < number of rows in the given matrix.

**Comment by conradsnicta** [comment]
@eddelbuettel - thanks for running the tests; good to hear that there are no regressions.

**Comment by conradsnicta** [comment]
fixed rolled into RC2:
http://sourceforge.net/projects/arma/files/armadillo-8.400-RC2.tar.xz

**Comment by donaldRwilliams** [comment]
Hi:
I was wondering if there were changes made to the functions, as it does not seem to work for me as expected.

R solution
````
R_wish <- rWishart(10000, 20, S)
mean(diag( apply(R_wish, c(1, 2), mean) )) # about 20 as expected
20.06603
`````

**Comment by eddelbuettel** [comment]
Sorry, why is this in a 13 month old thread?  Are you tying this to a particular release?

Or is this the same as #247 which you just filed to?  If so, do you mind just deleting your post here (after confirming).  I'll gladly delete mine.

**Comment by donaldRwilliams** [comment]
It is the same. I was not sure, because it was closed, that you would receive further notifications. I will deleted it.
