### ISSUE TITLE
Bash script to automate updating armadillo

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppArmadillo#203]
I was surprised to see that Armadillo doesn't yet have a bash script to automatically update the `armadillo_bits` like [`BH`'s CreateBoost.sh](https://github.com/eddelbuettel/bh/blob/master/local/scripts/CreateBoost.sh).

Feature wise the script needs to:

- [ ] Accept URL
- [ ] Extract version info
- [ ] Extract only `armadillo_bits` and `armadillo` into `inst/include`
- [ ] Add customary change statement to `ChangeLog`
- [ ] Perform a commit

**Comment by eddelbuettel** [comment]
I don't one.  It is one or two rsync invocations, and I like seeing what happens.

BH is different as it uses a carefully-curated subset.

**Comment by coatless** [comment]
Mind sharing the `rsync` setup?

**Comment by eddelbuettel** [comment]
Essentially just

```
cd /tmp
wget url_from_arma.sf.net       # as conrad does not like me updating from svn or git
tar xaf ...
rsync -nav arma-*/include/armadillo  ~/git/rcpparmadillo/inst/include/armadillo     # also without 'n' 
rsync -nav arma-*/include/armadillo_bits/  ~/git/rcpparmadillo/inst/include/armadillo_bits/   # ditto
```

and sometimes I throw a `--delete` in to see if files are now obsolete.

**Comment by coatless** [comment]
@eddelbuettel thanks! `rsync` looks like the predecessor to cloud storage.
