### ISSUE TITLE
ERROR in BioCircos installation in R package.

### ISSUE THREAD

**Issue by deppworld** [RcppCore/RcppArmadillo#208]
> install.packages()
Installing package into ‘/home/deepak/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/BioCircos_0.3.3.tar.gz'
Content type 'application/x-gzip' length 422701 bytes (412 KB)
==================================================
downloaded 412 KB

* installing *source* package ‘BioCircos’ ...
** package ‘BioCircos’ successfully unpacked and MD5 sums checked
mv: cannot move '/home/deepak/R/x86_64-pc-linux-gnu-library/3.4/BioCircos' to '/home/deepak/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-BioCircos/BioCircos': Permission denied
Warning in file.copy(f, instdir, TRUE) :
  problem copying ./NAMESPACE to /home/deepak/R/x86_64-pc-linux-gnu-library/3.4/BioCircos/NAMESPACE: Permission denied
Warning in file.copy(f, instdir, TRUE) :
  problem copying ./LICENSE to /home/deepak/R/x86_64-pc-linux-gnu-library/3.4/BioCircos/LICENSE: Permission denied
Warning in file(file, if (append) "a" else "w") :
  cannot open file '/home/deepak/R/x86_64-pc-linux-gnu-library/3.4/BioCircos/DESCRIPTION': Permission denied
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package ‘BioCircos’
* removing ‘/home/deepak/R/x86_64-pc-linux-gnu-library/3.4/BioCircos’

The downloaded source packages are in
	‘/tmp/RtmpVXCTcJ/downloaded_packages’
Warning message:
In install.packages() :
  installation of package ‘BioCircos’ had non-zero exit status

I tried multiple way did not able to install. Please Help

**Comment by eddelbuettel** [comment]
Looks like a local permissions issue.

**Comment by eddelbuettel** [comment]
BioCircos has nothing to with RcppArmadillo, so no idea why you are filing this here.

And for the record, it install just fine:

```sh
edd@rob:~$ install.r BioCircos     ## install.r from littler calls install.packages()
trying URL 'https://cloud.r-project.org/src/contrib/BioCircos_0.3.3.tar.gz'
Content type 'application/x-gzip' length 422701 bytes (412 KB)
==================================================
downloaded 412 KB

* installing *source* package ‘BioCircos’ ...
** package ‘BioCircos’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (BioCircos)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
edd@rob:~$ 
```
