### ISSUE TITLE
49: Error: expecting string instruction after `rep'

### ISSUE THREAD

**Issue by ignaciomsarmiento** [RcppCore/RcppArmadillo#210]
I'm running R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree" on a Scientific Linux release 6.9 (Carbon) machine. I'm trying to install RcppArmadillo and I get the following errors. 

checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -m64 accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, but without OpenMP as version 4.8.2 (Armadillo constraint)
checking LAPACK_LIBS... fallback LAPACK from R 3.3.0 or later used
checking for macOS... not found as on Linux
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
g++ -m64 -std=gnu++0x -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include  -I../inst/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppArmadillo.cpp -o RcppArmadillo.o
{standard input}: Assembler messages:
{standard input}:49: Error: expecting string instruction after `rep'
{standard input}:4849: Error: expecting string instruction after `rep'
make: *** [RcppArmadillo.o] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/usr/lib64/R/library/RcppArmadillo’
ERROR: dependency ‘RcppArmadillo’ is not available for package ‘bife’
* removing ‘/usr/lib64/R/library/bife’

The downloaded source packages are in
	‘/tmp/RtmpGsVYSV/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

Is there a way to fix this? 
Best,

Ignacio

**Comment by eddelbuettel** [comment]
So per

```
checking whether g++ version is sufficient... yes, but without OpenMP as version 4.8.2 (Armadillo constraint)
```

you use `g++ 4.8.2` which ought to be sufficient.  But something goes belly up with the compiler. I think you may have to test this locally:

- unpack the tarball
- remove / rename the script `configure`  in the top-level as it will overwrite `src/Makevars`
- manually copy `src/Makevars.in` to `src/Makevars` and select whatever options you need; contact local admins

If everything else fails pick an older RcppArmadillo release from [the archive section](https://cloud.r-project.org/src/contrib/Archive/RcppArmadillo/).  Newer ones require new-enough compilers.

**Comment by eddelbuettel** [comment]
Also: sometimes such "internal" errors of the compilers are a symptom of resource starvation. Are you on a proper machine, or is this some super-low-memory blade or cloud instance?  g++ 4.8.* has worked in the past which why do not error on when we check minimal versions.

**Comment by ignaciomsarmiento** [comment]
Thanks Dirk, after trying the lazy solution, i.e. trying previous releases, which did not work (I went up to RcppArmadillo_0.6.400.2.2.tar) 
I started looking more into it. The problem was a binutils version mismatch,  installing devtoolset-2-binutils solved the problem.

**Comment by eddelbuettel** [comment]
Bingo, well analysed. I had actually never seen _that_ error and it hinted at something internal.

So with the tools aligned `g++ 4.8.2` is still "good enough" ?

**Comment by ignaciomsarmiento** [comment]
Yeap, that is still "good enough"
