### ISSUE TITLE
Problem with a advanced constructor but only for the arma::uvec when copy_aux_mem=false

### ISSUE THREAD

**Issue by Polkas** [RcppCore/RcppArmadillo#215]
Hi I have been writing my own package which is based on Rcpp/RcppArmadillo. Moreover I use RccpModule to enable the OOP paradigm. 
I have problem at lines 29-33 where I want to build uvec by a reference.:
https://github.com/Polkas/miceFast/blob/master/src/miceFast_class.cpp#L29-L33
I want to state that it works perfectly for a vec and mat.  The uvec pointer seams to randomly losing right address and has exploding manner for values.

e.g.
providing values such 1:10 results in 1,2,432332432,4,5,....
or all of them are huge or all of them are totally random

I replaced a desired uvec by a colvec and convert a type at the evaluation step by `arma::conv_to<arma::uvec>::from`.  But this solution demands from users to convert int vector to a numeric type at the R environment.

**Comment by eddelbuettel** [comment]
That is to be expected because R only knows a signed integer type. So you must either convert to `double` (to preserve the values larger than `INT_MAX`) or convert to `integer` (and risk dropping values, though it may be rare).

There is nothing Rcpp or RcppArmadillo can do here -- R only supports a smaller set of types.  I suggest we close this.

**Comment by dselivanov** [comment]
To clarify a bit. It is very likely that you use 64bit system and `uvec` = `vec<uword>` and `uword` is 64 bit unsigned integer. What I believe you really need is `vec<int>` or `vec<uint32_t>`. The former will be identical to R's integer vector and the latter will have same as R representation of integers up to 2**31.

**Comment by eddelbuettel** [comment]
Even if it were 32 bit, the `uint32_t` != `int32_t` so we have to cast to match the type R(cpp) can handle.

**Comment by Polkas** [comment]
Thank you for your guidance.
