### ISSUE TITLE
Installation on MAC OS, g++ version not sufficient

### ISSUE THREAD

**Issue by sentian** [RcppCore/RcppArmadillo#223]
Thanks for the great package. I have a problem of installation on MAC OS. 

I compiled from the source and the version is 0.8.500.0. During the installation process, it shows some warnings (attached below). However, I do have 'g++' (Homebrew GCC 8.1.0) 8.1.0 available, and I think that's the newest version. I'm wondering where these warnings come from and how I can fix it. Thanks for the help

```
checking whether g++ version is sufficient... almost
configure: WARNING: Compiler self-identifies as being compliant with GNUC extensions but is not g++.
checking for macOS... found
checking for macOS Apple compiler... found
configure: WARNING: OpenMP unavailable and turned off.
checking LAPACK_LIBS... R-supplied partial LAPACK found
configure: WARNING: Some complex-valued LAPACK functions may not be available
```

**Comment by coatless** [comment]
Show us your `~/.R/Makevars` I think this is the case of not changing the `CXX` and `CXX11`...

**Comment by sentian** [comment]
Here's my `~/.R/Makevars` file:

```
CC=gcc
CXX=g++
CXX1X=g++
CXX11=g++

SHLIB_OPENMP_CFLAGS= -fopenmp
SHLIB_OPENMP_CXXFLAGS= -fopenmp
SHLIB_OPENMP_FCFLAGS= -fopenmp
SHLIB_OPENMP_FFLAGS= -fopenmp
```

**Comment by kthohr** [comment]
By default, `g++` is an alias for Apple's version of Clang. Try `g++ --version`:
```
...
Apple LLVM version 9.1.0 (clang-902.0.39.1)
...
```
You need to set `CXX`, etc., to the appropriate path (or alias) for gcc8. See the following thread for details:

RcppCore/RcppArmadillo/issues/143

**Comment by sentian** [comment]
Already did. Here's what `gcc --version` gives:

```
gcc (Homebrew GCC 8.1.0) 8.1.0
```

**Comment by eddelbuettel** [comment]
That is a highly non-standard setup on macOS so you will need to debug / analyze the shell commands we have in `configure.ac` (and which get expanded to `configure`) to figure out where it fails.

None of us have that setup as it does not correspond to any of the supported or recommended macOS setups.

**Comment by kthohr** [comment]
R clearly doesn't see this, based on the result of 
```
checking for macOS Apple compiler... found
```
Try setting the full path for gcc8 in Makevars under `CXX`, e.g.,
```
...
CC=/usr/local/gcc8/bin/gcc
CXX=/usr/local/gcc8/bin/g++
...
```

**Comment by sentian** [comment]
Thanks for the help guys.

@eddelbuettel I agree. I'm very new to all the gcc/clang stuff, and just blindly follow some instructions online of installing and configuring 'brew gcc'. They suggest add the PATH in .bash_profile and I guess it masks the gcc/clang from Xcode. What's a standard setup anyway?

@kthohr I changed it. And it works now. I guess adding PATH (/usr/local/..) to the .bash_profile, does not mask Apple's clang successfully. 

But I do get an error message when compiling from source. I will lay it out by opening a new issue. Feel free to close this one since it has been resolved. Thanks again.

**Comment by kthohr** [comment]
The 'standard setup' is available from the R website:

https://cran.r-project.org/bin/macosx/tools/

which is also linked in the issue thread I mentioned above.  

FYI: Environment variables set in .profile or .bash_profile might not be visible in R unless you launch R from a shell environment.

**Comment by sentian** [comment]
Got it thanks @kthohr

**Comment by eddelbuettel** [comment]
Will close then.  As an FIY, we have some things to say about this in the [Rcpp FAQ](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf) but all this also tends to change a lot and fast.
