### ISSUE TITLE
trouble installing RcppArmadillo as a dependency for DeSeq2

### ISSUE THREAD

**Issue by sengoku93** [RcppCore/RcppArmadillo#226]
Hi,

After extensively looking through github, biostars, and stackoverflow for possible solutions to my issue of installing RcppArmadillo as a dependency for DeSeq2. I have tried updating gcc used via homebrew and macports as well as installing xcode command line tools. I have also tried to install older versions of RcppArmadillo that other users have said worked. None of this help me successfully install RcppArmadillo. I have attached an image below of my console window. Any suggestions or advice will be very much appreciated. Thank you!

**Comment by kthohr** [comment]
The error is pretty clear: R cannot find your gcc installation. Update your settings in `~/.R/Makevars`. 

See the following thread for details and suggestions:

RcppCore/RcppArmadillo/issues/143

**Comment by eddelbuettel** [comment]
@sengoku93 Please do not post images.

**Comment by coatless** [comment]
@sengoku93 you need to install the gfortran.

Use: https://cran.r-project.org/bin/macosx/tools/gfortran-6.1.pkg

**Comment by sengoku93** [comment]
@coatless , what is the reasoning behing installing gfortran in order for package to download successfully. 

Also, what is ~/.R/Makevars?

Thank you for your time!

**Comment by eddelbuettel** [comment]
You need to link against `quadmath`. 

~ is your home directory, ~/.R is a directory named capital-R in your home directory, and ~/.R/Makevars is where R looks for possible overrides of compilers and other builds settings.  As I understand it macOS users need to set it.

**Comment by coatless** [comment]
Evidence on this evolves overtime...

**Comment by coatless** [comment]
So, you need to install manually `data.table` via:

```r
install.packages(c("data.table"))
```

**Comment by eddelbuettel** [comment]
Also consider r-help or StackOverflow; this not the place for generic R help.
