### ISSUE TITLE
Issue with important and installing dendextend - URGENT PLEASE HELP!

### ISSUE THREAD

**Issue by Mshoukat1992** [RcppCore/RcppArmadillo#232]
Hi,

I recently encountered an issue with dendextend which I have historically been using with no issues.
When I call the library (library(dendextend)) in bash I get an error following which I uninstalled and reinstalled dendextend which now no longer installs.

I get the following error on installation using
install.packages("dendextend")

Error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so':
  dlopen(/usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
  Referenced from: /usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so
  Reason: image not found
ERROR: lazy loading failed for package ‘dendextend’
* removing ‘/usr/local/lib/R/3.5/site-library/dendextend’

The downloaded source packages are in
	‘/private/var/folders/tw/fgxg7p2x1v14h9n_29dv64th0000gn/T/RtmpLoHIjI/downloaded_packages’
Warning message:
In install.packages("dendextend") :
  installation of package ‘dendextend’ had non-zero exit status

I am using the most up to date version of R 1.1.4

**Comment by eddelbuettel** [comment]
You are at the wrong repo, and you are shouting. Neither one helps.  Maybe try StackOverflow, or a mailing list.

**Comment by Mshoukat1992** [comment]
My apologies - Do you know why installing might be giving an error?
