### ISSUE TITLE
error to install

### ISSUE THREAD

**Issue by abreuef** [RcppCore/RcppArmadillo#267]
Hi,
I am getting this error message when trying to install PccpArmadillo. Any idea about what is happening?

Thanks a lot!

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
checking for g++... g++
checking whether the C++ compiler works... no
configure: error: in `/private/var/folders/th/62h3hqb11n34s0p6f76fhr600000gn/T/Rtmppijop3/R.INSTALL2aaf73e4437b/RcppArmadillo':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘RcppArmadillo’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo’
Warning in install.packages :
  installation of package ‘RcppArmadillo’ had non-zero exit status

**Comment by eddelbuettel** [comment]
Someone called James will assist you shortly.  In the meantime, do me the favour of reading the existing documentation (hint: the Rcpp FAQ pdf is good) and pester the r-sig-mac mailing list.

This is a source code repo.  The source works on every real operating system. I am not responsible for the mess that R and macOS make so I am closing this as I am tired of every other so-called "bug" report being about it seemingly being to hard for folks to get macOS to work.

![image](https://user-images.githubusercontent.com/673121/64178638-71373280-ce27-11e9-8207-dfc658ba177f.png)

**Comment by eddelbuettel** [comment]
Also paging @coatless

**Comment by abreuef** [comment]
I am very sorry to bother you. I am new in R and also its my first time using GitHub. Thanks for you assistance.

___
Edson Fiedler de Abreu Júnior
PhD Student

Laboratório de Mamíferos
Dep. de Ciências Biológicas - ESALQ
Universidade de São Paulo

**Comment by eddelbuettel** [comment]
Before filing an issue, consult both open issues as well as closed issues -- you can search for strings there.

If maxOS is giving you fits try working on linux.  I haven't looked back in 25 years.

**Comment by coatless** [comment]
@abreuef from the error message, it seems like Xcode CLI tools weren't installed. Can you follow the guide here:

https://thecoatlessprofessor.com/programming/r-compiler-tools-for-rcpp-on-macos/
