### ISSUE TITLE
Unable to create package with force = TRUE

### ISSUE THREAD

**Issue by Mervap** [RcppCore/RcppArmadillo#272]
The following command
`RcppArmadillo::RcppArmadillo.package.skeleton(force = FALSE)`
fails with

>Calling kitten to create basic package.
>Error in (function (name = "anRpackage", path = ".", author, maintainer, : unused argument >(force = FALSE)
> 
>Error in value[[3L]](cond) : error while calling `kitten`

It fails only if `pkgKitten` is installed

**Comment by eddelbuettel** [comment]
You we please stop issue ticket ping pong?   I wrote both of these, I am aware of the symmetry,

**Comment by Mervap** [comment]
Issue #229 in this repository was not resolved in the second. Yes, because of this, I felt it necessary to duplicate. I'm sorry to inconvenience you

**Comment by eddelbuettel** [comment]
Not my fault if that fellow made the change and never PRed back to me.
