### ISSUE TITLE
RcppArmadillo sample with different probabilities 

### ISSUE THREAD

**Issue by emanuelegdepaoli** [RcppCore/RcppArmadillo#275]
I've found a problem with RcppArmadillo sample function when the sampling probabilities are not constant. 
The code is:

```
#include <RcppArmadillo.h>
#include <RcppArmadilloExtensions/sample.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;
using namespace std;

// [[Rcpp::export]]
uvec arma_sample(int n, int k, vec prob){
  uvec out(n, fill::zeros);
  vec comp = regspace(1,  k);
  prob.print();
  for(int i = 0; i < n; ++i){
    out(i) = Rcpp::RcppArmadillo::sample(comp, 1, false, prob)[0];
  }
  prob.print();
  return out;
}
```

and the output when the function is called in R:

```
> res = arma_sample(10^4, 2, c(0.1,0.9))
   0.1000
   0.9000
   0.5000
   0.5000
> prop.table(table(res))
res
     1      2 
0.4934 0.5066 `

```

Apparently the function is sampling from a discrete distribution with uniform probabilities.

**Comment by eddelbuettel** [comment]
@helmingstay Are you around and able to take a look?

**Comment by helmingstay** [comment]
Ouch. Thanks for @emanuelegdepaoli for the lovely bug report.
To clarify, the first call to sample() works as intended, but the input arma::vector prob was clobbered by the worker functions called by sample_main, e.g., ProbSampleReplace.

The input prob vector is now passed as const and copied inside sample_main.

**Comment by emanuelegdepaoli** [comment]
Thank you @helmingstay
