### ISSUE TITLE
Inconsistency between RcppArmadillo::sample and the sample in r

### ISSUE THREAD

**Issue by hyqsumile** [RcppCore/RcppArmadillo#278]
Hi, I find that the new version of R has changed the implementation of function sample() (see: https://community.rstudio.com/t/getting-different-results-with-set-seed/31624/5). But the RcppArmadillo::sample still follows the old version. By default, the content in this page(https://gallery.rcpp.org/articles/using-the-Rcpp-based-sample-implementation/) is outdated and can not be reproduced in the updated R studio 3.6.x.  Hopefully that this could be updated. Thanks in advance.

**Comment by rstub** [comment]
This is a known issue, c.f. #250

**Comment by hyqsumile** [comment]
Thanks! I will close this then.
