### ISSUE TITLE
Allow for user-specified RNG

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppArmadillo#279]
Through the [`arma_rng_alt` class](https://github.com/RcppCore/RcppArmadillo/blob/fd5c56d1c2a2fbd44790a3809aeee134d0f49818/inst/include/RcppArmadillo/Alt_R_RNG.h), `RcppArmadillo` inherits _R_'s RNG engine  and applies it to all `armadillo`'s random distribution functions, e.g. `arma::rand*()`. As a result, `armadillo`'s random distribution functions then have a single thread limitation that is inherited from _R_. This is problematic as the functions are then restricted to sequential applications instead of parallelized work.   As a result, this requires a rewrite of existing `armadillo` functionality since the `arma_rng_alt` class cannot be changed to use a thread-safe RNG engine and distribution functions. 

One way around this would be to offer a way to supply a custom RNG class that supports parallel operations. 

In particular, the following the should be changed: 

https://github.com/RcppCore/RcppArmadillo/blob/c9a1ddc2cc54fc72f8e79fea129eba3e040f1445/inst/include/RcppArmadilloForward.h#L41-L44

to:

```cpp
#ifndef ARMA_RNG_ALT
#define ARMA_RNG_ALT         RcppArmadillo/Alt_R_RNG.h
#endif
```

From there, an appropriate `#define ARMA_RNG_ALT` could be supplied as need by the downstream _R_ package.

**Comment by conradsnicta** [comment]
The `ARMA_RNG_ALT` approach is rather hacky, and is not meant to be used outside of the internals of Armadillo and RcppArmadillo. It was never designed to be user accessible.

Vanilla Armadillo already uses a thread-safe RNG in C++11 mode when installed via CMake. So an alternative approach for RcppArmadillo would to to enforce the requirement for C++11 and build the Armadillo run-time library.

**Comment by eddelbuettel** [comment]
It's complicated.  CRAN has a bunch of nice modern RNGs we might want to use.  But doing that cleanly at coding standards commensurate with the rest of Armadillo may not be obvious.  

Maybe the easiest is just to farm out to the candidate RNGs, fill or or more vectors and use the advanced zero copy constructors.

**Comment by eddelbuettel** [comment]
Closing as consensus with upstream that this may not be the best way to proceed.
