### ISSUE TITLE
Install error on macOS with clang7

### ISSUE THREAD

**Issue by pat-s** [RcppCore/RcppArmadillo#280]
macOS 10.14.6 

I've installed clang7 following #268. Any suggestions?

```
Error: package or namespace load failed for ‘RcppArmadillo’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/pjs/Library/R/3.6/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so':
  dlopen(/Users/pjs/Library/R/3.6/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so, 6): Symbol not found: _wrapper2_ddot_
  Referenced from: /Users/pjs/Library/R/3.6/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so
  Expected in: flat namespace
 in /Users/pjs/Library/R/3.6/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so
Error: loading failed
```

**Comment by eddelbuettel** [comment]
Which version? The "just published" CRAN version 0.9.800.3.0?  Or a different one?

`wrapper2` points to a Fortran macro [from this file](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/armadillo_bits/compiler_setup.hpp) -- can you poke a little?

/cc @conradsnicta

**Comment by conradsnicta** [comment]
@pat-s Uninstall the system level Armadillo, and then reinstall RcppArmadillo.  For more info see related issue: https://github.com/RcppCore/RcppArmadillo/issues/264

You do not need to install Armadillo in order to use RcppArmadillo.

**Comment by pat-s** [comment]
Thanks. Didn't find #264 when browsing the error message.

While this worked for me, I wonder if there is a better long-term approach to this. Didn't sound like there is such a solution in #264. 

Also this only applies when people install everything from source on macOS or if the binary is not yet built for a new release, so probably not that much of a pressing thing.
