### ISSUE TITLE
Inconsistency with element-wise extremum values when inputs have NA values

### ISSUE THREAD

**Issue by Eluvias** [RcppCore/RcppArmadillo#287]
Currently, `arma::min(X, Y)` is not equal to `arma::min(Y, X)` when `NA` values are present either in X or Y.  `arma::max(X, Y)` is not different.

``` r
library(Rcpp)

cppFunction('Rcpp::List test(arma::mat X, arma::mat Y) {

return List::create( _["arma_min_XY"] = arma::min(X, Y),
                     _["arma_min_YX"] = arma::min(Y, X),
                     _["arma_max_XY"] = arma::max(X, Y),
                     _["arma_max_YX"] = arma::max(Y, X));
                     
              }', depends = "RcppArmadillo")


X <- matrix(NA_real_, nrow = 2, ncol = 2)
Y <- matrix(1, nrow = 2, ncol = 2)

test(X, Y)
#> $arma_min_XY
#>      [,1] [,2]
#> [1,]   NA   NA
#> [2,]   NA   NA
#> 
#> $arma_min_YX
#>      [,1] [,2]
#> [1,]    1    1
#> [2,]    1    1
#> 
#> $arma_max_XY
#>      [,1] [,2]
#> [1,]   NA   NA
#> [2,]   NA   NA
#> 
#> $arma_max_YX
#>      [,1] [,2]
#> [1,]    1    1
#> [2,]    1    1
```

**Comment by eddelbuettel** [comment]
Does Conrad document these to be robust to NA? Don't extrapolate from R....

**Comment by Eluvias** [comment]
No, I don't extrapolate from R; the expectation was these to ignore `NA`s like `arma::min(X)/max(X)` .

Here:

``` r
library(Rcpp)

cppFunction('arma::mat arma_min(arma::mat X) {
return arma::min(X);
              }',     depends = "RcppArmadillo")

A <- matrix(c(1, NA_real_, NA_real_, 1), nrow = 2, ncol = 2)

arma_min(A)
#>      [,1] [,2]
#> [1,]    1    1
```

But the element wise versions don't ignore `NA`s  if the input passed on the first argument. 

There is no specific documention on how NAs are handled by these functions; only this : [Caveat: NaN is not equal to anything, even itself](http://arma.sourceforge.net/docs.html#has_nan);.

**Comment by eddelbuettel** [comment]
Fair enough.  Poking @conradsnicta ...

**Comment by conradsnicta** [comment]
In general, NaN in C++ doesn't indicate "missing data".  Armadillo doesn't have special handling for NaNs, apart from these functions:
  * [.replace()](http://arma.sourceforge.net/docs.html#replace)
  * [.has_nan()](http://arma.sourceforge.net/docs.html#has_nan)
  * [.is_finite()](http://arma.sourceforge.net/docs.html#is_finite)
  * [find_finite()](http://arma.sourceforge.net/docs.html#find_finite)
  * [find_nonfinite()](http://arma.sourceforge.net/docs.html#find_nonfinite)

If you have NaN in your data, the results from `arma::min(X, Y)` and other functions are dependent on the data (eg. ordering of the data, ordering of the arguments), the machine on which the code is running on, etc.

I suggest that any data with NaNs is first sanitised, possibly via [.replace()](http://arma.sourceforge.net/docs.html#replace).

**Comment by eddelbuettel** [comment]
@conradsnicta :  R users generally think about three non-finite values:  NA, NaN, and +/- Inf.  
NA indicates missingness.  It is different from NaN.  R reserves another bit pattern for it.  

@Eluvias : I should have picked up on that earlier.  You gotta be careful with R special values outside of R.  I may have some helper / tester scripts hanging around.   Also always try short snippets like this as `main()` standalone C++ programs away from R headers just for comparison.

**Comment by conradsnicta** [comment]
As far as I know, in C++ there is no standard way to describe "NA" (as opposed to NaN), where "NA" indicates "missing" or "not available".

Clearly it would be useful to have "NA", but that's beyond the scope of Armadillo, since it lives in C++ land.

**Comment by eddelbuettel** [comment]
Sorry, I get that wrong when I don't look it up for a while.  For `double` we have NA, NaN and Inf per IEEE. Quote from R's `Arith.h`.

```c++
/* implementation of these : ../../main/arithmetic.c */
LibExtern double R_NaN;		/* IEEE NaN */
LibExtern double R_PosInf;	/* IEEE Inf */
LibExtern double R_NegInf;	/* IEEE -Inf */
LibExtern double R_NaReal;	/* NA_REAL: IEEE */
LibExtern int	 R_NaInt;	/* NA_INTEGER:= INT_MIN currently */
```

What R does differently is to add some of these to `int` (and `bool` -- my favourite: R logicals have three values: TRUE, FALSE and NA).

Anyway, the following is from [`src/main/arithmetic.c`](https://github.com/wch/r-source/blob/trunk/src/main/arithmetic.c) and there is more -- this works quite well and is generally well respected -- data work profits from being able to declare missingness as well as 'bad number'.

```c
static double R_ValueOfNA(void)
{
    /* The gcc shipping with Fedora 9 gets this wrong without
     * the volatile declaration. Thanks to Marc Schwartz. */
    volatile ieee_double x;
    x.word[hw] = 0x7ff00000;
    x.word[lw] = 1954;
    return x.value;
}

int R_IsNA(double x)
{
    if (isnan(x)) {
	ieee_double y;
	y.value = x;
	return (y.word[lw] == 1954);
    }
    return 0;
}

int R_IsNaN(double x)
{
    if (isnan(x)) {
	ieee_double y;
	y.value = x;
	return (y.word[lw] != 1954);
    }
    return 0;
}

/* ISNAN uses isnan, which is undefined by C++ headers
   This workaround is called only when ISNAN() is used
   in a user code in a file with __cplusplus defined */

int R_isnancpp(double x)
{
   return (isnan(x)!=0);
}


/* Mainly for use in packages */
int R_finite(double x)
{
#ifdef HAVE_WORKING_ISFINITE
    return isfinite(x);
#else
    return (!isnan(x) & (x != R_PosInf) & (x != R_NegInf));
#endif
}

**Comment by eddelbuettel** [comment]
(But that is just FYI -- we still need to educate our users that not all R quirks carry over to non R code.)

**Comment by eddelbuettel** [comment]
I am going to close this as we all, I think, concluded that this works as specified.
