### ISSUE TITLE
Failed RcppArmadillo installation on AIX7.2

### ISSUE THREAD

**Issue by bergen288** [RcppCore/RcppArmadillo#300]
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server with no internet access. Below is my R CMD INSTALL statement and its error with RcppArmadillo package. Can someone please help me to figure out what's wrong?  
Thanks.
 
```r
R CMD INSTALL -l /software/R/site-library RcppArmadillo_0.9.880.1.0.tar.gz
* installing *source* package 'RcppArmadillo' ...
** package 'RcppArmadillo' successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -maix64 -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -maix64 -std=gnu++11 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -maix64 -std=gnu++11 accepts -g... (cached) yes
checking whether we have a suitable tempdir... /tmp
checking whether R CMD SHLIB can already compile programs using OpenMP... yes
checking LAPACK_LIBS... R-supplied partial LAPACK found
configure: WARNING: Some complex-valued LAPACK functions may not be available
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
make[1]: Entering directory '/tmp/RtmpyMrMia/R.INSTALL47025a7d055d27/RcppArmadillo/src'
g++ -maix64 -std=gnu++11 -I"/opt/freeware/lib64/R/include" -DNDEBUG  -I"/software/R/site-library/Rcpp/include" -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM -I../inst/include    -O2 -I/opt/freeware/include -I/usr/include -D_GETDELIM  -c RcppArmadillo.cpp -o RcppArmadillo.o
In file included from ../inst/include/armadillo:175,
                 from ../inst/include/RcppArmadilloForward.h:49,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo_bits/SpMat_bones.hpp:685:29: error: 'mutex' in namespace 'std' does not name a type
   arma_aligned mutable std::mutex cache_mutex;
                             ^~~~~
../inst/include/armadillo_bits/SpMat_bones.hpp:685:24: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
../inst/include/armadillo_bits/SpMat_bones.hpp:1:1:
+#include <mutex>
 // Copyright 2008-2016 Conrad Sanderson (http://conradsanderson.id.au)
../inst/include/armadillo_bits/SpMat_bones.hpp:685:24:
   arma_aligned mutable std::mutex cache_mutex;
                        ^~~
In file included from ../inst/include/armadillo:642,
                 from ../inst/include/RcppArmadilloForward.h:49,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo_bits/SpMat_meat.hpp: In member function 'void arma::SpMat<eT>::sync_cache() const':
../inst/include/armadillo_bits/SpMat_meat.hpp:6823:7: error: 'cache_mutex' was not declared in this scope
       cache_mutex.lock();
       ^~~~~~~~~~~
../inst/include/armadillo_bits/SpMat_meat.hpp: In member function 'void arma::SpMat<eT>::sync_csc() const':
../inst/include/armadillo_bits/SpMat_meat.hpp:6875:7: error: 'cache_mutex' was not declared in this scope
       cache_mutex.lock();
       ^~~~~~~~~~~
../inst/include/armadillo_bits/SpMat_meat.hpp: In instantiation of 'void arma::SpMat<eT>::init(const arma::SpMat<eT>&) [with eT = double]':
../inst/include/armadillo_bits/SpMat_meat.hpp:698:3:   required from 'arma::SpMat<eT>& arma::SpMat<eT>::operator=(const arma::SpMat<eT>&) [with eT = double]'
../inst/include/armadillo_bits/SpMat_meat.hpp:5844:5:   required from 'void arma::SpMat<eT>::steal_mem(arma::SpMat<eT>&) [with eT = double]'
../inst/include/armadillo_bits/SpMat_meat.hpp:251:13:   required from 'arma::SpMat<eT>::SpMat(arma::SpMat<eT>&&) [with eT = double]'
../inst/include/armadillo_bits/fn_speye.hpp:77:10:   required from here
../inst/include/armadillo_bits/SpMat_meat.hpp:5212:9: error: 'const class arma::SpMat<double>' has no member named 'cache_mutex'
       x.cache_mutex.lock();
       ~~^~~~~~~~~~~
../inst/include/armadillo_bits/SpMat_meat.hpp:5218:9: error: 'const class arma::SpMat<double>' has no member named 'cache_mutex'
       x.cache_mutex.unlock();
       ~~^~~~~~~~~~~
make[1]: *** [/opt/freeware/lib64/R/etc/Makeconf:177: RcppArmadillo.o] Error 1
make[1]: Leaving directory '/tmp/RtmpyMrMia/R.INSTALL47025a7d055d27/RcppArmadillo/src'
ERROR: compilation failed for package 'RcppArmadillo'
* removing '/software/R/site-library/RcppArmadillo'
make: *** [makefile:2: all] Error 1
```

**Comment by eddelbuettel** [comment]
What does `g++ --version` say?

**Comment by bergen288** [comment]
Both g++ and gcc are v8.3 on my AIX7.2.

```r
Login=xzhang: Line=36 > g++ --version
g++ (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by eddelbuettel** [comment]
That should be new enough. Not sure why it complains about `std::mutex`.

Can you, just for kicks, try some of the older releases from https://cran.r-project.org/src/contrib/Archive/RcppArmadillo/ to see when it may have broken?

**Comment by bergen288** [comment]
The installation of RcppArmadillo_0.9.870.2.0.tar.gz finished successfully.
Thanks.

**Comment by eddelbuettel** [comment]
So 0.9.880.1.0 introduced a regression?  We should look into that.  I am still not quite sure why.

**Comment by bergen288** [comment]
Actually, my installation with forecast package failed due to errors related with RcppArmadillo.  See my issue posted here: https://github.com/robjhyndman/forecast/issues/852.  Do you mind to take a look as well?
Thanks.

**Comment by conradsnicta** [comment]
@bergen288 It seems your system doesn't support `std::mutex` from C++11. It's also possible there is interference between RcppArmadillo and a system level installation of Armadillo.

I suggest to define `ARMA_DONT_USE_CXX11_MUTEX` before including the RcppArmadillo header.  Example:

    #define ARMA_DONT_USE_CXX11_MUTEX
    #include "RcppArmadillo.h"

Also, make sure there is only either Armadillo or RcppArmadillo installed, not both.  It's possible they are interfereing with each other.  For example, your system level Armadillo might be older than the Armadillo embedded into RcppArmadillo.

**Comment by bergen288** [comment]
Not sure who closed my ticket.  Anyway, can you tell me which file to define **ARMA_DONT_USE_CXX11_MUTEX**?

**Comment by eddelbuettel** [comment]
Apparently you did (likely by accident):  

![image](https://user-images.githubusercontent.com/673121/82947372-8fb8fd00-9f65-11ea-9361-04a854986cef.png)

You would make the change in the source file(s) of package `forecast` in the lines before `#include "RcppArmadillo.h"` (or maybe `#include <RcppArmadillo.h>`).

**Comment by bergen288** [comment]
I have a script to scan the whole directory and its sub-directories  for RcppArmadillo.h after unzip/untar forecast_8.12.tar.gz file.  There is only one file (calcBATS.h) found with RcppArmadillo.h
```r
The target text file name is 'calcBATS.h' in '/software/R/pkg-source-files/forecast/src'
*** There are 1 target string(s) found ! ***
#include <RcppArmadillo.h>
```
Now I added "ARMA_DONT_USE_CXX11_MUTEX".  But my forecast installation still failed with the same MUTEX errors.
```r
#define ARMA_DONT_USE_CXX11_MUTEX
#include <RcppArmadillo.h>
#include <cmath>
```

**Comment by conradsnicta** [comment]
@bergen288 Did you also check places like `/usr/include` and `/usr/local/include` ?

You mentioned that you're using a "server with no internet access".  How did you install RcppArmadillo then?

**Comment by eddelbuettel** [comment]
@conradsnicta R should order that correctly, I never had issues and I usually have the distro-provided (slightly older) armadillo around.  Never was an issue.

**Comment by bergen288** [comment]
eddelbuettel: 

My mutex issue with R forecast package is still outstanding.  Per your suggestion, I installed the old version of RcppArmadillo_0.9.870.2.0.  Now I would like to install RcppArmadillo_0.9.880.1.0 with "ARMA_DONT_USE_CXX11_MUTEX".  But I can see lots of  #include <RcppArmadillo.h> in the package.   Do I have to put #define ARMA_DONT_USE_CXX11_MUTEX before all #include <RcppArmadillo.h>?

Thanks.

**Comment by eddelbuettel** [comment]
>  But I can see lots of #include <RcppArmadillo.h> in the package.

Which package?  `forecast` ?  Maybe.

Alternatively you can try to live off a local fork and define `"ARMA_DONT_USE_CXX11_MUTEX"` in
the top-most include file of the RcppArmadillo package.  And/or in  your ~/.R/Makefile so it is used by each compilation you make (but possibly not your colleagues, if any).  

Fundamentally we still need to figure out why your installation does not support `std::mutex`.

(And my name is 'Dirk' if you need to holler across in an issue thread apparently only you, Conrad and I read...)

**Comment by bergen288** [comment]
Dirk:

Sorry to call you wrong name.  To my understanding, anything start with # is a comment in Makefile.  Should I define it like below?  May I define it in RcppArmadillo.cpp file inside /software/R/pkg-source-files/RcppArmadillo/src?
```r
define ARMA_DONT_USE_CXX11_MUTEX  
```

**Comment by eddelbuettel** [comment]
In `~/.R/Makevars` you would something like this:

```
CXXFLAGS=            	-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -march=native -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION
CXX11FLAGS=		-g -O3 -Wall -pipe -Wno-unused $(PEDANTIC) -march=native -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION
```

which adds a specific Boost directive.  You would add `-DARMA_DONT_USE_CXX11_MUTEX`.

In a source file you add the `#define` directly as I presume you know.
```

**Comment by bergen288** [comment]
Dirk:

"-DARMA_DONT_USE_CXX11_MUTEX" is appended at the end of CXXFLAGS and CXX11FLAGS in R/etc/Makeconf file.  My new installations of RcppArmadillo version 0.9.880.1.0  and forecast packages are finished successfully.

Thanks a lot for your help.

**Comment by eddelbuettel** [comment]
My pleasure!  Glad to know it works now.

I still would like to know why/how we need it and how we could possibly make this automagic.  Conrad is very diligent about these matters and will surely default the flag to false where needed---but we need a trigger, and I don't think we have one yet.

**Comment by kevinushey** [comment]
Given the include paths:

```
-I"/opt/freeware/lib64/R/include"
-I"/software/R/site-library/Rcpp/include"
-I/opt/freeware/include
-I/usr/include
-I../inst/include
-I/opt/freeware/include
-I/usr/include
```

I'd wager that there's something in `-I/opt/freeware/include` that's interfering or conflicting with the "default" C++ headers.
