### ISSUE TITLE
Package Doesn't Install on Solaris 11.4

### ISSUE THREAD

**Issue by alexswanson8** [RcppCore/RcppArmadillo#306]
I'm getting errors as follows, any suggestions?

** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘RcppArmadillo’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/root/software/R-3.6.3/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so':
  ld.so.1: R: relocation error: file /root/software/R-3.6.3/library/00LOCK-RcppArmadillo/00new/RcppArmadillo/libs/RcppArmadillo.so: symbol strtrs_: referenced symbol not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/root/software/R-3.6.3/library/RcppArmadillo’
Warning message:
In install.packages("/root/software/R_Packages/Forecast_Group/RcppArmadillo_0.9.900.2.0.tar.gz") :
  installation of package ‘/root/software/R_Packages/Forecast_Group/RcppArmadillo_0.9.900.2.0.tar.gz’ had non-zero exit status

**Comment by kevinushey** [comment]
Is installing Linux an option? :-)

In all seriousness, from what I understand `strtrs_` is a symbol provided by LAPACK:

https://www.netlib.org/lapack/explore-html/d1/df5/group__real_o_t_h_e_rcomputational_ga39f1accd4c0ff41b0ae185c173044601.html

so perhaps the version of LAPACK on your machine is too old or doesn't have this available?

**Comment by alexswanson8** [comment]
Sadly it's SPARC hardware and the only version of Linux I have for SPARC is so old that I'm keeping it in its shrinkwrap as an investment for my retirement.

It's a vanilla install so I'd guess LAPACK is not there. Thanks for the tip, I'll look into trying to find and install it.

**Comment by eddelbuettel** [comment]
Is this a first attempt, or did you have RcppArmadillo built earlier?  Kevin was eagle-eyed and this is LAPACK, but LAPACK changes it coverage close to "never" -- it is decades old and stable.  So maybe we "simply" not getting LAPACK from R, and (and we had this issue earlier with some rarely used complex math) maybe you are using LAPACK from R (whereas most of use shared library builds and LAPACK comes from the external one.)

Look at `sessionInfo()`. I have

```
Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3
```

If you have a capital R in there you use R's.

**Comment by alexswanson8** [comment]
This is a vanilla install starting from bare metal literally less than 48 hours before and using downloads from CRAN done this weekend. The main point of the exercise is in fact to go through the process, establish the procedure, and demonstrate it working. So far as I can tell from online searching, LAPACK ought to be there from OS packages.

**Comment by eddelbuettel** [comment]
Let's not waste time. I asked you to run the command

```
sessionInfo()
``` 

in R.  Can you please do that?

**Comment by alexswanson8** [comment]
My apologies, I didn't understand that that's what you meant. Unfortunately the server is shut down at the moment to save power. I'll run it as soon as I can and get back to you.

**Comment by alexswanson8** [comment]
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: sparc-sun-solaris2.11 (32-bit)
Running under: Solaris 11

Matrix products: default
BLAS:   /root/software/R-3.6.3/lib/libRblas.so
LAPACK: /root/software/R-3.6.3/lib/libRlapack.so

locale:
[1] /en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3
>

**Comment by eddelbuettel** [comment]
As predicted, you have R's builtin BLAS.  To use RcppArmadillo you need to build R and use an external (and complete) BLAS and LAPACK pair.  If that is too difficult try installing earlier RcppArmadillo version which you can get too via the Archive/ link of the package page at every CRAN mirror.

"Not really an RcppArmadillo bug" so closing this here.

**Comment by eddelbuettel** [comment]
Also, it's not exactly a new problem as R always had its embedded LAPACK which is e.g. the only used on Windows so you could look at years of discussion here or on the Rcpp-devel list.

On possible fix for you is to define `ARMA_CRIPPLED_LAPACK` (@conradsnicta tends to not mince words ...) before including the RcppArmadillo header, i.e. for example in your `Renviron.site` or your local `~/.Renviron`.  That way Armadillo will restrict itself to fewer functions, possibly at the loss of precision, power, speed, ....  But it may build.

**Comment by alexswanson8** [comment]
Thank you

**Comment by eddelbuettel** [comment]
No worries. I wish this was simpler.  We have tested for this in a million ways over the years...

@kevinushey I was just thinking if we should borrow a page from your simple 'does it OpenMP' tests for data.table and others and just do an immediate compilation attempt of something in full LAPACK/BLAS but in the restricted.  Looks like we were just handed a candidate symbol.   We could then bifurcate to a) trying again with a mainstream symbol such as `dgemm` under `ARMA_CRIPPLED_LAPACK` set and continue or b) cry and abort.  Thoughts?

**Comment by alexswanson8** [comment]
OK tried a couple of things
Complete rebuild with  configure --with-blas --with-lapack       does not work

Adding ARMA_CRIPPLED_LAPACK to .Renviron doesn't work unless I misunderstood

root@belrow91:~/software/R-3.6.3# cat ~/.Renviron
ARMA_CRIPPLED_LAPACK=true
root@belrow91:~/software/R-3.6.3#

**Comment by alexswanson8** [comment]
Apologies for strikethrough, seems to be formatting misunderstanding  ~

**Comment by eddelbuettel** [comment]
Sorry -- I was rushing there.  It will not work as an environment variable.  It's a define for the compiler. Silly me.

You can either
- open the tar.gz and hand-edit it to src/Makevars.in
- or hand-edit the top-level header file, or hardwire it in RcppArmadilloConfig.h (or RcppArmadilloConfigGenerated.h.in)
- or, better, edit your ~/.R/Makevars and edit to the proper CXX_FLAGS, likely CXX11FLAGS.

You need to "see it" when the package compile. We want a -DARMA_CRIPPLED_LAPACK on that line.  (Unless you have it in the header.)

**Comment by alexswanson8** [comment]
Hardwiring it in RcppArmadilloConfig.h seems to make no difference

**Comment by alexswanson8** [comment]
I'll have anther go at a rebuild, I've found the online advice for doing this for Solaris, leave it with me

**Comment by conradsnicta** [comment]
@alexswanson8  `strtrs_` is for single-precision floating point elements. R only supports double precision.  R provides something resembling BLAS and LAPACK, which supports a limited set of functions from standard BLAS and LAPACK.

R developers insist on shipping these "versions" of BLAS and LAPACK instead of simply packaging standard versions. This has been a recurring issue for many years, and they don't want to fix it.  The underlying reasoning does not entirely hold water, and in the end creates more work (and headaches) than necessary for everybody.

**Comment by eddelbuettel** [comment]
Oh @conradsnicta we have been over this a few times, but your tone does not help and is, frankly, inappropriate. Please edit the post.

**Comment by eddelbuettel** [comment]
@alexswanson8 If Solaris gives you prebuilt BLAS and LAPACK it should just be a matter of setting `configure` arguments. On Linux I just say `--with-blas --with-lapack` and R's configure does the rest.  If Solaris does not give you prebuilt ones then you of course have more work to do.  We had RcppArmadillo on CRAN for over a decade.  As I mentioned earlier, a *much simpler* quick test for you would be to try an older version first.  

The [R Installation and Administration](https://cran.r-project.org/doc/manuals/r-release/R-admin.html) has more on BLAS/LAPACK as well as a platfor-specific appendix which appears to have a Solaris section.

**Comment by alexswanson8** [comment]
I've tried --with-blas --with-lapack and got the same result. I found the recommended options for Solaris which are --with-blas='-library=sunperf' --with-lapack   but then make fails with
Warning in solve.default(rgb) :
  unable to load shared object '/root/software/R-3.6.3/modules//lapack.so':
  ld.so.1: R: relocation error: file /root/software/R-3.6.3/modules//lapack.so: symbol __z_abs: referenced symbol not found
Error in solve.default(rgb) : LAPACK routines cannot be loaded
Error: unable to load R code in package 'grDevices'
Execution halted

I found a note to the effect that I needed to set a particular cc compiler flag -dalign and I did that but it made no difference.

I did try an older version of Armadillo which I had from last year, but that won't install either, it gave a different error message to do with a null in a string. Recommend a particular version and I will happily try.

**Comment by eddelbuettel** [comment]
Sorry but you're on your own there.  R has support groups for using it on macOS, debian, fedora, windows.  But nothing for you.  

Guess you have to either fight it out or move on.  Which is probably what I would do.

**Comment by alexswanson8** [comment]
OK, thanks for helping anyway

**Comment by eddelbuettel** [comment]
It does point to a wart on our end in the 'should detect incomplete LAPACK/BLAS and deal more gracefully with it' which we already spent _quite_ some time on over the years.  Alas...

The good news is that it works on all other more reasonably equipped systems, and also on Windows.

**Comment by alexswanson8** [comment]
It runs out that there is a specific option to the Solaris C compiler "-library=sunperf" but even though I've set it in config.site, the module compile doesn't seem to use it, is there somewhere else I can put it?

**Comment by kevinushey** [comment]
I think a better forum for this sort of question might ultimately be the R-devel mailing list. (One member of R Core has experience configuring R on Solaris machines and may be able to give better help than we are able to offer)

**Comment by alexswanson8** [comment]
Ok will do, thanks again
