### ISSUE TITLE
In-place operations not preserved across packages 

### ISSUE THREAD

**Issue by NeferkareII** [RcppCore/RcppArmadillo#308]
As per the discussion [here](https://stackoverflow.com/questions/63449319/how-to-make-a-c-function-that-performs-an-in-place-operation-available-to-anot/63449820?noredirect=1#comment112202451_63449820), I'm aware this isn't a promised feature, but I still found it interesting and somewhat unexpected. 

Say I have an R package called "packA" that contains the following file "funcA.cpp":

```
// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::interfaces(r, cpp)]]
#include <RcppArmadillo.h>
using namespace Rcpp;

// [[Rcpp::export]]
void funcA (arma::vec& x) {
  x += 1;
}
```
Calling this function from R yields the expected result of adding 1 to each element of the vector in-place:
```
> vec <- c(1, 2, 3)
> funcA(vec)
> vec
[1] 2 3 4
```
Now say I have a second package "packB" that wants to call the function "funcA". It contains the following file called "funcB.cpp":
``` 
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>
#include <packA.h>
using namespace Rcpp;

// [[Rcpp::export]]
void funcB(arma::vec& y) {
  packA::funcA(y);
}
 ``` 
Calling this function no longer yields the desired result, as it would appear that the vector x is no longer modified in-place:
``` 
> vec <- c(1, 2, 3)
> funcB(vec)
> vec
[1] 1 2 3 
``` 

I tested it with Rcpp::Numericvector and there in-place operations seem to be preserved - similarly if you pass an Rcpp::Numericvector and then use the advanced constructor to create an arma::vec that shares the same underlying memory. 

I attached the two packages from the example above that recreate this behavior in a minimal fashion. 
[packages.zip](https://github.com/RcppCore/RcppArmadillo/files/5129866/packages.zip)

**Comment by eddelbuettel** [comment]
Let's not randomly cross-post issues from StackOverflow please.  I spend enough time over there trying to clear up confusion.

**Comment by NeferkareII** [comment]
Ah, sorry, just wanted to follow your suggestion and report it. Where would the correct place to do so have been?

**Comment by eddelbuettel** [comment]
For starters it is not a bug report but mostly a recitation of the StackOverflow issue.  

Also, you are apprently unware that there is a formal protocol to call functions from other package.  See Writing R Extensions for the details, we also have examples with Rcpp between xts and RcppXts and there are more.
