### ISSUE TITLE
Support for wrapping single precision matrices from float pkg

### ISSUE THREAD

**Issue by dselivanov** [RcppCore/RcppArmadillo#318]
It would be nice to include support of automatic conversion of single precision float matrices and vectors from https://github.com/wrathematics/float/ pkg into `arma::fmat`.  Right now I use following code to construct arma matrices from R's float matrices:

```cpp
arma::fmat extract_float_matrix(Rcpp::S4 x) {
  Rcpp::IntegerMatrix x_data = x.slot("Data");
  float *ptr = reinterpret_cast<float *>(&x_data[0]);
  arma::fmat x_mapped = arma::fmat(ptr, x_data.nrow(), x_data.ncol(), false, true);
  return (x_mapped);
}

arma::fvec extract_float_vector(Rcpp::S4 x) {
  Rcpp::IntegerVector x_data = x.slot("Data");
  float *ptr = reinterpret_cast<float *>(&x_data[0]);
  arma::fvec x_mapped = arma::fvec(ptr, x_data.length(), false, true);
  return (x_mapped);
}
```

I can try to work on this (without committing a deadline). I need some hints on how it is done with normal R matrices (in order to figure out which bits I need to implement).

**Comment by eddelbuettel** [comment]
In principle, yes.  In practice, less sure how well or smooth we can do it.  Most dispatching is done on the `SEXP` type but that does not work for "sneaked-in" types like `int64` (using the `bit64` package) or your `float`.  I am not sure how to do this 'well' yet have been been thinking about the `int64` case a bit for integration into `Rcpp` for both for large integer use and the `nanotime` use based on it.

But at a minimum we can probably add helper functions such as the above.

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up from either side.  Open to testing PR candidates for mapper functions but as R has no native `float`, not a big priority for me at this point.
