### ISSUE TITLE
Code will not compile using vecLib BLAS on macOS

### ISSUE THREAD

**Issue by dwachsmuth** [RcppCore/RcppArmadillo#348]
I've been trying to use RcppArmadillo for some heavy linear algebra, and was unable to get any of my code to compile on macOS (Big Sur, Intel), despite following @coatless 's guide. After some trial and error, I've narrowed the issue down to the Apple vecLib BLAS library.

With a fresh install of R 4.1.1, the following in a .cpp file compiles fine with `sourceCpp`:

```
#include <RcppArmadillo.h>   
// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
void hello_world() {
  Rcpp::Rcout << "Hello World!" << std::endl;  
}
```

But once I link R to Apple's (dramatically faster than reference BLAS) vecLib BLAS and LAPACK libraries (using the replacing-symlink method which used to be part of the R for macOS FAQ - https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html - although now seems to have vanished), the same .cpp  file now fails to compile:

```
> sourceCpp("src/test.cpp")
ld: library not found for -lRlapack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_4.so] Error 1
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include   -I"/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include" -I"/Users/dwachsmuth/Code/matchr/src" -I"/Users/dwachsmuth/Code/matchr/src/../inst/include" -I/usr/local/include -Xclang -fopenmp   -fPIC  -Wall -g -O2  -c test.cpp -o test.o
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -lomp -o sourceCpp_4.so test.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
Error in sourceCpp("src/test.cpp") : 
  Error 1 occurred building shared library.
```

My guess is it is possible to redirect the compiler to the vecLib BLAS and LAPACK libraries, but I couldn't find any information about how to do this.

Thanks in advance!

**Comment by eddelbuettel** [comment]
1. Your language is a little ambiguous, you talk about "compiling" but I believe you have a linker problem.
2. The `library not found for -lRlapack` is a tell: your R installation is *not* set up for shared libraries so you cannot mix and match those very shared libraries supplying BLAS and LAPACK.  Start there.
3. There is exactly zero we can do for you here.  RcppArmadillo is a standard R / CRAN package _and farms all of its build handling_ out to R itself.  So I suggest we close this and you try your luck over at r-sig-mac.

**Comment by dwachsmuth** [comment]
Thanks for the very speedy reply. AFAIK, the R CRAN binaries for macOS ship with both the reference BLAS and the Apple vecLib BLAS, and use a symlink to decide which is loaded, hence the official guidance about changing that symlink to change which BLAS R uses. My (admittedly completely under informed) suspicion was that perhaps something in the Rcpp compile/linking process is hard-coded to look for the reference BLAS rather than the (AFAIK standard for macOS R) symlink.

But if you think this is more of an r-sig-mac question, I'm happy to redirect.

**Comment by eddelbuettel** [comment]
(And I am not trying to be curt or mean -- but if you already digested the @coatless material I really have nothing else as a non-macOS user.  Truly sorry.)

**Comment by eddelbuettel** [comment]
>  R CRAN binaries for macOS ship with both the reference BLAS and the Apple vecLib

I honestly did not even know that.

>  is hard-coded to look for the reference BLAS

Not at all.  But we, in essence, just call `R CMD COMPILE` and `R CMD SHLIB` and ... just as you would on the command-line, and then get answers back from R just as you would there.  Packages cannot alter that.  

Cheers to McGill.  My former advisor is a CRC over in another dept.

**Comment by dwachsmuth** [comment]
Ok thanks very much for the clarification—I'll keep poking around! (And re: McGill, it's a small world!)
