### ISSUE TITLE
Loss of dim 2 when using field as input

### ISSUE THREAD

**Issue by BerriJ** [RcppCore/RcppArmadillo#351]
HI,

consider these 2 functions:

```
#include <RcppArmadillo.h>
using namespace arma;

// [[Rcpp::export]]
field<mat> fieldtest1()
{
    field<mat> out(5, 6);

    return out;
}

// [[Rcpp::export]]
field<mat> fieldtest2(field<mat> x)
{
    return x;
}
```

Now consider this R code:

```
[R] field <- fieldtest1() 
    dim(field) 
[1] 5 6
[R] field2 <- fieldtest2(field) 
    dim(field2)                                                       
[1] 30  1
```

`fieldtest1` returns a nested list with dimensions 5,6 as expected. But `fieldtest2` just imports and exports the field drop dimension 2 and returns a 30,1 list. 

This Issue may be related to https://github.com/RcppCore/RcppArmadillo/issues/263.

**Comment by eddelbuettel** [comment]
Thanks -- and I also think there is little new here that we didn't already have in #263.   It would appear few people work with `fields` as a data structure so it isn't biting too many people.  If it bites you and you have a moment or two I'd be happy to guide you through trying to write a PR that may fix things.  (Usual caveat that we then still have to see if it upsets existing packages, but in this case the chances may be good...)

**Comment by BerriJ** [comment]
I'm happy to write a PR for this. Do you have an idea how to fix this or can you direct me to the relevant files of RcpArmadillo?

**Comment by eddelbuettel** [comment]
Yes. This should in the files in `inst/include/Rcpp*` which cover the `as<>` and `wrap()` converters.  There is a `FieldImporter` in `RcppArmadilloWrap.h`.  And `RcppArmadilloAs.h` also has a bit.  Maybe you can start and poke and print some diagnostics and what came in and how.  It's been on my TODO list for years but as I have zero code using `arma::field` ...

**Comment by eddelbuettel** [comment]
BTW there is a branch new branch for Armadillo 10.7.2 which is currently being bulk-tested on the 900+ reverse depends.  May as well fork off that, or wait, or maybe just rebase again later...

**Comment by BerriJ** [comment]
Currently, I do only see master [here](https://github.com/RcppCore/RcppArmadillo/branches). However, rebasing will be no problem before I send a PR.

**Comment by eddelbuettel** [comment]
Ah yes you are correct -- I didn't push as tjis is so small.  The delta will be tiny, three upstream header files plus ChangeLog, NEWS, DESCRIPTION.  If you stay out of those three we'll be good with a rebase in a day or so.

**Comment by BerriJ** [comment]
I fiddled around with it and I identified the problem. However, my proposed fix only works for 1d and 2d arrays. Generalizing the approach to 3d seems easy but somehow throws a runtime error, details are in https://github.com/RcppCore/RcppArmadillo/pull/352.

I also discovered a Problem with passing 3d fields from C++ to R (so the opposite way). More on that also in https://github.com/RcppCore/RcppArmadillo/pull/352.

**Comment by BerriJ** [comment]
Sorry to bother you again but I have a small question. Say I have a package with several .cpp and .h files. Is there a place I can put the new #define so that it applies globally?

**Comment by eddelbuettel** [comment]
One way is in `src/Makevars*` via a `-DFOO=bar` which is equivalent to `#define FOO bar`.  Otherwise _you_ control your package; what is commonly done is to declare a header named as the package and `#include` that in packages that use it.  Just like `Rcpp.h` or `RcppArmadillo.h` then pull in their respective `config.h`.

Those questions are great, and we all are happy to help, but can you please bring them to the rcpp-devel list rather than burying them here?  Thank you, and _Frohes Fest!_.

**Comment by BerriJ** [comment]
Thank you very much. I'll do so in the future, I promise. Frohes Fest! :)
