### ISSUE TITLE
Additional tests for fields

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#355]
Following #352 I started to add a unit test file in C++ (and a caller in R) for fields.  This could (and should) get expanded.  My plan so far is to have test for both import (none so far) and exports (started).

If I could twist your arm @BerriJ to maybe contribute a few for where you did saw the failures pre-PR ?   We can possiblty do an `expect_error()` around it. 

This can also serve as extra documentation as it shows the usage.

**Comment by eddelbuettel** [comment]
I took another look, and I think I understand better what is happening.  While Armadillo allow 1d, 2d, and 3d Field creators:

![image](https://user-images.githubusercontent.com/673121/141661637-00a689af-c0c8-4a64-a546-e0a45fa14237.png)

these are in fact always represented in '3d' _i.e._ attributes rows, cols, slices are present.

![image](https://user-images.githubusercontent.com/673121/141661646-99d48284-7236-4f8a-bc40-33fb88e78518.png)

In the corner cases of an `F(1)`, all three are of values 1, and `n_elem` is also one.  So yep what the PR does is correct: setting up a 3d `dim` objects with <rows, cols, slizes> is exactly what we wanted.   And which the old code gets wrong.

This is now documented in new unit test code (for both without (_i.e._ default "old" behaviour) and with (_i.e._ "new" behaviour).

I will try to complement the unit test files with some for the opposite direction, _i.e._ R to C++.

**Comment by BerriJ** [comment]
Yes, they always have rows, cols, and slices. This is somewhat confusing.

I'll have a look into it and I'm happy to add some tests. Probably around mid-next week.

**Comment by eddelbuettel** [comment]
I now added a complete (if hard to read) set. It demonstrates where the old (current) code is wrong or difficient -- now tests have comments or are commented out -- and the new tests show that everything is as expected. 

Nice work, again, in your PR.  We'll work on transitioning to making it the default "eventually".
