### ISSUE TITLE
sparse matrix solver

### ISSUE THREAD

**Issue by YinLiLin** [RcppCore/RcppArmadillo#372]
Hi,

I found that only SuperLU was achieved in armadillo, I am just wandering if it is possible to implement Cholesky, LU decomposition or conjugate gradient algorithm on sparse matrix solver? like Eigen::SimplicialLDLT<>, Eigen::ConjugateGradient<> in Eigen.

Thank you.

**Comment by eddelbuettel** [comment]
Please check the old issues, there are (if memory serves) some technical details which require linking which the `RcppArmadillo` packages does _not_ do by default (and choice).

We do not have good reference documentation on this though.  Help on that front would be appreciated.

**Comment by YinLiLin** [comment]
Many thanks for the quick reply. I tried to find out the answer from the old issues, but haven't got it by now, may i please ask for the link you mentioned, or (if possible) other useful guidance for this issue?

**Comment by eddelbuettel** [comment]
Have you found for example [this Rcpp Gallery on linking with SuperLU](https://gallery.rcpp.org/articles/armadillo-with-superlu/) yet?

**Comment by YinLiLin** [comment]
Yes, I have successfully achieved it with this instruction, however, i am planning to make comparisons of the efficiency for different algorithms, e.g. SuperLU, Chol, LU, CG. My program was written on the basis of RcppArmadillo, i have no idea how to implement Chol, LU decomposition on sparse matrix solver by RcppArmadillo.

**Comment by eddelbuettel** [comment]
I think we can and should close this. You assumed there would be other (sparse) solvers you could just use, and there aren't.  RcppArmadillo also does not claim that there are any.

**Comment by YinLiLin** [comment]
Get it. Thank you for the discussion.

**Comment by eddelbuettel** [comment]
One thing that may be worth exploring if one or more of the other sparse matrix package already have code for this -- [spam64](https://cran.r-project.org/package=spam64).  We could possibly talk to them and have the C access points exported to have something callable without having to deal with the library issues.  It's just a thought but if you have some time poke -- it's a long shot but maybe this gives a feasible route to extend RcppArmadillo.

**Comment by YinLiLin** [comment]
Many thanks! It seems very helpful for my situation, I will have a try.

**Comment by eddelbuettel** [comment]
Might be nice to build 'bridges' i.e. simple converters.  We could start with something at the Rcpp Gallery ...  Just a thought.
