### ISSUE TITLE
Random seeding for chi2rnd doesn't work cross-platform

### ISSUE THREAD

**Issue by daeyounglim** [RcppCore/RcppArmadillo#373]
I've been using RcppArmadillo's Wishart random sampler for my package and found out that the output isn't reproducible. I've been informed that RcppArmadillo in recent updates has been modified to use R's RNG by default, which to a large extent is true—`randn` and `randu` work fine. However, `set.seed` seems to bypass armadillo's samplers that rely on `chi2rnd`.

I've run the following code `test.cpp` on macOS Monterey 12.3.1 and Debian 4.19.160-2 with RcppArmadillo version 0.11.0.0.0:

```cpp
#include <cmath>
#include <RcppArmadillo.h>
#include <Rmath.h>
#include <Rdefines.h>
// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
arma::mat test(int &n) {
    double df = 10.0;
    return arma::chi2rnd(df, 3, 3);
}
```

On my Mac,
```r
library(Rcpp)
library(RcppArmadillo)
sourceCpp("test.cpp")
set.seed(1111)
test(3)
```
yields
```r
           [,1]     [,2]      [,3]
[1,]   5.887224 17.05700 13.624775
[2,]  17.508067 13.30482  8.697143
[3,]   8.741382 12.24704 13.127976
```
whereas Debian yields
```r
         [,1]      [,2]      [,3]
[1,] 8.799888  2.989588 10.063611
[2,] 6.388290 17.797957 10.254374
[3,] 6.100068 10.639533  7.728846
```

Considering `set.seed` does produce the same random number sequence when restricted to one operating system, it seems like R's seeding is working, but the algorithm is OS-dependent? Am I understanding this correctly?

**Comment by eddelbuettel** [comment]
I think you got pretty close to the core of the matter:  for uniform and normal we do indeed let Armadillo use the R RNGs (of known and trusted quality) which makes life easier for seeding etc.

For other generators, other seeds may be used.  You appear to be using a different one.  

What I would do here is to probably set up a similar five or ten standalone C++ program with Armadillo and see how it behaves on different platforms as you appear to have access to different platforms, and concerns about behavior there.

**Comment by eddelbuettel** [comment]
Also:

> To change the RNG seed, use arma_rng::set_seed(value) or arma_rng::set_seed_random() functions

As we are on the same page that this likely uses the Armadillo RNGs, you need to use the Armadillo seeding functions.

**Comment by daeyounglim** [comment]
Thank you for the confirmation. I'll close this issue.

**Comment by eddelbuettel** [comment]
Sounds good.  I won't have time to take a close look but if you can think of ways to connect this back to R's RNGs it may be worth doing.  I also haven't looked but I think for other distributions R uses a standard scheme of drawing a U on the [0,1] interval and reverting out the draw based on the cumulative distribution function which can be inverted.  But it's been a while since I looked at this.
