### ISSUE TITLE
Possible error in fastLm documentation

### ISSUE THREAD

**Issue by pierucci** [RcppCore/RcppArmadillo#39]
Hi,

The documentation for the RcppArmadillo fastLm states :

## Value
fastLmPure returns a list with three components:
### coefficients
a vector of coefficients
### stderr
a vector of the (estimated) standard errors of the coefficient estimates
### df.residual
a scalar denoting the degrees of freedom in the model

While fastLmPure actually returns `coefficients` and `stderr` in one-column matrix objects:
```
flm <- fastLmPure( cbind(1, log(trees$Girth)), log(trees$Volume) )
print(flm)
$coefficients
          [,1]
[1,] -2.353325
[2,]  2.199970

$stderr
           [,1]
[1,] 0.23066284
[2,] 0.08983455

$df.residual
[1] 29
```

**Comment by eddelbuettel** [comment]
Yeah, sure, that is a design feature|bug|whatever from the very beginning in RcppArmadillo -- we return one-column matrices for _all_ vectors you create  in RcppArmadillo.
