### ISSUE TITLE
Is `ARMA_64BIT_WORD` supported in RcppArmadillo?

### ISSUE THREAD

**Issue by mattfidler** [RcppCore/RcppArmadillo#398]
I was wondering if `ARMA_64BIT_WORD` is supported in RcppArmadillo.

The reason I ask is because of the Armadillo Documentation note that I pointed out here:

https://github.com/nlmixr2/nlmixr2/issues/63#issuecomment-1295692802

In this case, I have 2 very large matrices (for a specific problem) that then finally reduce to the diagonal that would be under the size needed for `ARMA_64BIT_WORD`

The large matrices are here:

https://github.com/nlmixr2/nlmixr2est/blob/7237ac1c54a176e766b9290e70b4d23b3acef2af/src/cwres.cpp#L158-L159

And the reduction is the next line:

https://github.com/nlmixr2/nlmixr2est/blob/7237ac1c54a176e766b9290e70b4d23b3acef2af/src/cwres.cpp#L158-L159

I cant simply use:

```c++
(fppm2 * omegaMat * fppm2.t()).diag()
```

Because the template fails.

**Comment by eddelbuettel** [comment]
I think it's been the default for years:

https://github.com/RcppCore/RcppArmadillo/blob/1a0174a3ff5ee22b8aaa689dac4068b9d34603bf/inst/include/RcppArmadillo/config/RcppArmadilloConfig.h#L123-L129

Can you try a five-liner in just C++ with only Armadillo to then see if it then breaks under RcppArmadillo?  It shouldn't -- but one never know and, as they say, the proof of the pudding is in the eating.

**Comment by mattfidler** [comment]
Thanks, I will try again;

Apparently it has worked since 2016 there must be something else wrong with the code.

(https://stackoverflow.com/questions/40592054/large-matrices-in-rcpparmadillo-via-the-arma-64bit-word-define)

**Comment by eddelbuettel** [comment]
Yep, we had that define for a loooong time. If memory serves it needed C++11 support which we had for years too.

I would try a simple `main()` around a few lines of just C++ to try.

**Comment by mattfidler** [comment]
I tried in my package.  It was failing because I had to be more explicit in types.  So it works for me.

Thanks for indulging the chatter
