### ISSUE TITLE
NaN output from arma::uvec compared to arma::vec

### ISSUE THREAD

**Issue by mlampros** [RcppCore/RcppArmadillo#399]
First of all thank you for making Armadillo and RcppArmadillo publicly available.

In one of my RcppArmadillo code snippets I faced an issue related to NaN values. Specifically the `.fill(arma::datum::nan)` expression does not return the same output for `arma::uvec` and `arma::vec`. The following sample code (ran on Linux Mint) shows the difference:

```cpp

# include <RcppArmadillo.h>
// [[Rcpp::depends("RcppArmadillo")]]
// [[Rcpp::plugins(openmp)]]
// [[Rcpp::plugins(cpp11)]]


// 'uvec' with nan

// [[Rcpp::export]]
Rcpp::List nan_uvec() {
  
  arma::uvec init_vec(3);
  init_vec.fill(arma::datum::nan);
  
  arma::uvec idx_nan = arma::find_nonfinite(init_vec);
  
  return Rcpp::List::create(Rcpp::Named("uvec_nan") = init_vec,
                            Rcpp::Named("non_finite_uvec") = idx_nan);
}

// nan_uvec()
// $uvec_nan
//       [,1]
// [1,]    0
// [2,]    0
// [3,]    0
// 
// $non_finite_uvec
//   [,1]


// 'vec' with nan

// [[Rcpp::export]]
Rcpp::List nan_vec() {
  
  arma::vec init_vec(3);
  init_vec.fill(arma::datum::nan);
  
  arma::uvec idx_nan = arma::find_nonfinite(init_vec);
  
  return Rcpp::List::create(Rcpp::Named("vec_nan") = init_vec,
                            Rcpp::Named("non_finite_uvec") = idx_nan);
}

// nan_vec()
// $vec_nan
//      [,1]
// [1,]  NaN
// [2,]  NaN
// [3,]  NaN
//   
//   $non_finite_uvec
//       [,1]
// [1,]    0
// [2,]    1
// [3,]    2

```

Someone would expect that the output of the second example code snippet (`arma::vec`) would be also the case for the first example (`arma::uvec`) because in both cases I search for non-finite values (`arma::find_nonfinite`). Based on the [documentation of Armadillo](https://arma.sourceforge.net/docs.html)  `uvec  =  ucolvec  =  Col<uword>` and `vec = colvec = Col<double>`. Is there a difference between unsigned integer compared to a double for NaN values?

I am aware of similar [armadillo Gitlab](https://gitlab.com/conradsnicta/armadillo-code/-/issues/169) and [RcppArmadillo Github](https://github.com/RcppCore/RcppArmadillo/issues/287#issuecomment-588005326) issues, but I'm not certain on how to catch similar cases. Is this the expected output for `arma::uvec`?

**Comment by eddelbuettel** [comment]
I think the `uvec` does not actually get a `NaN`. Here is modified version of your code which
- removes the extra headers we do not need
- adds a `print()` at the C++ level 

showing that the `uvec` actually has zeros.

#### Code

```c++
// [[Rcpp::depends("RcppArmadillo")]]

#include <RcppArmadillo.h>

// 'uvec' with nan
// [[Rcpp::export]]
Rcpp::List nan_uvec() {
    arma::uvec init_vec(3);
    init_vec.fill(arma::datum::nan);
    init_vec.print("uvec in C++");
    arma::uvec idx_nan = arma::find_nonfinite(init_vec);
    return Rcpp::List::create(Rcpp::Named("uvec_nan") = init_vec,
                              Rcpp::Named("non_finite_uvec") = idx_nan);
}

// 'vec' with nan
// [[Rcpp::export]]
Rcpp::List nan_vec() {
    arma::vec init_vec(3);
    init_vec.fill(arma::datum::nan);
    init_vec.print("vec in C++");
    arma::uvec idx_nan = arma::find_nonfinite(init_vec);
    return Rcpp::List::create(Rcpp::Named("vec_nan") = init_vec,
                              Rcpp::Named("non_finite_uvec") = idx_nan);
}

/*** R
nan_uvec()
nan_vec()
*/
```

#### Output

> Rcpp::sourceCpp("~/git/rcpparmadillo/local/issue399.cpp")

```r
> nan_uvec()
uvec in C++
        0
        0
        0
$uvec_nan
     [,1]
[1,]    0
[2,]    0
[3,]    0

$non_finite_uvec
     [,1]


> nan_vec()
vec in C++
      nan
      nan
      nan
$vec_nan
     [,1]
[1,]  NaN
[2,]  NaN
[3,]  NaN

$non_finite_uvec
     [,1]
[1,]    0
[2,]    1
[3,]    2

> 
```

**Comment by mlampros** [comment]
I think it would be better that the case of `uvec`

```cpp
arma::uvec init_vec(3);
init_vec.fill(arma::datum::nan);
```

should give a compilation error. Otherwise these two lines can be integrated to a code base and the user might falsely assume that it works as expected.

**Comment by eddelbuettel** [comment]
I was just out for a run and was thinking about that too but it may just be that C/C++ implicit casting rules get in the way:

````r
> Rcpp::cppFunction("void foo(double val) { arma::uvec v(3); v.fill(val); v.print(); }", depends="RcppArmadillo")
> foo(1.1)
        1
        1
        1
> 
```

**Comment by mlampros** [comment]
understood. thank you for your responses.
