### ISSUE TITLE
using namespace arma;

### ISSUE THREAD

**Issue by ischlo** [RcppCore/RcppArmadillo#412]
Hello, i was wondering if it is possible to include the namespace, my code did not seem to work that way, but it would be convenient to have that especially for bigger functions that rely on many functionalities of the library. Thanks

**Comment by eddelbuettel** [comment]
Please no.  See _Writing R Extensions_ [here with respect to `std`](https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html?q=using%20namespace%20std#portable-c-and-c-code).

Also, you could consider open-ended questions like this on the mailing list.
