### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by ChristophKnapp** [RcppCore/RcppArmadillo#419]
Hi, I'm trying to install RcppArmadillo on a debian computer. R version is 4.3.1 (2023-06-16) -- "Beagle Scouts". I'm not sure what the problem is and could not find anything related to 

/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas

Most often its just a library missing but with this I'm lost. 

I actually try to install the seqinr package where RcppArmadillo is in the dependency tree. 

Regards

> install.packages("RcppArmadillo")
Installing package into ‘/home/hummelchen/R/x86_64-pc-linux-gnu-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RcppArmadillo_0.12.4.1.0.tar.gz'
Content type 'application/x-gzip' length 1373512 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ -std=gnu++17 accepts -g... yes
checking for g++ -std=gnu++17 option to enable C++11 features... none needed
checking how to run the C++ preprocessor... g++ -std=gnu++17 -E
checking whether the compiler supports GNU C++... (cached) yes
checking whether g++ -std=gnu++17 accepts -g... (cached) yes
checking for g++ -std=gnu++17 option to enable C++11 features... (cached) none needed
checking whether we have a suitable tempdir... /tmp
checking whether R CMD SHLIB can already compile programs using OpenMP... yes
checking LAPACK_LIBS... system LAPACK found
configure: creating ./config.status
config.status: creating inst/include/RcppArmadillo/config/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
using C++ compiler: ‘g++ (Debian 10.2.1-6) 10.2.1 20210110’
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -I'/home/hummelchen/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/home/jranke/git/r-backports/bullseye/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppArmadillo.cpp -o RcppArmadillo.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -I'/home/hummelchen/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/home/jranke/git/r-backports/bullseye/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -I'/home/hummelchen/R/x86_64-pc-linux-gnu-library/4.3/Rcpp/include'    -fopenmp -fpic  -g -O2 -ffile-prefix-map=/home/jranke/git/r-backports/bullseye/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c fastLm.cpp -o fastLm.o
g++ -std=gnu++17 -shared -L/usr/lib/R/lib -Wl,-z,relro -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -fopenmp -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/home/hummelchen/R/x86_64-pc-linux-gnu-library/4.3/RcppArmadillo’

The downloaded source packages are in
	‘/tmp/RtmpVeNbCd/downloaded_packages’
Warning message:
In install.packages("RcppArmadillo") :
  installation of package ‘RcppArmadillo’ had non-zero exit status

**Comment by eddelbuettel** [comment]
Please do

      sudo apt install r-base-dev

to get the _development_ packages needed to _link_ against libraries needed, here BLAS and LAPACK.  That is a well documented aspect of how life on Linux system works and is similar for the other distros.

Or just do

     sudo apt install r-cran-rcpparmadillo

and enjoy the pre-made package.  We provide it so that users unfamiliar with builds do not have to worry about it.

As there is no issue with the _source_ package you reported against, I will close this issue.  For general questions on how to use R on Debian, Ubuntu, ... etc the r-sig-debian list is very helpful and would have been a good venue too.

**Comment by ChristophKnapp** [comment]
That was silly of me, I was so sure I did that. Thanks for your fast help.

**Comment by eddelbuettel** [comment]
We all had our moments like that.  No worries.   I hope you get to enjoy RcppArmadillo, by itself or via seqinr.
