### ISSUE TITLE
pass arma::cube object as function argument gives error

### ISSUE THREAD

**Issue by antoniopvgs** [RcppCore/RcppArmadillo#42]
I don not think this is a bug but if you pass and arma::mat object or arma::field as an argument to a function instead, the code runs smoothly. Therefore it seems that the package does not implement the same functionality for arma::cube.

**Comment by eddelbuettel** [comment]
Pull requests would be welcome.

**Comment by antoniopvgs** [comment]
Hi Dirk, that's fair. I'm far from being an expert programmer but found the following code that solves the problem. However, I don't know how easy would be integrating it in your package:

#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
arma::cube array2cube( SEXP myArray ) {

Rcpp::NumericVector vecArray(myArray);
Rcpp::IntegerVector arrayDims = vecArray.attr("dim");

arma::cube cubeArray(vecArray.begin(), arrayDims[0], arrayDims[1], arrayDims[2], false);

return(cubeArray);  

}

Many thanks in any case for providing the Rcpp package.

**Comment by eddelbuettel** [comment]
This has been added in #64.

**Comment by gvegayon** [comment]
Great!

George G. Vega Yon (from mobile)
+1 626 381 8171
http://www.its.caltech.edu/~gvegayon

**Comment by eddelbuettel** [comment]
Our thanks to @nathan-russell  :smiley:

**Comment by antoniopvgs** [comment]
Thanks a lot.

**Comment by eddelbuettel** [comment]
For completeness:

```r
 R> library(Rcpp)
 R> cppFunction("arma::cube doubleCube(arma::cube cb) { return 2*cb; }", depends="RcppArmadillo")
!R> doubleCube(array(1:8, dim=c(2,2,2)))
 , , 1

      [,1] [,2]
 [1,]    2    6
 [2,]    4    8

 , , 2

      [,1] [,2]
 [1,]   10   14
 [2,]   12   16

 R> 
```

Thanks again @nathan-russell !

**Comment by nathan-russell** [comment]
@eddelbuettel More than happy to help where I'm able to :+1:
