### ISSUE TITLE
[DOCS] - Review DESCRIPTION's Date

### ISSUE THREAD

**Issue by cgiachalis** [RcppCore/RcppArmadillo#423]
DESCRIPTION's date points to year 2024.

https://github.com/RcppCore/RcppArmadillo/blob/3fa6590a3f6af858c6c69e18e0ca8b243417dd94/DESCRIPTION#L5

The date changed to `2024-04-04`  in: https://github.com/RcppCore/RcppArmadillo/commit/f393c6029174304a0bcd17b1b2a6e85a445a0476 where the date stamp was 2023-04-04...  :)

**Comment by eddelbuettel** [comment]
Thanks for catching that typo, now fixed.

**Comment by eddelbuettel** [comment]
Oddly, R CMD check warns about _old_ dates but not dates in the future.  Oh well.
