### ISSUE TITLE
Failed to install RcppArmadillo on Linux Hyper Cluster

### ISSUE THREAD

**Issue by Geophagus96** [RcppCore/RcppArmadillo#427]
I tried to install RcppArmadillo on a school Linux Hyper Cluster (which I do not have sudo access). I am installing via:

> install.packages('RcppArmadillo')

in the R interface with R version 4.3.1 and Rcpp version 1.0.11. The installation failed with error message:

![linuxR](https://github.com/RcppCore/RcppArmadillo/assets/33130813/eaeda727-062e-4a73-9e95-b5ca81290503)

I am wondering is the dependency on open_mp that leads to this failed installation?

**Comment by eddelbuettel** [comment]
Please see the corpus of [existing (closed) issues here](https://github.com/RcppCore/RcppArmadillo/issues?q=is%3Aissue+is%3Aclosed) which you can also search.  You likely have an insufficient compiler, and the issues discuss different ways to overcome this on the different systems, eg RHEL/CentOS and alike with ancient compilers.

You screenshot is also completely illegible.  It is generally recommended here and eg at StackOverflow to only post copied-and-pasted text.

**Comment by eddelbuettel** [comment]
I suspect you are the same person who [just asked on StackOverflow](https://stackoverflow.com/questions/77426669/failed-to-install-rcpparmadillo-on-linux-with-openmp-error#77426669).

**Comment by Geophagus96** [comment]
lol, yes I am the same person

**Comment by eddelbuettel** [comment]
Thanks for putting the added text in over there, you could have done it here too of course.  Looks like you are a little stuck with your tools but between an older source version, trying to get a current compiler and putzing with default setup to edit out OpenMP you use you may get there.  Let us know -- it is entirely a local deployment issue.
