### ISSUE TITLE
Rcpp required version might need updating?

### ISSUE THREAD

**Issue by raymondben** [RcppCore/RcppArmadillo#441]
Was treated to this complaint when trying to install RcppArmadillo on a not-very-frequently updated machine:
```
In file included from RcppArmadillo.cpp:21:
../inst/include/RcppArmadillo/Lighter:37:10: fatal error: Rcpp/Lighter: No such file or directory
   37 | #include <Rcpp/Lighter>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

The Rcpp version was old (1.0.7) and updating it solved the problem. But in doing so I noticed that the current RcppArmadillo DESCRIPTION file requires only Rcpp >= 0.11.0 (https://github.com/RcppCore/RcppArmadillo/blob/master/DESCRIPTION#L25)

I think the Lighter usage was brought in after Rcpp 1.0.7 (https://github.com/RcppCore/Rcpp/commit/d0bad4dfe9d1fcb9cfc95e2805617450edd2e851) - should the required Rcpp version be updated?
Apologies for the noise if that's not the case.

**Comment by eddelbuettel** [comment]
That's a good catch and correct.  Rcpp 1.0.8 in Jan 2022 brought those and I will update the minimum version.

(I always run `update.packages()` so no machine of mine would have a new RcppArmadillo and an outdated Rcpp.)
