### ISSUE TITLE
OpenMP + macOS round 20? 

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppArmadillo#444]
It seems like the CRAN r binary is now shipping with built-in libomp headers! So, the check inside of [`configure.ac`](https://github.com/RcppCore/RcppArmadillo/blob/37461ba36472305c699263afc229919d37daa5e3/configure.ac#L109) and the [`inline` plugin](https://github.com/RcppCore/RcppArmadillo/blob/37461ba36472305c699263afc229919d37daa5e3/R/inline.R#L20) might need to be tweaked to unlock additional cores.

The goal of the ticket is to register a change in macOS; but, there is no need to exert energy since it's part of an ongoing discussion in R-SIG-MAC with [Simon](https://stat.ethz.ch/pipermail/r-sig-mac/2024-June/015012.html) and [Prof. Ripley](https://stat.ethz.ch/pipermail/r-sig-mac/2024-June/015008.html) chiming in.

**Comment by eddelbuettel** [comment]
Thanks for keeping tabs on it. I don't follow r-sig-mac but trust you will advice if/when/which changes are needed. Much appreciated.

**Comment by eddelbuettel** [comment]
@coatless Any update, or sage advice for something we should consider altering or adding?

**Comment by coatless** [comment]
Nope. We're going to close this out. Headers are still opt-in.
