### ISSUE TITLE
Incompatability with Rcpp::clone

### ISSUE THREAD

**Issue by halidaee** [RcppCore/RcppArmadillo#453]
I have a number of areas in my code where I am trying to make a deep copy of an arma::mat object, i.e. 

`arma::mat X = Rcpp::clone(inputs)`

These are almost always clones of objects passed on as function inputs, i.e. 

```
arma::mat next_W_func(const arma::mat& W_k) {
      arma::mat W_kmin1 = clone(W_k);
}
// code to change W_k
```

Every instance I try adding Rcpp::clone to my code results in the following error during build:

```
/open/programs/miniconda3/envs/r_env/lib/R/library/Rcpp/include/Rcpp/clone.h: In instantiation of 'T Rcpp::clone(const T&) [with T = arma::Mat<double>]':
demo.cpp:79:30:   required from here
   79 |     arma::mat X = Rcpp::clone(inputs);
      |                   ~~~~~~~~~~~^~~~~~~~
/open/programs/miniconda3/envs/r_env/lib/R/library/Rcpp/include/Rcpp/clone.h:34:18: error: no matching function for call to 'Rcpp::Shield<SEXPREC*>::Shield(arma::Mat<double>&)'
   34 |     Shield<SEXP> x(const_cast<T&>(object));
      |                  ^
// error continues very long trace after here.
```

I'm wondering if there is some incompatibility with this package and Rcpp?

**Comment by halidaee** [comment]
After some additional toying around, this doesn't appear to be something specific with arma object, so closing issue.

**Comment by eddelbuettel** [comment]
There may be some template magic missing which the 'no matching function' indicates. Feel free to send a PR with missing pieces if you feel motivated to fill the hole.   

In the meantime, I would probably use a shortcut, convert back to `SEXP` and/or clone earlier as `SEXP` objects as  `clone()` works on `SEXP`.  The comments in `clone.h` are illustrative:



```c++
/* cloning type T is possible if :
   - T can be converted to SEXP
   - T has a SEXP constructor
*/
template <typename T> T clone(const T& object) {
    Shield<SEXP> x(const_cast<T&>(object));
    Shield<SEXP> copy(Rf_duplicate(x));
    return T((SEXP)copy);
}
```

You could also look at doing this the C++ way and instantiate a new object from the old one.  Untested:

```c++
arma::mat next_W_func(const arma::mat& W_k) {
      return arma::mat{ W_k };
}
```
