### ISSUE TITLE
how to achieve QR for lm

### ISSUE THREAD

**Issue by Sherry520** [RcppCore/RcppArmadillo#459]
I want to calculate the regression coefficient using QR decomposition. But why here `arma::qr_econ(X_mat, y_vec);` "no matching function for call qr_econ()"?
```C++
List lm_armadillo_with_p_values(arma::mat mat) {
  // seprate matrix to y and x
  arma::mat X_mat = mat.cols(1, mat.n_cols - 1);
  arma::vec y_vec = mat.col(0); 
  
  // check dim
  if (X_mat.n_rows != y_vec.n_rows) {
    stop("Number of rows in X does not match length of y.");
  }
  
  // // Calculated regression coefficient by lsmeans method
  // arma::vec beta = solve(X_mat, y_vec);  // beta = (X'X)^(-1) X'y
  
  // Calculated regression coefficient by QR
  arma::qr_econ(X_mat, y_vec); 

  // beta = R^(-1) * Q^T * y
  arma::mat Q = Q; 
  arma::mat R = R; 

  // Calculated regression coefficient
  arma::vec beta = inv(R) * Q.t() * y_vec;
    
  // Calculated predicted value
  arma::vec y_hat = X_mat * beta;
  
  // Calculated residual
  arma::vec residuals = y_vec - y_hat;
  
  // Calculation standard error
  arma::mat X_transpose = X_mat.t();
  arma::mat var_beta = inv(X_transpose * X_mat) * var(residuals);  // (X'X)^(-1) * Var(ε)
  arma::vec se_beta = sqrt(var_beta.diag());  // Extraction standard error
  
  // Calculate the t statistic
  arma::vec t_stat = beta / se_beta;
  
  // Calculating P-values (two-tail test)
  int n = X_mat.n_rows;  // sample size
  int p = X_mat.n_cols;  // Number of predictors
  int df = n - p;        // Degree of freedom
  NumericVector p_values(t_stat.n_elem); 
  // Iterate over the tstat to compute the corresponding p-value
  for (size_t i = 0; i < t_stat.n_elem; ++i) {
    p_values[i] = 2 * (1 - R::pt(std::abs(t_stat[i]), df, 0, 0));
  }
  
  // R-squared
  double ss_total = sum(square(y_vec - mean(y_vec)));
  double ss_residual = sum(square(residuals));
  double r_squared = 1 - (ss_residual / ss_total);
  
  // return result
  return List::create(
    Named("coefficients") = beta,
    Named("residuals") = residuals,
    Named("standard_errors") = se_beta,
    Named("t_stat") = t_stat,
    Named("p_values") = p_values,
    Named("r_squared") = r_squared
  );
}

```

**Comment by eddelbuettel** [comment]
If you look at the [documentation for qr_econ](https://arma.sourceforge.net/docs.html#qr_econ) it clearly states you need three arguments.

> qr_econ( Q, R, X )

> Economical decomposition of X (with size m x n) into an orthogonal matrix Q and a right triangular matrix R, such that Q*R = X

so if you write your code as 

```c++
  // beta = R^(-1) * Q^T * y
  arma::mat Q = Q;
  arma::mat R = R;

  // Calculated regression coefficient by QR
  qr_econ(Q, R, X_mat);
```

it compiles.  It didn't check whether the values you compute are correct as you did not provide a minimally complete verifiable example -- only the core of one function.

**Comment by eddelbuettel** [comment]
Also be aware of what we document in the context of `fastLm()` :  but R does internally is more sophisticated, there is a difference between what statisticians prefer and what numerical analysis do.  This should only matter for degenerate case but keep it in mind.

**Comment by Sherry520** [comment]
> Also be aware of what we document in the context of `fastLm()` : but R does internally is more sophisticated, there is a difference between what statisticians prefer and what numerical analysis do. This should only matter for degenerate case but keep it in mind.

Thank you very much. I'll look up more information to understand the context of `fastLm()`.

**Comment by eddelbuettel** [comment]
I did not say that what `fastLm()` does is better: I said it is different from what R does.  As is your method. 

In short, R does *not* just call QR from LAPACK/BLAS.  As stated it may not matter in most cases, but in can in some cases.  Which is why we wrote the note below.  So be aware.

https://github.com/RcppCore/RcppArmadillo/blob/7b4bd345326a33b598f98f60dc24b6481ccdd157/man/fastLm.Rd#L37-L53

**Comment by Sherry520** [comment]
> I did not say that what `fastLm()` does is better: I said it is different from what R does. As is your method.
> 
> In short, R does _not_ just call QR from LAPACK/BLAS. As stated it may not matter in most cases, but in can in some cases. Which is why we wrote the note below. So be aware.
> 
> https://github.com/RcppCore/RcppArmadillo/blob/7b4bd345326a33b598f98f60dc24b6481ccdd157/man/fastLm.Rd#L37-L53

Thank you. I got it.
