### ISSUE TITLE
Memory allocation when creating an arma::cube from an existing pointer

### ISSUE THREAD

**Issue by NikNakk** [RcppCore/RcppArmadillo#47]
This has come up on [stackoverflow](http://stackoverflow.com/questions/31439134/rcpparmadillo-issue-with-memory-usage).

Creating an `arma::cube` object from the pointer to an existing `NumericVector` shouldn't result in much if any increased use of RAM. However, if the number of slices is large, there is a big spike of memory usage. This seems to relate to code in `create_mat` within "Cube_meat.hpp" which allocates RAM for matrix pointers for a `cube` object, but I can't work out why it should require so much RAM. With the example below on my machine (which has 12 GB of RAM), the memory never becomes an issue. However, ramping up the array size further can quickly lead to me running out of RAM altogether.

I'm using R 3.2.1 and RcppArmadillo 0.5.200.1.0 running under 64 bit Windows 8.1. I've also tested R 3.2.1 on Scientific Linux 6 (based on RHEL 6) and can demonstrate the same behaviour.

Reproducible example:

    library("RcppArmadillo")
    library("inline")
    code <- "
    Rcpp::NumericVector input_(input);
    IntegerVector dim = input_.attr(\"dim\");
    arma::cube disturb(input_.begin(), dim[0], dim[1], dim[2], false);
    disturb[0, 0, 0] = 45;
    return wrap(2);
    "
    Test <- cxxfunction(signature(input = "numeric"), plugin = "RcppArmadillo", body = code)
    input <- array(1e7, 2, 2)
    Test(input)
    # no change in memory usage

    dim(input) <- c(2, 1e7, 2)
    gc()
    Test(input)
    # no change in memory usage

    dim(input) <- c(2, 2, 1e7)
    gc()
    Test(input)
    # spike in memory usage

    dim(input) <- c(20, 2, 1e6)
    gc()
    Test(input)
    # no change in memory usage
    library("RcppArmadillo")
    library("inline")
    code <- "
    Rcpp::NumericVector input_(input);
    IntegerVector dim = input_.attr(\"dim\");
    arma::cube disturb(input_.begin(), dim[0], dim[1], dim[2], false);
    disturb[0, 0, 0] = 45;
    return wrap(2);
    "
    Test <- cxxfunction(signature(input = "numeric"), plugin = "RcppArmadillo", body = code)
    input <- array(0, c(1e7, 2, 2))
    Test(input)
    # no change in memory usage

    dim(input) <- c(2, 1e7, 2)
    gc()
    Test(input)
    # no change in memory usage

    dim(input) <- c(2, 2, 1e7)
    gc()
    Test(input)
    # spike in memory usage

    dim(input) <- c(20, 2, 1e6)
    gc()
    Test(input)
    # no change in memory usage

**Comment by eddelbuettel** [comment]
But isn't that an Armadillo issue for which you'd need to talk to Conrad?   

I don't see anything we do as getting in the way.  Am I overlooking anything?

**Comment by NikNakk** [comment]
Quite right. I was confusing what was your code vs. what was in Armadillo itself.

 

I’ve now produced a reproducible example using just C++ and Armadillo and will send it on.

 

BW

 

Nick
