### ISSUE TITLE
sort_index compatibility issue pre and post version 0.5

### ISSUE THREAD

**Issue by JEFworks** [RcppCore/RcppArmadillo#49]
Hi,

I have two version of RcppArmadillo on two different servers: RcppArmadillo_0.5.200.1.0 and RcppArmadillo_0.4.650.1.1

When I run `sort_index` with RcppArmadillo_0.5.200.1.0, the output is returned as a column. Whereas, when I run `sort_index` with RcppArmadillo_0.4.650.1.1, the output is returned as a row. 

`sort_index` with RcppArmadillo_0.5.200.1.0 also doesn't handle `Inf` whereas RcppArmadillo_0.4.650.1.1 treats `Inf` as largest possible value. 

I believe this incompability was introduced in v0.5 when 'sort_index() and stable_sort_index() have been placed in the delayed operations framework for increased efficiency' 

In case you want to test this out, I used the following code:
```
library('Rcpp')
library('inline')

rcpp_inc <- '
using namespace Rcpp;
'

src <- ' 
arma::mat m=Rcpp::as<arma::mat>(Mat);
arma::rowvec z=m.row(0);
arma::urowvec o=arma::sort_index(z, "ascend"); // ascending order
return wrap(o);
'

fn <- cxxfunction(signature(Mat="numeric"), src, plugin='RcppArmadillo', rcpp_inc)

set.seed(0)
mat <- matrix( c(rnorm(5*10,mean=0,sd=1), rnorm(5*10,mean=5,sd=1)), 10, 10)
mat[1,1] <- Inf

fn(mat)
```

With RcppArmadillo_0.4.650.1.1, the output is a row:
```
> fn(mat)
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    3    2    1    4    8    7    5    6    9     0
```

With RcppArmadillo_0.5.200.1.0, if I don't uncomment `mat[1,1] <- Inf`, then I get the following error:
`Error: sort_index(): detected non-finite values`

If I remove the infinite, then I still have to make `urowvec` into `uvec` to avoid `Error: Mat::init(): requested size is not compatible with row vector layout` because the output is a column:
```
> fn(mat)
      [,1]
 [1,]    3
 [2,]    2
 [3,]    1
 [4,]    0
 [5,]    4
 [6,]    8
 [7,]    7
 [8,]    5
 [9,]    6
[10,]    9
```

Please fix this compatibility issue. I much prefer the old return style and ability to handle infinite values. 

I have a package that depends on RcppArmadillo (https://github.com/hms-dbmi/scde), developed using RcppArmadillo_0.4.650.1.1. Would you recommend I update my code to conform to RcppArmadillo_0.5.200.1.0's return outputs or will you be updating RcppArmadillo_0.5.200.1.0 to be compatible with RcppArmadillo_0.4.650.1.1?

Thanks! Feel free to let me know if I could be of assistance with anything else.

Best,
Jean

**Comment by eddelbuettel** [comment]
I have very little to say to all of this ... as you seem to be affected by changed in Armadillo.  So maybe talking to Conrad is more important.  I'll send him an email with this issue ticket url.

**Comment by eddelbuettel** [comment]
Mind you the row vs col change may be us. OTOH we run pretty stringent tests against all CRAN packages depending on RcppArmadillo before each release to catch any and all regressions.  And address those before a release.

So with I can only recommend that you do upload your package to CRAN, even if not perfect yet, as it would then become part of the test set :)

**Comment by JEFworks** [comment]
Thanks to you and Conrad for the fix!

**Comment by eddelbuettel** [comment]
Glad to hear it is all sorted out with version 0.5.400.2.0 -- and thanks as always to Conrad.
