### ISSUE TITLE
zgesvx missing in Rlapack

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#67]
This is used by Baptiste's [cda](https://cran.r-project.org/web/packages/cda/index.html) package, and per email from KH leads to a regression test error on systems using Rlapack.

**Comment by kthohr** [comment]
I still don't see the argument for not including a full Lapack distribution with R...

**Comment by eddelbuettel** [comment]
You are talking to the wrong person. I am not part of R Core. Please take that aspect to the r-devel list.

**Comment by eddelbuettel** [comment]
Thanks to Conrad this use is now also flagged to @baptiste 's [cda](https://github.com/baptiste/cda) will now build either way.  When Rlapack is used we still lack about a dozen complex functions but that is an issue we need to take up with R Core.

**Comment by thirdwing** [comment]
FYI. `zgesvx` has been added into R.

See the commit https://github.com/wch/r-source/commit/98acd96f22eb795a933879c0d3f740e802855473

**Comment by eddelbuettel** [comment]
Thanks, we know -- I emailed Baptiste last eve when I found out and had tested against a brand-new r-devel.

**Comment by eddelbuettel** [comment]
This has been taken care of in R 3.3.0.   

There is now complete LAPACK support for complex numbers even when the included LAPACK is used.
