### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by seninp** [RcppCore/RcppArmadillo#68]
Having troubles installing the library, could you please help?:

> library(devtools)
> install_github('RcppCore/RcppArmadillo')
Downloading GitHub repo RcppCore/RcppArmadillo@master
Installing RcppArmadillo
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  '/tmp/RtmpAKuXjx/devtools655039c1e2f9/RcppCore-RcppArmadillo-2f9f114'  \
  --library='/home/psenin/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘RcppArmadillo’ ...
* checking LAPACK_LIBS: divide-and-conquer complex SVD available via system LAPACK
** libs
ccache clang++ -Qunused-arguments -I/usr/share/R/include -DNDEBUG   -I"/home/psenin/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I../inst/include -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppArmadillo.cpp -o RcppArmadillo.o
In file included from RcppArmadillo.cpp:22:
In file included from ../inst/include/RcppArmadillo.h:30:
In file included from ../inst/include/RcppArmadilloForward.h:46:
In file included from ../inst/include/armadillo:50:
../inst/include/armadillo_bits/compiler_setup.hpp:273:7: error: builtin feature check macro requires a parenthesized identifier
  #if __has_attribute(__const__)
      ^
../inst/include/armadillo_bits/compiler_setup.hpp:273:32: error: expected end of line in preprocessor expression
  #if __has_attribute(__const__)
                               ^
2 errors generated.
make: *** [RcppArmadillo.o] Erreur 1
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/home/psenin/R/x86_64-pc-linux-gnu-library/3.2/RcppArmadillo’
Erreur : Command failed (1)

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.9.1       BiocInstaller_1.20.1

loaded via a namespace (and not attached):
[1] httr_1.0.0    R6_2.1.1      magrittr_1.5  tools_3.2.2   curl_0.9.4   
[6] memoise_0.2.1 stringi_1.0-1 stringr_1.0.0 digest_0.6.8

**Comment by eddelbuettel** [comment]
1) Your question is poorly formatted. Do you use quoye (`>`) when you mean code. See the help.
2) Installation from `devtools` is not supported or encouraged.  
3) We make monthly (!!) releases to CRAN. Use those. The command is `install.packages()`.
4) Your error message, buried in the ill-formatted question, suggested that the compiler in Ubuntu 12.04 may be too old.  Nothing we can fix.  Use an older RcppArmadillo if this is the binding issue--or better still upgrade your compile or Ubuntu version.
5) For what it is worth we run Travis CI on that Ubuntu version too.  The last test four days ago preceding the last release used `gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3`.

**Comment by seninp** [comment]
I see, sorry for the trouble. 

Nevertheless, CRAN-based installation throws exactly the same exception:

    essai de l'URL 'http://cran.rstudio.com/src/contrib/RcppArmadillo_0.6.300.2.0.tar.gz'
    Content type 'application/x-gzip' length 984649 bytes (961 KB)
    ==================================================
    downloaded 961 KB

    * installing *source* package ‘RcppArmadillo’ ...
    ** package ‘RcppArmadillo’ correctement décompressé et sommes MD5 vérifiées
    * checking LAPACK_LIBS: divide-and-conquer complex SVD available via system LAPACK
    ** libs
    ccache clang++ -Qunused-arguments -I/usr/share/R/include -DNDEBUG   -I"/home/psenin/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I../inst/include -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppArmadillo.cpp -o RcppArmadillo.o
    In file included from RcppArmadillo.cpp:22:
    In file included from ../inst/include/RcppArmadillo.h:30:
    In file included from ../inst/include/RcppArmadilloForward.h:46:
    In file included from ../inst/include/armadillo:50:
    ../inst/include/armadillo_bits/compiler_setup.hpp:273:7: error: builtin feature check macro requires a parenthesized identifier
      #if __has_attribute(__const__)
          ^
    ../inst/include/armadillo_bits/compiler_setup.hpp:273:32: error: expected end of line in preprocessor expression
      #if __has_attribute(__const__)
                               ^
    2 errors generated.

My gcc version is also 4.6.3

    $ gcc --version
    gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
    Copyright © 2011 Free Software Foundation, Inc.

Updating OS at the host is not possible. Where can I get older sources?

Thanks!

**Comment by eddelbuettel** [comment]
As I told you, `g++-4.6.3` has been used for _hundreds_ of builds by us. It is fine.

Now that you questions is legible, we see `ccache clang++ `.  Turn off that `clang` version and try again.

Older sources are in `Archive/` section of CRAN.  Each package has its full history.

**Comment by seninp** [comment]
Done! Thank you guys!

    ** testing if installed package can be loaded
    * DONE (RcppArmadillo)

**Comment by eddelbuettel** [comment]
Ok. For that record, what does `clang++ --version` say?  Something from the dark ages likes 3.2 or so?  Newer versions should all work too.

There _will_ be  a cutoff point at which `g++-4.6.*` will be too old too once Conrad switches to a C++11 based version.

**Comment by seninp** [comment]
Ha, 3.0!!!

    $ clang++ --version
    Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
    Target: x86_64-pc-linux-gnu
    Thread model: posix

**Comment by eddelbuettel** [comment]
Jeebus.  John von Neuman wrote that one himself while he was at Los Alamos, right?

**Comment by seninp** [comment]
True story!

Thank you again for the help and a good joke!
