### ISSUE TITLE
Error installing RcppArmadillo

### ISSUE THREAD

**Issue by IsabelFE** [RcppCore/RcppArmadillo#71]
Hello,

I am new to R and I having some issues installing packages. I am trying to install RcppArmadillo and I am getting the next error:

install.packages("RcppArmadillo")

ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RcppArmadillo.so] Error 1
ERROR: compilation failed for package 'RcppArmadillo'
* removing '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RcppArmadillo'

Could you please help me?
 
Some info: I use OSX el Capitan 10.11. 
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Platform: x86_64-apple-darwin13.4.0 (64-bit)
R Studio Version 0.99.489 

Thanks a lot,

Isabel

**Comment by eddelbuettel** [comment]
The error is right in front of you:

> ld: library not found for -lgfortran

Please see the OS X help for R -- there is a list or google it -- on this. I don't have an OS X machine, but I understand this be a FAQ.  Worst case please subscribe to [rcpp-devel](http://lists.r-forge.r-project.org/cgi-bin/mailman/listinfo/rcpp-devel) and ask there.

**Comment by kthohr** [comment]
You need gfortran v4.8; see here:

http://www.thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

which is still relevant for El Capitan. Open terminal and run
```
curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
```

**Comment by eddelbuettel** [comment]
Yep, I just poked around on StackOverflow and here is [one answer from there](
http://stackoverflow.com/questions/30562877/r-can-not-find-gfortran). Thanks for the link from @coatless.

**Comment by cripenam** [comment]
It works to some people if you install the Dev version:

install.packages("https://cran.r-project.org/src/contrib/Archive/RcppArmadillo/RcppArmadillo_0.9.900.3.0.tar.gz", repos=NULL, type="source")

**Comment by eddelbuettel** [comment]
I am sorry but what value does that message add?  We had three+ more releases since so 0.9.900.3.0 is *outdated*.

**Comment by Ethan4444444** [comment]
I know this thread concerns OS X, but if any Debian-based distro users are directed here (as I was), the problem can be solved by installing the Fortran compiler:

`sudo apt-get install gfortran`

Version specs:

Ubuntu 20.04
R version 4.1.0
RcppArmadillo version 0.10.6.0.0

**Comment by eddelbuettel** [comment]
I am going to delete this comment shortly as it adds no value here.  `gfortran` is implied by `r-base-dev` which you should have installed anyway.

**Comment by Ethan4444444** [comment]
> I am going to delete this comment shortly as it adds no value here.  `gfortran` is implied by `r-base-dev` which you should have installed anyway.

Perhaps it might be beneficial to leave my comment here, together with your message about `r-base-dev`, because the thread does not mention the need to have `r-base-dev` installed.

**Comment by eddelbuettel** [comment]
The thread is for a different os.

**Comment by Ethan4444444** [comment]
Understandable. Have a nice day
