### ISSUE TITLE
Trouble with installing under FreeBSD...

### ISSUE THREAD

**Issue by jszhao** [RcppCore/RcppArmadillo#74]
When I tried to install RcppArmadillo, I got the following error message:

`* installing *source* package 'RcppArmadillo' ...`
`** package 'RcppArmadillo' successfully unpacked and MD5 sums checked`
`./configure: not found`
`ERROR: configuration failed for package 'RcppArmadillo'`
`* removing '/usr/local/lib/R/library/RcppArmadillo'`

I don't know how to solve this problem.

Any help will be appreciated.

**Comment by eddelbuettel** [comment]
The `configure` script has `#!/bin/bash`.

Download the tarball, adjust accordingly (ie pick a different shell, or install bash, or whatever) and then install from the updated sources.

I'd recommend having `#!/bin/bash`.  We're hardly the only ones using that.

**Comment by jszhao** [comment]
Thanks. I have downloaded the source code and change the `#!/bin/bash` in `configure` to `#!/usr/local/bin/bash`, and then it works.

**Comment by eddelbuettel** [comment]
Nice.  I had a look at the script, and I do use some bashisms there so it would be a pain to change.

One intermediate step would be `#!/usr/bin/env bash` (using the `env foo` trick common with Python).  Can you check if that works too?  I could make that change, it should work on all systems where bash is native anyway and also on those like yours where it needs to be added.

**Comment by jszhao** [comment]
Thanks a lot for pointing to `#!/usr/bin/env bash` trick. I have checked that, and it works like a charm.

**Comment by eddelbuettel** [comment]
I'll make the change, and keep it in mind. Sorry to be enforcing bash on you, but it is a pretty common shell out here (though the *BSDs and other have their own of course).

**Comment by jszhao** [comment]
There is another way, that is to a symbolic link named `/bin/bash` and 
point it to `/usr/local/bin/bash`
```
ln -s /usr/local/bin/bash /bin/bash
```
On FreeBSD, bash could be installed as a package.

**Comment by eddelbuettel** [comment]
Yes, of course, but *you* have to do that. I cannot rely on it being present.  Had you done that before you would not have noticed this.

(And I'd do it, as much as I hate messing with system directories which your package installer owns.)

**Comment by jszhao** [comment]
Thank you for making the change. Frankly, I also hate to add symbolic to /bin/.
