### ISSUE TITLE
randu and randn hang on 0.6.5

### ISSUE THREAD

**Issue by faraway1nspace** [RcppCore/RcppArmadillo#79]
Hello and thank you for Rcpp and RcppArmadillo!

I am currently using Rcpp 0.11.6 on R 3.2 on Ubuntu 14.04, using packages installed from the CRAN ubuntu repo. I am currently using RcppArmadillo 0.4.400.0, because newer versions of RcppArmadillo fail the following test (in R) :

```r
library(Rcpp)
library(RcppArmadillo)
library(inline)
testarmadillo <-cxxfunction(sig=c(n="integer"), 
                                            body='
     arma::mat f = arma::join_rows(arma::randu(Rcpp::as<int>(n)),  
                                   arma::randn(Rcpp::as<int>(n)));
     return wrap(f);',
                                            plugin="RcppArmadillo") # COMPILES NO ERRORS
testarmadillo(10)  # HANGS INFINITELY
```

Calling randu or randn causes the terminal to hang infinitely.  I have to kill the terminal to stop the process. I have checked various RcppArmadillo versions (archived on CRAN), and it seems to occur on every version greater than 0.4.4 (such as 0.4.5, 0.5, etc....) as well as the latest version. It works on 0.4.4.000.0.  There are no warnings when I compile RcppArmadillo.

**Comment by eddelbuettel** [comment]
Ok, a few things:

1. Try formatting your posts. It makes it easier for other people to read your posts, and hence more likely they will help you. I formatted it for you.
2.  You were using the older inline approach.  Rcpp Attributes is nicer. A new version is below.
3.  RcppArmadillo is used from R.  R has *very* good and *extremely* well-tested statistical algorithms.  I would use R's RNG.  In fact, that is what we do here as I recall...
4.  For me it all works.

New file:

```c++
#include <RcppArmadillo.h>

// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
arma::mat foo(int n) {
    arma::mat f = arma::join_rows(arma::randu(n),  
                                  arma::randn(n));
    return f;
}

/*** R
set.seed(123)
foo(5)
*/
```

which we simple feed to `sourceCpp()` which will also run the code:

```r
R> set.seed(123)

R> foo(5)
          [,1]        [,2]
[1,] 0.2875775 -0.61079930
[2,] 0.7883051  0.03777546
[3,] 0.4089769  0.95877582
[4,] 0.8830174  0.12566834
[5,] 0.9404673 -0.05538708
R> 
```

Best of all, the seed is linked to R as we (as I recall) use R's RNG by default.  Calling again gives different numbers; resetting the seed gives (as expected) what we just got:

```r
R> foo(5)
          [,1]       [,2]
[1,] 0.4533342 -0.1193901
[2,] 0.6775706  0.3153385
[3,] 0.5726334  0.6708789
[4,] 0.1029247  0.3320531
[5,] 0.8998250  0.9669271
R> set.seed(123)
R> foo(5)
          [,1]        [,2]
[1,] 0.2875775 -0.61079930
[2,] 0.7883051  0.03777546
[3,] 0.4089769  0.95877582
[4,] 0.8830174  0.12566834
[5,] 0.9404673 -0.05538708
R> 
```

Strictly no issue here.   I _suspect_ that the cause may have been your use of `cxxfunction()` AND the random generator WITHOUT setting RNGState (see Writing R Extensions).   The Rcpp Attributes approach does that automatically for you, and I no longer recall if we did that for inline too.

**Comment by faraway1nspace** [comment]
Superb! Thanks for the detailed correction and broad lesson. This now works on RcppArmadillo 0.6.5.
