### ISSUE TITLE
Compilation failure when installed via Bioconductor in R v3.2.5

### ISSUE THREAD

**Issue by systemdown** [RcppCore/RcppArmadillo#86]
Not sure this is the right place to submit an issue related to RcppArmadillo and Bioconductor, please remove if it's not appropriate.

I first tried to install my stable R v3.2.2 toolchain on a new CentOS v6.7 machine and the latest DESeq2 package (or one of its dependencies) required RcppArmadillo which failed to compile.

I didn't see this a month or two ago when I last did a rollout, so I thought maybe some dependencies are now only supported in R v3.2.5 (latest) so I did a **fresh** install of R v3.2.5 and the first package I tried to install was "RcppArmadillo" on its own from Bioconductor; it failed also.

Error and steps to replicate below:

`$ sudo /opt/R-3.2.5/bin/R --no-save`

`> source('/tmp/biocLite.R')
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help`

`> biocLite(c('RcppArmadillo'))
BioC_mirror: http://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.1), R 3.2.5 (2016-04-14).`

 ... ommitting output of successful compile and install of "Rcpp" and other auto dependencies

`Installing package(s) ‘RcppArmadillo’
trying URL 'http://cran.rstudio.com/src/contrib/RcppArmadillo_0.6.700.3.0.tar.gz'
Content type 'application/x-gzip' length 1002967 bytes (979 KB)
downloaded 979 KB`

`* installing source package ‘RcppArmadillo’ ...`
` package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
 checking LAPACK_LIBS: R-supplied partial LAPACK found
 some operations may not be available`

`g++ -I/opt/R-3.2.5/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/opt/R-3.2.5/lib64/R/library/Rcpp/include"  -I../inst/include -fpic  -g -O2  -c R
cppArmadillo.cpp -o RcppArmadillo.o
In file included from ../inst/include/armadillo:107,
                 from ../inst/include/RcppArmadilloForward.h:46,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo_bits/traits.hpp: In instantiation of ‘const bool arma::is_arma_type<std::__traitor<std::__is_integer<int>, std::__is_floatin
g<int> >::<anonymous enum> >::value’:
../inst/include/armadillo_bits/op_logmat_meat.hpp:289:   instantiated from here
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem2’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem1’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_col’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_row’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_diagview’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtGlue’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtOp’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eGlue’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eOp’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Glue’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Op’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Gen’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<int>, std::__is_floating<int> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Mat’
../inst/include/armadillo_bits/traits.hpp: In instantiation of ‘const bool arma::is_arma_type<std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum> >::value’:
../inst/include/armadillo_bits/op_logmat_meat.hpp:289:   instantiated from here
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem2’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_elem1’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_col’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview_row’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_subview’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_diagview’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtGlue’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_mtOp’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eGlue’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_eOp’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Glue’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Op’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Gen’
../inst/include/armadillo_bits/traits.hpp:642: error: ‘std::__traitor<std::__is_integer<double>, std::__is_floating<double> >::<anonymous enum>’ is/uses anonymous type
../inst/include/armadillo_bits/traits.hpp:642: error:   trying to instantiate ‘template<class T> struct arma::is_Mat’`
`make: [RcppArmadillo.o] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
 removing ‘/opt/R-3.2.5/lib64/R/library/RcppArmadillo’`

`The downloaded source packages are in
        ‘/tmp/RtmphzwtY3/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘RcppArmadillo’ had non-zero exit status`

`> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.7 (Final)`

`locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C`

`attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base`

`other attached packages:
[1] BiocInstaller_1.20.1`

`loaded via a namespace (and not attached):
[1] tools_3.2.5`
`> q()`

`$ g++ --version`
`g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.`

It's been a while since I've touched C++, I can't tell whether it's a C++ version incompatibility, or compiler directive issue or something else entirely - hoping you might know what it could be, cheers.

**Comment by jar1karp** [comment]
I'm getting the same error on RHEL 6.7 that has same g++ version. No issues with newer compiler (e.g. gcc-5.3.1). Installing with devtools::install_github('RcppCore/RcppArmadillo', ref='6450efdb9b727539dabd13467db5a7a0f25c8b38') seems to work, so apparently the armadillo update to 6.700.3 after this requires newer compiler.

**Comment by eddelbuettel** [comment]
g++-4.4 is simply getting too old.  Same for some other packages of ours.

And the GitHub sources are identical to the CRAN package.

**Comment by eddelbuettel** [comment]
This issue is also identical to #85.

**Comment by systemdown** [comment]
Thanks @jar1karp and @eddelbuettel - I wasn't aware that g++ 5.x was required, it's not something I had thought about. Seems a shame that CentOS 6, as with RHEL 6 are supported until 2020 and they ship g++ 4.4 by default.

**Comment by systemdown** [comment]
Also my apologies, I'm not familiar with Github and didn't see that I could search for closed issues (I only saw the 4 open issues). Thanks again.

**Comment by eddelbuettel** [comment]
Nobody said 5.* was _required_.  CRAN itself uses 4.6.* on Windows, 4.9.* is widely used.

**Comment by systemdown** [comment]
Yes you're right, sorry. I will do some testing and see which version makes sense for me.

**Comment by eddelbuettel** [comment]
If you find a viable minimal solution -- gcc/g++/gfortran 4.6 or 4.8 or 4.9 or ... --- maybe you could summarize in a paragraph?   This is the third time it has come up this week across two package so I should probably document this better somewhere (eg Rcpp FAQ).

**Comment by systemdown** [comment]
Okay, so - I have had success compiling both R v3.2.5 and installing RcppArmadillo via Bioconductor with gcc/g++/gfortran v4.7.2.

I'm using the CentOS "devtoolset-1.1" package which provides (amongst other tools) gcc/g++/gfortran ("GCC" from here on in) v4.7.2.

I noticed that the "C++11" compiler flag was enabled during R compile and similarly for RcppArmadillo - the "new" C++ language features are now supported so everything works.

FYI - I had no issues compiling the rest of my Bioconductor packages (DESeq2, edgeR, ChIPQC, Rsubread, limma etc) nor any of their CRAN dependencies.

Instructions to install and enable "devtoolset-1.1" in CentOS (I'm using CentOS v6.7 Final):

http://ask.xmodulo.com/upgrade-gcc-centos.html
http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos


Notes / Other things I tried:

* I originally wanted to try GCC v4.6.x but couldn't find a "nice" way to install for CentOS (and didn't want to screw around compiling the compiler)

* So I next tried GCC v4.8.2 (from "devtoolset-2") which did not succeed (R v3.2.5 did not get beyond the "configure" stage due to some issue with Fortran 77). Surprising since v4.7.2 is working and on the evidence, v4.9.x is known to work (but not tested by me). I didn't want to spend time debugging this so moved to the earlier "devtoolset-1.1" with GCC v4.7.2 which worked.

* I don't expect GCC v4.7.2 to work forever especially since the "C++14" standard has been fully implemented since GCC 5.1 (12 months ago) - my next move when things break in my R pipelines will probably be to GCC 5.x, if by that time, it's well supported by the R community

**Comment by eddelbuettel** [comment]
For your 'safety', though, the R gatekeepers are conservative and it took considerable prodding to get to C++11.  Supporting that on your end would be wise.  Conrad has also threatened to withdraw support for older C++ (ie C++ 98) at some point.

Yet C++14 is, as far as R is concerned, a while away.

I'll try to distill your notes into something in the Rcpp FAQ.

**Comment by systemdown** [comment]
Okay great, thanks. Good to hear that C++11 will be in R for a while and equally good to hear that C++14 is a while off yet. As a naive end-user of R I'm just happy when it works. I don't want to be playing with multiple compiler versions if I can avoid it.
