### ISSUE TITLE
Correct configure.ac for setting the LAPACK feature #define

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#99]
Per extended discussion with @baptiste in [this answer's comment thread](http://stackoverflow.com/a/35953211/143305) (and why it wasn't here is something unanswerable).

**Comment by eddelbuettel** [comment]
The fix is, I think, to use this code:

```c++
if test x"${hasRlapack}" == x""; then
    ## We are using a full Lapack and can use zgesdd -- so #undef remains
    AC_MSG_RESULT([system LAPACK found])
    have_good_lapack="#undef"
    arma_crippled_lapack="ARMA_CRIPPLED_LAPACK"
else
    if test x"${newR}" == x"yes"; then
        ## The R versions are recent enough and has an augmented internal Rlapack
        AC_MSG_RESULT([fallback LAPACK from R 3.3.0 or later used])
        have_good_lapack="#undef"
        arma_crippled_lapack="ARMA_CRIPPLED_LAPACK"
    else     
        ## We are using an older R's subset of Lapack and CANNOT use zgesdd etc, so we mark it
        AC_MSG_RESULT([R-supplied partial LAPACK found])
        AC_MSG_WARN([Some complex-valued LAPACK functions may not be available])
        have_good_lapack="#define"
        arma_crippled_lapack="ARMA_CRIPPLED_LAPACK 1"
    fi
fi
```

which flips the `undef` and `define` around.

**Comment by baptiste** [comment]
The fix is working, thanks!
(BTW you see why it was hard for me to follow the configure logic: the logic was actually inverted, so now it makes sense that it didn't make sense to me).

**Comment by eddelbuettel** [comment]
Yes, the logic was right but the _assigned values_ were inverted. I didn't check the generated header file well enough -- and the lack of a unit test haunted us.  Now that with R 3.3.0 we have a complete fallback we can add a test and run it on R (>= 3.3.0).
